### ISSUE TITLE
OAuth2 support is partial

### ISSUE THREAD

**Issue by csteez** [rswag/rswag#101]
Hi! 
After I edited the erb file for the index for swagger so it would authenticate, I noticed that the token isn't being used. Is there a way to use the token from the auth flow? We only support OAuth2. 

Am I supposed to re-authenticate on the backend? I just don't see a way the bearer token is ever used.

**Comment by csteez** [comment]
I figured it out. Documentation of OAuth2 support would have been nice :)

**Comment by domaindrivendev** [comment]
Glad you got things figured out. Re documentation, it is an FOSS project so you could always submit a PR to update the docs :)

**Comment by csteez** [comment]
Will do once I'm finished documenting our Api :)
