### ISSUE TITLE
Issue with 404, 422 when errors are raised

### ISSUE THREAD

**Issue by erlandsona** [rswag/rswag#103]
So I'm trying to test the following code
```ruby
class ThingController < ApiController
  def create
    @something = Thing.create!(thing_params)
  end

  def show
    @something = current_user.things.find(params[:id])
  end

  private

  def thing_params
    params.permit(:name)
  end
end
```
Where name is empty `#create` or ActiveRecord::RecordNotFound in the case of the current_user not owning the thing with that id.

rswag doesn't seem to be allowing rails to do it's thing and render the correct response codes as a result of the failures.

I may have more time to dig into this tomorrow, would love some help though :) Thanks!

**Comment by daniel-sullivan** [comment]
Having this same issue. Did you end up resolving?

**Comment by erlandsona** [comment]
Actually yeh! Thanks for reminding me. It's actually an issue with Rails' default configuration for the Test environment.

[Rails Http Error Config for Test ENV](https://github.com/eliotsykes/rspec-rails-examples/blob/master/spec/support/error_responses.rb)
See the [commented issue](https://github.com/rails/rails/pull/11289#issuecomment-118612393) for more details.
