### ISSUE TITLE
OpenAPI 3.0

### ISSUE THREAD

**Issue by tadassce** [rswag/rswag#104]
Thanks for the amazing project. I'm not involved at the moment and don't expect anything.

[OpenAPI 3.0 Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) has been out for a while, I was wondering if there are any plans for supporting that? Thanks <3

**Comment by plainprogrammer** [comment]
I am interested in contributing to this. My employer is using the gem for one of our projects and we'd like to be able to use OpenAPI 3.0 features. Is there anyone else working on, or interested in working on this capability?

**Comment by ndbroadbent** [comment]
I'd be interested in contributing to this as well.

**Comment by hwo411** [comment]
I'd also be interested in this

**Comment by agentGreg** [comment]
@tadassce have you maybe progressed on this issue?

**Comment by shifakhan** [comment]
@domaindrivendev thanks for the project! just bringing your attention to this issue. Do you have any plans re this one? Thanks again!

**Comment by mlensment** [comment]
+1

**Comment by chdezmar** [comment]
+1

**Comment by rwxdash** [comment]
> I am interested in contributing to this. My employer is using the gem for one of our projects and we'd like to be able to use OpenAPI 3.0 features. Is there anyone else working on, or interested in working on this capability?

I'd like to contribute to this as well. We are using rswag extensively in our projects, and current version isn't enough for us. Especially for multiple requests/responses, e.g. `oneOf`.

**Comment by jdanielian** [comment]
I am currently working on a 3.0 compliant fork off of this gem. I am not sure exactly the right way to proceed however. One decision I made early on in coding up the 3.0 compliant version is that for simplicity it would NOT be backward compatible with 2.0 swagger output. Basically if you want to generate 3.0 swagger, you would use the new open-api-3-rswag gem.

I find rswag to be an incredible library, we have adopted it at a couple projects - and its made an enormous impact. It seems like the current owner is not too interested in adding new features, moving to 3.0. It looks like PRs are kind of stagnating, etc. Which is perfectly fine!! :) He has certainly done more than his fair share, at his leisure he can progress it when (if?) it suits him. Thank you @domaindrivendev and all who have created the gem as it is today.

So, my fork has a branch that has 3.0 compliant output working right now in *very limited* scenarios. It is NOT ready for global use. I am working on updating all the existing specs to pass given the 3.0 structure shift in output. I also like some defaults for capturing request and response output in the generated swagger, and made some opinionated decisions to incorporate these into the framework.

Eventually, I would like to release a 3.0 version of my branch to a different named gem (open-api-3-rswag or something) assuming that is ok with the original owner @domaindrivendev. I really haven't contributed much before, so I *think* that is the proper etiquette - but please let me know if not.

**Comment by jdanielian** [comment]
https://github.com/jdanielian/open-api-rswag

If you are interested in watching the progress- here is the repo. I need to update the readme, add some additional tests, and update the Travis CI script to publish the gems to rubygems.org. 

So be patient, but I have a 3.0 compliant version of this pretty close to working. Eventually I’ll be a maintainer, open it up to contributions etc. So my goal is that we’ll have an OpenApi 3.0 version of this fabulous gem ready to go soon!

**Comment by philsturgeon** [comment]
@jdanielian heads up, its OpenAPI not Open API so maybe the repo name should be `openapi-rswag`. Cool to see you're doing the work!

**Comment by say8425** [comment]
@jdanielian that was awesome!

**Comment by J-Swift** [comment]
Hey @jdanielian this is great! I noticed you don't have issues enabled for the repo though, so what is the best place to file bugs?

**Comment by BookOfGreg** [comment]
@jdanielian and other readers to this issue. This gem is now part of an organization, I'll be looking into potential OpenAPI 3 upgrades including your fork of the gem. I'd love to see if we can pull your contributions back in to the main line, or upgrading to it by other means. And other contributors are always very welcome to a project.

**Comment by jdanielian** [comment]
That is fine - not sure you will be happy with my work, as I made some opinionated decisions on NOT making the 3.0 branch backwards compatible. But feel free to take what you need.

**Comment by top4ek** [comment]
@jdanielian thanks for such a great work. I've noticed too that Issues are disabled for your fork. I have a question about request_body_json. It's a bug or I missunderstood documentation.

**Comment by CaioBianchi** [comment]
@jdanielian Amazing work! Thank you.

**Comment by tf-tony** [comment]
@BookOfGreg  - Ready to volunteer so I can update my API docs.  You have any contrib guidelines to follow?

**Comment by BookOfGreg** [comment]
Contributors always welcome. [Contributing.md](https://github.com/rswag/rswag/blob/master/CONTRIBUTING.md)
Currently I've been making a list of things to remove and add for OpenAPI3, there's incredibly little docs for the differences between the two because they almost always point to the automated tools which isn't a huge help when I'm trying to make an automated tool 😆 .
The trick is trying to do it in a way that causes us no breakages which I think we can actually do.

**Comment by philsturgeon** [comment]
@BookOfGreg this spreadsheet with all the keywords might help you keep track of it all. https://docs.google.com/spreadsheets/d/1KT7WlHM5ED-yWbLEovEGjN8ieqnY2_agkj3pkRRAw1Y/edit?usp=sharing 

I made this working on things for @stoplightio, trying to make sure our OAS2 and OAS3 support is as complete as possible. Just chuck in "Y", "No" or "na" and it'll count things up.

**Comment by BookOfGreg** [comment]
I can't access this at work but I will be working from this soon enough, this is very appreciated.

**Comment by surjay** [comment]
Are there any timetables for either getting the fork (or similar features) into the mainline? I'd prefer to avoid switching to a fork that has/will diverge from where the main gem is heading/headed.

**Comment by BookOfGreg** [comment]
I'm doing this in my own personal time and nobody seems to be helping so I can only say it will happen when it happens. I'm one person and this is open source.

The difference between the fork and this is I'm going to try do it while maintaining backward compat, probably by detecting if you're writting to a swagger 2 or 3 file and allowing extensions for openapi3 if you're on it.

Phil Sturgeon above already posted an extremely helpful guide on the differences between the two for me so that will make the job easier when we get to it.

**Comment by zinosama** [comment]
@BookOfGreg being able to support backwards compatibility is great. however, this issue has been here for two years now. imo it's a lot more beneficial for the community to have working but breaking support for 3.0 than no support at all. 

It'll be helpful if you can clarify the direction of you're taking with this gem, as well as the best way for folks to contribute (is there a todo or wish list? do you have a wip PR folks can contribute to?).

Many thanks for doing this!

**Comment by J-Swift** [comment]
I normally try to +1 in emoji, but I just had to say I 100% agree with @zinosama - 3.0 support is more important than backwards compatibility in my mind and for my use cases.

Also agree that having a clear framework in place for contributing (what needs to be done etc) will go a long way.

**Comment by hlascelles** [comment]
Agree, we would like to try it and help too. _Maybe_ this would be more than a PR (until it is ready to merge back into this repo). Would it need a repo fork with its own issues and so on? And yes, definitely breaking change would be fine for us too.

**Comment by BookOfGreg** [comment]
https://github.com/rswag/rswag/pull/286
Nearly there.

**Comment by BookOfGreg** [comment]
Merged. Version 2.3.0 of rswag supports Openapi 3.0.

Just change your swagger_helper from swagger: 2.0 to openapi: '3.0.1' and it will attempt to output openapi3 with no changes needed to your tests.
You will get deprecation warnings if there's anything that can be made more like openapi 3's syntax, usually done in the swagger_helper.

If anyone notices that it does not generate valid openapi3 on their existing tests please open an issue. Not we know that the common trick of adding example onto the response metadata will result in a validation warning, we will look at that for 2.4.x

Hope this helps!
