### ISSUE TITLE
Swagger "oneOf" for path params?

### ISSUE THREAD

**Issue by mathias** [rswag/rswag#106]
There isn't much about the Swagger DSL itself here, so it is unclear how much to expect out of this gem or what the "best practices" are. How would you define a path param that can be one type or another? Like this:

```ruby
      parameter(
        one_of({
          "$ref" => "#/parameters/user_name_param",
          "$ref" => "#/parameters/uuid_path_param",
        })
      )
```
and assuming a shared setup like:

```ruby
  parameters: {
        user_name_path_param: {
          name: :user_name,
          type: :string,
          in: :path,
          required: true,
          description: "A username that uniquely identifies an user",
          pattern: '^[a-z0-9\-]{2,32}$',
          example: "mathias"
        },
        uuid_path_param: {
          name: :uuid,
          type: :string,
          in: :path,
          required: true,
          description: "A UUID that identifies an object",
          pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$',
          example: "f9fa5355-be64-45f0-a102-583c4e5e8644"
        },
```
(except this does not work)

**Comment by domaindrivendev** [comment]
Apologies for the lack of documentation. I’d love to improve it but just don’t have the cycles right now. If you’re interested in contributing to better docs, a PR would be more than welcome.

With this gem, there’s an assumption that you’re familiar with the Swagger specification itself. If you know how to describe your API with Swagger then it should map directly to the rswag DSL. So, I would suggest investigating how you might represent your use case with Swagger first, then the application in this gem will be relatively straightforward.

**Comment by fstybel** [comment]
@mathias  Is it possible to use `one_of` in rswag?

**Comment by irwangunardi** [comment]
I have no luck using all_of in rswag

**Comment by dkniffin** [comment]
I know this is an old issue, but it came up in results, so I'm going to put this here for reference.

If you need `oneOf`, you can do something like this:

```rb
schema(
  type: :object,
  properties: {
    whatever_key: {
      oneOf: [
        { type: :string },
        { type: :integer }
      ]
    }        
)
```

Also note: nil/null is a special case. You can handle that like this:

```rb
schema(
  type: :object,
  properties: {
    whatever_key: {
      type: :string,
      'x-nullable': true
    }        
)
```

This might be something good to add to the readme. @domaindrivendev any chance that it would get reviewed and merged anytime soon?
