### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by jbabe** [rswag/rswag#109]
We have cases where we like to put our Swagger UI and swagger.json behind authentication. Is there any interest in adding something like Basic Authentication to the following locations?

https://github.com/domaindrivendev/rswag/blob/master/rswag-ui/app/controllers/rswag/ui/home_controller.rb#L4

https://github.com/domaindrivendev/rswag/blob/master/rswag-api/lib/rswag/api/middleware.rb#L20

**Comment by jbabe** [comment]
I realize this could be handled by rack middleware outside of the gem (and calling via `insert_before`) but would be nice to have it built in and activated via configuration.

**Comment by domaindrivendev** [comment]
The following 3 lines in `application.rb` seems to do the trick:

```ruby
Rswag::Api::Engine.config.middleware.use Rack::Auth::Basic do |username, pwd|
  username == 'tom' && pwd == 'secret'
end
```

Fairly trivial and expresses the intent nicely so I'm not convinced it's worth baking something directly into rswag.

**Comment by jbabe** [comment]
@domaindrivendev that's fair - I was going to cut a PR but I think I'll close this issue instead. 

Appreciate the quick response!

**Comment by ctrlshiftjv** [comment]
how did you go about it jbabe? I want to make the user login if they want to view my api-docs
