### ISSUE TITLE
RSpec failing on RSwag tests

### ISSUE THREAD

**Issue by imRohan** [rswag/rswag#119]
Not sure how this could be happening, but running `rspec` fails on the `path` tag that's required for rswag 
```
NoMethodError:
  undefined method `path' for RSpec::ExampleGroups::DERP:Class
```
Im using RSpec 3.6

**Comment by hobertro** [comment]
Ran into this today and found this link:

https://github.com/domaindrivendev/rswag/issues/60

It resolved the problem but I don't know if it fixes the root cause

**Comment by imRohan** [comment]
Hmm yes, I was reading that earlier. I tried adding `type: :request` to the top level describe, but that didn't fix it for me. Not sure if I'm doing some wrong?
