### ISSUE TITLE
Do references have to be under #/definitions/ ?

### ISSUE THREAD

**Issue by douglasrlee** [rswag/rswag#120]
I added references to a custom location `controllers` but when I try to actually reference them from my tests I am getting this error: `The fragment '/controllers' does not exist on schema c6ca8c54-47bf-5290-be91-fa4bbb3ed08f`

All I am doing is: `schema(:$ref => "#/controllers/some_controller")`

**Comment by domaindrivendev** [comment]
I believe so but to clarify you should refer the Swagger / OpenApi 2.0 spec

**Comment by domaindrivendev** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
