### ISSUE TITLE
Multiple "parameter" lines not generating correct request params

### ISSUE THREAD

**Issue by abevoelker** [rswag/rswag#130]
Following(-ish) the README, I created this spec:

```ruby
# spec/integration/users/registrations_controller_spec.rb
require "swagger_helper"

describe "User registration API" do
  let(:user) { FactoryBot.create(:user) }

  path '/api/users/registrations' do
    put "updates password" do
      security [ bearer: [] ]
      consumes 'application/json'
      parameter name: :current_password, in: :body, type: :string
      parameter name: :password, in: :body, type: :string

      response '201', 'password updated' do
        let(:Authorization) { "Bearer #{::UserToken.encode(user)}" }
        let(:current_password) { "currentpw" }
        let(:password) { "updatedpw" }
        run_test!
      end
    end
  end
end
```

```ruby
# spec/swagger_helper.rb
require 'rails_helper'

RSpec.configure do |config|
  # Specify a root folder where Swagger JSON files are generated
  # NOTE: If you're using the rswag-api to serve API descriptions, you'll need
  # to ensure that it's configured to serve Swagger from the same folder
  config.swagger_root = Rails.root.to_s + '/swagger'

  # Define one or more Swagger documents and provide global metadata for each one
  # When you run the 'rswag:specs:to_swagger' rake task, the complete Swagger will
  # be generated at the provided relative path under swagger_root
  # By default, the operations defined in spec files are added to the first
  # document below. You can override this behavior by adding a swagger_doc tag to the
  # the root example_group in your specs, e.g. describe '...', swagger_doc: 'v2/swagger.json'
  config.swagger_docs = {
    'v1/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'API V1',
        version: 'v1'
      },
      paths: {},
      securityDefinitions: {
        bearer: {
          type: :apiKey,
          name: "Authorization",
          in: :header,
        }
      }
    }
  }
end
```

The "Authorization: Bearer" header is sent correctly, however when I debug the `request.params` received by the `Users::RegistrationsController`, this is what it gets:

```ruby
request.params # => {"_json"=>"currentpw", "controller"=>"users/registrations", "action"=>"update", "registration"=>{"_json"=>"currentpw"}}
```

So it is only sending the `current_password` param and for some reason using `_json` for the param name. If I change the `let(:password)` to `let(:password) { raise "got here" }` it never executes, so it seems that `let` is not being called.

Are multiple `parameter` definitions not supported?

**Comment by domaindrivendev** [comment]
Take a closer look at the “post” example in the readme. For posts/puts, you just specify a single body parameter but of type object, and with as many properties as you need. Try this and make current_password and password properties

**Comment by abevoelker** [comment]
I did see that, however I can't change this API to nest all the parameters under a new parent param - these params have to all be at the root level.

I don't know if this is the "right" way to change this but I made this patch locally that seems to work ¯\\_(ツ)_/¯

https://github.com/abevoelker/rswag/commit/10b2dc0720386e98e46922ac34a8101470bc8271

**Comment by abevoelker** [comment]
Okay as I'm starting to learn Swagger I think I was misunderstanding this (my bad). Thanks for the pointer

**Comment by abevoelker** [comment]
Sorry, I misunderstood that really badly. My bad again

**Comment by LewisYoul** [comment]
Can I ask you @abevoelker how you managed to get these body parameters to render sensibly in the swagger UI? When I nest all of my properties inside a single `body` parameter as @domaindrivendev suggests the request works however when the documentation is generated it only creates a single `body` parameter into which all of the properties are nested. This doesn't seem particularly explicit. Is it expected behaviour? I would expect all of the individual properties (in the case below `type, with_geojson, page, per_page, buffer` to be listed individually.

**Comment by abevoelker** [comment]
@LewisYoul Yeah unfortunately I believe that's just how Swagger UI displays `body` parameters so it's expected; not sure you can work around it (although I'm far from a Swagger expert so who knows). FWIW you can see the same behavior if you view certain actions in Swagger's official pet store example app: https://petstore.swagger.io/#/store/placeOrder

**Comment by LewisYoul** [comment]
Thanks for the link, that's useful for visualisation!

**Comment by mediafinger** [comment]
I've noticed this is a 2 years old thread, but as I could not find any rswag documentation about adding multiple parameters to the JSON body at root level to create a proper swagger / OpenAPI 3.0 file, I'll add it here:

```ruby
      parameter name: {}, in: :body, schema: {
        type: :object,
        required: %w(amount asset_id target_address),
        properties: {
          amount: {
            type: :integer,
            description: "amount in fractional unit",
            example: 612,
          },
          asset_id: {
            type: :string,
            enum: Transaction::VALID_ASSET_IDS,
            description: "one of: #{Transaction::VALID_ASSET_IDS}",
            example: "btc",
          },
          target_address: {
            type: :string,
            description: "wallet address to withdraw to",
            example: "17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2",
          },
        },
      }
```

Basically just use `name: {}` instead of a "name".

**Comment by mediafinger** [comment]
I've noticed this is a 2 years old thread, but as I could not find any rswag documentation about adding multiple parameters to the JSON body at root level to create a proper swagger / OpenAPI 3.0 file, I'll add it here:

Using `name: {}` in the request spec works well with `rake rswag:specs:swaggerize`
  
```ruby
      parameter name: {}, in: :body, schema: {
        type: :object,
        required: %w(amount asset_id target_address),
        properties: {
          amount: {
            type: :integer,
            description: "amount in fractional unit",
            example: 612,
          },
          asset_id: {
            type: :string,
            enum: Transaction::VALID_ASSET_IDS,
            description: "one of: #{Transaction::VALID_ASSET_IDS}",
            example: "btc",
          },
          target_address: {
            type: :string,
            description: "wallet address to withdraw to",
            example: "17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2",
          },
        },
      }
```

But to make the specs pass, I had to monkey-patch the gem:

```ruby
module Rswag
  module Specs
    class RequestFactory
      def build_json_payload(parameters, example)
        body_param = parameters.select { |p| p[:in] == :body }.first
        body_param ? example.send(body_param[:name]).to_json : nil

      # this rescue is our monkey-patch
      rescue TypeError
        parameters
          .select { |p| p[:in] == :body }
          .dig(0, :schema, :properties)
          .keys
          .each_with_object({}) { |key, acc| acc[key] = example.send(key).as_json }.to_json
        # monkey-patch end
      end
    end
  end
end
```

_(inspired by @abevoelker's linked patch above)_

The resulting _swagger.yml_ looks right and my `run_test!` specs pass.

```yaml
# ...
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - amount
              - asset_id
              - target_address
              properties:
                amount:
                  type: integer
                  description: amount in fractional unit
                  example: 612
                asset_id:
                  type: string
                  enum:
                  - btc
                  - eth
                  description: 'one of: ["btc", "eth"]'
                  example: btc
                target_address:
                  type: string
                  description: wallet address to withdraw to
                  example: 17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2
```

Does anything speak against adding a _similar_ solution (with a condition instead of a rescue) to the gem itself?  
It it not implemented as it doesn't adhere to some JSON schema standard?  
(Which in my case is kinda irrelevant, as I am working on an existing API which I must not change.)

If there is a general interest in such a solution, I could prepare a PR with nicer code. At the moment I am not sure though, if I overlooked any implications.

**Comment by wscourge** [comment]
One workaround that works for us and is easier than monkey-patching is actually naming/enveloping the main `parameter` with our custom keyword `:root` (for better readability, it could be anything, ie. `:envelope`).

Example:

```
# spec/integration/users/registrations_controller_spec.rb
require "swagger_helper"

describe "User registration API" do
  let(:user) { FactoryBot.create(:user) }

  path '/api/users/registrations' do
    put "updates password" do
      security [ bearer: [] ]
      consumes 'application/json'
      parameter name: :root, in: :body, schema: {
        type: :object
        required: %w[password, current_password],
        properties: {
          password: {
            type: :string
          },
          current_password: {
            type: :string
          }
        }
      }

      response '201', 'password updated' do
        let(:Authorization) { "Bearer #{::UserToken.encode(user)}" }
        let(:current_password) { "currentpw" }
        let(:password) { "updatedpw" }
        run_test!
      end
    end
  end
end
```

**Comment by brunocalmels** [comment]
I was encountering a similar problem. In my case, I was just missing the line
```ruby
 consumes "application/json"
```
which is critical for the parameters to be correctly bundled. Just in case anyone faces such an issue...

**Comment by al3rez** [comment]
> I've noticed this is a 2 years old thread, but as I could not find any rswag documentation about adding multiple parameters to the JSON body at root level to create a proper swagger / OpenAPI 3.0 file, I'll add it here:
> 
> Using `name: {}` in the request spec works well with `rake rswag:specs:swaggerize`
> 
> ```ruby
>       parameter name: {}, in: :body, schema: {
>         type: :object,
>         required: %w(amount asset_id target_address),
>         properties: {
>           amount: {
>             type: :integer,
>             description: "amount in fractional unit",
>             example: 612,
>           },
>           asset_id: {
>             type: :string,
>             enum: Transaction::VALID_ASSET_IDS,
>             description: "one of: #{Transaction::VALID_ASSET_IDS}",
>             example: "btc",
>           },
>           target_address: {
>             type: :string,
>             description: "wallet address to withdraw to",
>             example: "17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2",
>           },
>         },
>       }
> ```
> 
> But to make the specs pass, I had to monkey-patch the gem:
> 
> ```ruby
> module Rswag
>   module Specs
>     class RequestFactory
>       def build_json_payload(parameters, example)
>         body_param = parameters.select { |p| p[:in] == :body }.first
>         body_param ? example.send(body_param[:name]).to_json : nil
> 
>       # this rescue is our monkey-patch
>       rescue TypeError
>         parameters
>           .select { |p| p[:in] == :body }
>           .dig(0, :schema, :properties)
>           .keys
>           .each_with_object({}) { |key, acc| acc[key] = example.send(key).as_json }.to_json
>         # monkey-patch end
>       end
>     end
>   end
> end
> ```
> 
> _(inspired by @abevoelker's linked patch above)_
> 
> The resulting _swagger.yml_ looks right and my `run_test!` specs pass.
> 
> ```yaml
> # ...
>       requestBody:
>         content:
>           application/json:
>             schema:
>               type: object
>               required:
>               - amount
>               - asset_id
>               - target_address
>               properties:
>                 amount:
>                   type: integer
>                   description: amount in fractional unit
>                   example: 612
>                 asset_id:
>                   type: string
>                   enum:
>                   - btc
>                   - eth
>                   description: 'one of: ["btc", "eth"]'
>                   example: btc
>                 target_address:
>                   type: string
>                   description: wallet address to withdraw to
>                   example: 17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2
> ```
> 
> Does anything speak against adding a _similar_ solution (with a condition instead of a rescue) to the gem itself? It it not implemented as it doesn't adhere to some JSON schema standard? (Which in my case is kinda irrelevant, as I am working on an existing API which I must not change.)
> 
> If there is a general interest in such a solution, I could prepare a PR with nicer code. At the moment I am not sure though, if I overlooked any implications.

Thanks for posting this.

**Comment by fabiaepv** [comment]
no need to monkey-patch you can add a :root parameter in body like someone said in the comments before and when you need to assign a value to a specific key like amount you can set it like this:

```
parameter name: :root, in: :body, schema: {
          type: :object,
          required: %w(amount asset_id target_address),
          properties: {
            amount: {
              type: :integer,
              description: "amount in fractional unit",
              example: 612,
            },
            asset_id: {
              type: :string,
              enum: Transaction::VALID_ASSET_IDS,
              description: "one of: #{Transaction::VALID_ASSET_IDS}",
              example: "btc",
            },
            target_address: {
              type: :string,
              description: "wallet address to withdraw to",
              example: "17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2",
            },
          },
        }
  
  let(:amount) { 612 }
  let(:asset_id) { "btc" }
  let(:target_address) { "17fnafpkX9fUA5V9FuPzKyX4jmq15dZZw2" }
  let(:root) {{ amount: amount, asset_id: asset_id, target_address: target_address  }}
```

and if you need to do some testing with different values you can work only with the amount, asset_id and target_address variables.. root it will always stay like that..

Hope it was helpful!! ✌️

**Comment by Houdini** [comment]
I can confirm that the problem persists. Either schema is valid or tests pass
