### ISSUE TITLE
uninitialized constant FactoryBot

### ISSUE THREAD

**Issue by gouvermxt** [rswag/rswag#133]
After I added FactoryBot in my project, I'm receiving this error when run `rake rswag:specs:swaggerize`.

> /usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.7.1/lib:/usr/local/bundle/gems/rspec-support-3.7.1/lib /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
/app/spec/support/factory_bot.rb:2:in `block in <top (required)>': uninitialized constant FactoryBot (NameError)
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core.rb:98:in `configure'
	from /app/spec/support/factory_bot.rb:1:in `<top (required)>'
	from /app/spec/rails_helper.rb:3:in `require'
	from /app/spec/rails_helper.rb:3:in `<top (required)>'
	from /app/spec/swagger_helper.rb:1:in `require'
	from /app/spec/swagger_helper.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/rswag-specs-2.0.3/lib/rswag/specs/swagger_formatter.rb:2:in `require'
	from /usr/local/bundle/gems/rswag-specs-2.0.3/lib/rswag/specs/swagger_formatter.rb:2:in `<top (required)>'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:227:in `require'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:227:in `rescue in custom_formatter'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:224:in `custom_formatter'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:177:in `find_formatter'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:146:in `add'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:878:in `add_formatter'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `each'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:23:in `configure'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'

**Comment by gouvermxt** [comment]
Closing since it was an error in my rspec configuration.

**Comment by GabrielDVpereira** [comment]
Hey, where were you mistaken? I'm getting the same error but I can't find it anywhere
