### ISSUE TITLE
Found a possible security issue

### ISSUE THREAD

**Issue by ransombriggs** [rswag/rswag#135]
I found a possible security issue and was wondering your preferred method of reporting.

**Comment by domaindrivendev** [comment]
Hi @ransombriggs. Thanks for reaching out. Could you email me via the "Email me" link on the following page: https://rubygems.org/profiles/domaindrivendev

**Comment by jtannas** [comment]
We've since added https://github.com/rswag/rswag/blob/master/SECURITY.md explaining how to report Security issues. Closing Issue.
Thank you for the report :bow:
