### ISSUE TITLE
integrate with rubocop and rubocop-rspec

### ISSUE THREAD

**Issue by ryan-ukc** [rswag/rswag#138]
Creating a test with a single run_test! method results in a rubocop failure on the metric RSpec/EmptyExampleGroup

Could this gem have a way of integrating with rubocop and rspec so rswag tests are recognised?

**Comment by domaindrivendev** [comment]
I’m not familiar with those gems so some additional context and detail would be helpful.

However, you can split out the run_test! method into a more idiomatic “before” / “example” block pair and this might help, especially if rubocop is for static analysis. Read the following readme section for details:

https://github.com/domaindrivendev/rswag/blob/master/README.md#the-rspec-dsl

**Comment by ryan-ukc** [comment]
The rubocop-rspec gem is part of the rubocop repo https://github.com/rubocop-hq/rubocop-rspec

In order to use rswag we are needing to exclude the rubocop linters for the following issues:

RSpec/DescribeClass
RSpec/EmptyExampleGroup
RSpec/RepeatedDescription
RSpec/RepeatedExample
RSpec/ScatteredSetup

It is a concern to need to write rspec tests in a different way to use the rswag gem

**Comment by domaindrivendev** [comment]
As I said above - run_rests! is a convenience method but you can ignore it and write your specs with “before” and “it” blocks too as described in the link I provided above

**Comment by jimeh** [comment]
I believe this issue isn't directly related to rswag. As there's not much rswag can do aside from modifying the DSL so all constructs are done via standard RSpec DSL methods.

I think a better approach would be to create a separate `rubocop-rswag` gem that patches up `rubocop-rspec` to not complain about rswag stuff, and maybe also have it lint for best practises of rswag itself.

**Comment by dvandersluis** [comment]
I don't know `rswag` at all but dropping in from rubocop to say that rubocop-rspec has configurable syntax for a while now and that might be able to help you out. See https://docs.rubocop.org/rubocop-rspec/usage.html#rspec-dsl-configuration
