### ISSUE TITLE
How to mark required fields in a nested param object

### ISSUE THREAD

**Issue by katelovescode** [rswag/rswag#139]
I'm using `rswag` to document my API-only Rails app that uses Strong Parameters.

model:
```ruby
class Call < ApplicationRecord
  belongs_to :interview

  validates :to, :from, :sid, presence: true, allow_blank: false
end
```

controller:
```ruby
 # POST /calls
  def create
    @call = Call.create!(call_params)
    json_response(@call, :created)
  end

  private

    def call_params
      # whitelist params
      params.require(:call).permit(
        :duration, :from, :sid, { statuses: [] }, :to, :interview_id
      )
    end
```

spec:
```ruby
  path "/v1/calls" do
    post "Creates a call" do
      tags "Calls"
      consumes "application/json"
      produces "application/json"
      parameter name: :call, in: :body, schema: {
        type: :object,
        properties: {
          interview_id: { type: :integer },
          duration: { type: :number, format: :float },
          from: { type: :string },
          sid: { type: :string },
          statuses: { type: :array, items: { type: :string } },
          to: { type: :string }
        },
        required: %w[interview_id from sid to]
      }
```

When I swaggerize it, though, there's no indication which fields are required (I'd expect something like an asterisk or comment in the model example).  Am I missing something?

<img width="751" alt="screen shot 2018-07-26 at 5 15 21 pm" src="https://user-images.githubusercontent.com/8364647/43291572-8e19f4fa-90f7-11e8-935c-6442d37d382d.png">

**Comment by domaindrivendev** [comment]
See above the JSON example, there's a tab bar that allows you to toggle between "Example Value" and "Model". If you click on the model tab, you'll see a full description of the object (as opposed to example JSON) and that should indicate which fields are required.

It's also worth noting that, if you're using a recent version, you can default to the "model" view instead of the "example" by setting the `defaultModelRendering` config value in the `rswag-ui.rb`:

```ruby
Rswag::Ui.configure do |c|
  c.swagger_endpoint '/api-docs/v1/swagger.json', 'API V1 Docs'
  c.config_object[:defaultModelRendering] = 'model'
end
```

**Comment by katelovescode** [comment]
Fantastic, thanks. In case anyone follows me in here on this issue; if you add "required: true" to the parameter definition as below:
```
parameter name: :call, in: :body, required: true, schema: {...}
```
you will also be able to see the parent param indicated as required.  Thanks @domaindrivendev !
