### ISSUE TITLE
How to skip a spec

### ISSUE THREAD

**Issue by sudoaza** [rswag/rswag#140]
**QUESTION**

im trying to skip some specific specs but doesnt seem to work, tried skip inside the request block and post block and no luck.

Is it possible to skip a spec?

**Comment by khalilgharbaoui** [comment]
@sudoaza are you able to skip specs now?
if so what was your solution?

**Comment by khalilgharbaoui** [comment]
My solution was to use the rspec `xit` as a callback instead of `run_test!`

Example:
```
response '403', 'forbidden' do
  xit
end
```
This is not documented anywhere but it actually skips the test but keeps it in the documentation.

Hope this helps.

@domaindrivendev please add this to the documentation!

**Comment by jtannas** [comment]
Heyo - new volunteer here sorting through the issue backlog and came across this.
I'm hoping to get a wiki going soon with common problems, and this seems like a good candidate for an FAQ.

**Comment by jtannas** [comment]
Added to the Wiki here: https://github.com/rswag/rswag/issues/140#issuecomment-449047723
