### ISSUE TITLE
Clarify README for the different security options

### ISSUE THREAD

**Issue by rprieto** [rswag/rswag#141]
The README has a great example for Basic auth. Since it uses a convention-based setup (`security [basic: []]` means you need to do `let(:Authorization) { }`), it would be very helpful to explain how the other two options work (`api_key` and `oauth`).

For example, I have an API Key called `X-API-TOKEN`. The Swagger definition is:

```rb
# spec/support/swagger_helper.rb
securityDefinitions: {
  apiToken: {
    type: :apiKey,
    name: 'X-API-TOKEN',
    in: :header
  }
}
```

How should we configure the following entries? 

```rb
# spec/api/my_spec.rb
get 'Get something' do
  security [ ??? ]
  response '200', 'Success' do
    let(???) { "my-test-api-key" }
  end
end
```

Thanks!

**Comment by rprieto** [comment]
It seems to work with the following syntax. If that's the right way could it be in the README?

```rb
get 'Get something' do
  # here, use the name of the security definition 
  security [ apiToken: [] ]
  response '200', 'Success' do
    # here, use the HTTP header itself 
    let('X-API-TOKEN') { "my-test-api-key" }
  end
end
```

I think something is still off, because if a request decides **not** to send a token (e.g. to test `HTTP 401`), then it crashes with:

```
undefined method `X-API-TOKEN' for #<RSpec::ExampleGroups::Chatrooms::ChatroomsId::Get::ChatroomDetail:0x00007fa7b45c7688>`.
```

**Comment by paulomcnally** [comment]
Has anyone found a solution to this?

I can't find a way to pass the value in the correct way to the header.

**Comment by ahmedzoha029** [comment]
@paulomcnally  
security [ apiToken: [] ]
let('X-API-TOKEN') { "my-test-api-key" }
works for me

**Comment by paulomcnally** [comment]
**[name]_spec.rb**

```
security [api_key: []]
...
response(200, 'successful') do
  let(:api_key) { 'fake_api_key' }
   run_test!
end
```

**spec/swagger_helper.rb**

```
...
components: {
  securitySchemes: {
    api_key: {
      type: :apiKey,
      name: 'api_key',
      in: :header
    }
  }
}
...
```

This work for me, but on controller receive:

```
header_name = 'api_key'
header = request.headers[header_name] || request.headers['HTTP_API_KEY']
```

`api_key` work for request, but `HTTP_API_KEY` work for documentation generated with swagger.
