### ISSUE TITLE
Exclude params in a test

### ISSUE THREAD

**Issue by jsartin513** [rswag/rswag#145]
Thanks for this gem, it's been a huge help to us!

We can't test a lot of our 400-status use cases because we're testing the case of a missing parameter. If we don't define the parameter, we get a `NoMethodError` trying to run the test. 
We have in some cases worked around it by setting the parameter to nil, but that's not testing the case that we're looking for.

Is there a way to do this? Or would this be something you might add in the future?

**Comment by kubi-dev** [comment]
> We have in some cases worked around it by setting the parameter to nil, but that's not testing the case that we're looking for.

It is fine, you should be happy with this solution

**Comment by jaydorsey** [comment]
@jsartin513 can you post an example of one of your specs? I found that setting `required: false` on my parameter definitions allowed me to run the tests & generate the documentation without having to pass in the parameter as nil (or assign a value).
