### ISSUE TITLE
How to check an email has been enqueued?

### ISSUE THREAD

**Issue by cmunozgar** [rswag/rswag#147]
Hi there!

I'm trying to make a test for an API endpoint where it makes several actions and then enqueue an email to be delivered using the `deliver_later` method and enqueuing it in Sidekiq.

How can I test this inside the current `run_test! do |response|`block?

Thanks in advance!

**Comment by jfloff** [comment]
I was just faced with this, and it was not an easy task. This is less of a rswag and more of a Sidekiq issue but I will detail what I did in my project. 

So, on the `run_test!` block I have something like this to check a specific mailer:
```
run_test! do |response|
          # check mailer
          expect(sidekiq_count_mailer(UserMailer, :delivered_email)).to eq(1)
          sidekiq_drain_mailer
          expect(sidekiq_count_mailer(UserMailer, :delivered_email)).to eq(0)
end
```
This will first check if the sidekiq queue of the `UserMailer.delivered_email` has 9 emails pending. Then I drain the queue (note, drain actually processes the background sidekiq job), and after draining I check if all the emails were delivered. 

But now you ask me: what are those `sidekiq_count_mailer` and `sidekiq_drain_mailer` functions? Those I had to add myself, here is the helper that I added:
```
# spec/support/sidekiq_helpers.rb

module SidekiqHelpers
  # See more info here:
  # https://github.com/mperham/sidekiq/wiki/Testing
  # https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb
  # https://github.com/mperham/sidekiq/wiki/API


  def sidekiq_select_mailer(wanted_mailer_class, wanted_mailer_method)
    wanted_mailer_class = wanted_mailer_class.to_s
    wanted_mailer_method = wanted_mailer_method.to_s

    return ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper.jobs.select{ |mailer|
      class_name = mailer['args'][0]['arguments'][0]
      method_name = mailer['args'][0]['arguments'][1]

      class_name == wanted_mailer_class and method_name == wanted_mailer_method
    }
  end

  def sidekiq_count_mailer(wanted_mailer_class, wanted_mailer_method)
    return sidekiq_select_mailer(wanted_mailer_class, wanted_mailer_method).count
  end

  def sidekiq_drain_mailer
    ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper.drain
  end

end
```

Then on your `spec_helper.rb` you have to add:
```
# Sidekiq
require 'sidekiq'
require 'sidekiq/extensions/action_mailer'
require 'sidekiq/extensions/active_record'
require 'sidekiq/extensions/class_methods'
require './spec/support/sidekiq_helpers'

# and then include the new helper
RSpec.configure do |config|
  config.include SidekiqHelpers
  ...
end
```

I think this might do it. If not, feel free to ping me. 

Other tip: You might want to add a before hook that clears the sidekiq queues before each test, more or less like this:
```
  # clear queues before each run
  config.before(:each) do
    Sidekiq::Worker.clear_all
  end
```

-

**Comment by jtannas** [comment]
Looks like this question has been answered already but I'll toss in one more suggestion before I close it for anyone who comes across this ticket:

```ruby
  run_test! do
    expect(ActionMailer::Base.deliveries.count).to eq(1)
    expect(ActionMailer::Base.deliveries.last.to).to eq('example@test.com')
  end
  ```
