### ISSUE TITLE
Trying to send the hash of object in query params but not working.

### ISSUE THREAD

**Issue by gurudath** [rswag/rswag#148]
let!(:some_model) { create(:some_model }  
path '/ast/dataset/search' do
    hash_value = { text: 'asdsdas' }.to_s
    let!(:value) { URI.escape(hash_value) }
    get 'Show of SomeController' do
      tags 'Api::V1::SomeController'
      produces 'application/json'
      consumes 'application/json'
      parameter name: 'some_model', in: :query, :type => :object
      response '200', 'search exadata' do
        schema type: :object,
               properties: {
                       type: :object,
                       properties: {
                           value: { type: :string },
                   }
               }
        run_test! do |response|
          expect(JSON.parse(response.body)['value']).to eq(some_model.value)
        end
      end
    end
  end

I am trying to send the hash of object in query params like below
https://example.com/ast/dataset/search?some_model={value: 'asdsdas'} 

I even tried with URL encoding but not working as its going as a string. As I did write or we need to pass differently?
Thanks in advance.

**Comment by gurudath** [comment]
Closing this issue as i was able to pass as form params. I think we need more documentation details. I was able to do as i dig deep in code and was able to achieve.

**Comment by tfwright** [comment]
@gurudath can you share what you did to work around this?

**Comment by dpaluy** [comment]
I resolved this:

```
parameter name: :last_updated, required: false,
                  in: :query, description: "Filter by time of last update",
                  schema: {
                     type: :object,
                     properties: {
                       from: {
                          type: :string,
                          format: :date,
                         description: "The start date. Format: YYYY-MM-DD"
                       },
                       to: {
                          type: :string,
                          format: :date,
                          description: "The end date. Format: YYYY-MM-DD"
                       },

                     }
                  },
                  style: 'deepObject', explode: true
```
