### ISSUE TITLE
doesn't actually run tests which are present like expect(data['message']).to eq('Not Found')

### ISSUE THREAD

**Issue by gurudath** [rswag/rswag#149]
run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['message']).to eq('Not Found')
        end
Run test is not failing if the data['message'] retuns as "Not Foundadssd" . It just passes . Then what is the need to use expect inside the run_test!

Please let me know how to handle this. Thanks

**Comment by jaydorsey** [comment]
@gurudath, are you seeing this behavior (test is passing when it shouldn't) when you run `rake rswag:specs:swaggerize`, or when you run your tests standalone?

**Comment by jtannas** [comment]
heyo - I'm a new volunteer helping clear out the issue backlog.
Since there was no response to Jay's request for more information I'm going to close this ticket as abandoned.
If you're still running into problems then feel free to open a new issue and I'll be happy to help. Cheers!
