### ISSUE TITLE
Update swagger-ui files

### ISSUE THREAD

**Issue by damir** [rswag/rswag#153]
I hit this bug which is fixed in v3.17.4. - https://github.com/swagger-api/swagger-ui/issues/4693
Thanks!

**Comment by iuri-gg** [comment]
Swagger UI Dist is at v3.19 I think. Can we update to latest version?

**Comment by jtannas** [comment]
Gem has since been updated to 3.52.5 so closing this issue immediately. Thanks for partipating! Cheers :slightly_smiling_face:
