### ISSUE TITLE
No route matches [GET] "/api-docs"

### ISSUE THREAD

**Issue by stevehanson** [rswag/rswag#157]
I'm trying to set up Rswag 2.0.5, but when I navigate to `/api-docs`, I get the Rails 404 page: 

> No route matches [GET] "/api-docs"

The weird thing is that when I look at my routes, I have:

```
rswag_api_path     /api-docs    Rswag::Api::Engine
```

The stack trace I see is:

```
Started GET "/api-docs" for 127.0.0.1 at 2018-10-11 15:16:19 -0500
(0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
↳ /Users/shanson/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/log_subscriber.rb:98

ActionController::RoutingError (No route matches [GET] "/api-docs"):

actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

This is reproducible with the following steps:

```shell
> rails new swagger-app
> cd swagger-app
```

Add the following to the Gemfile:

```ruby
gem "rswag-api"
gem "rswag-ui"

group :test do
  gem 'rswag-specs'
  gem 'rspec-rails'
end
```

Then:

```shell
> bundle
> rails g rswag:api:install rswag:ui:install
> RAILS_ENV=test rails g rswag:specs:install
> rails s
```

Navigate to http://localhost:3000/api-docs. Results in 404, even though URL is listed in routes.

Thanks for any help!

**Comment by stevehanson** [comment]
I was able to resolve this by adding the following to `routes.rb`:

```
mount Rswag::Ui::Engine => 'api-docs'
```

in addition to what was already added by the install generator:

```
mount Rswag::Api::Engine => 'api-docs'
```

This step wasn't listed in the Getting Started section of the Readme. Did something maybe go wrong when running the install generators? If this is expected behavior, I could take a pass at adding this to the Readme.

**Comment by nfedyashev** [comment]
@stevehanson thank you for posting this workaround!
Worked for me as well

**Comment by dLobatog** [comment]
I'm able to see the top-bar, but the API is empty if I mount `Rswag::Ui::Engine` at http://localhost:3000/api-docs/ . Are you able to see the actual API docs or just this:

![screenshot from 2018-10-24 11-16-20](https://user-images.githubusercontent.com/598891/47420293-5e22f300-d77e-11e8-9b84-8419f9665ecf.png)

?

For the record, the same JSON can be uploaded to http://editor.swagger.io/ and it doesn't throw any errors or warnings

**Comment by development-amold** [comment]
Same workaround here.....

I'm able to see the top-bar, but the API is empty if I mount Rswag::Ui::Engine at http://localhost:3000/api-docs/ 

Its working fine when I paste swagger.json here ==> http://editor.swagger.io/

any updates on this.....:(

**Comment by stevehanson** [comment]
@dLobatog @development-amold yes, I'm able to see the API documentation. I have the following config:

config/initializers/rswag-api.rb
```ruby
Rswag::Api.configure do |c|
  c.swagger_root = Rails.root.to_s + "/swagger"
end
```

config/initializers/rwag-ui.rb
```ruby
Rswag::Ui.configure do |c|
  c.swagger_endpoint "/api-docs/v1/swagger.json", "API V1 Docs"
end
```

spec/swagger_helper.rb
```ruby
require "rails_helper"

RSpec.configure do |config|
  config.swagger_root = Rails.root.to_s + "/swagger"

  config.swagger_docs = {
    "v1/swagger.json" => {
      swagger: "2.0",
      info: {
        title: "API V1",
        version: "v1",
      },
      basePath: "/api/v1",
      definitions: {},
    },
  }
end
```

config/routes/rb
```ruby
mount Rswag::Api::Engine => "api-docs"
mount Rswag::Ui::Engine => "api-docs"
```

**Comment by development-amold** [comment]
Thanks @stevehanson for the quick reply, Its showing API definitions when I explicitly add the following lines of code to initializers that would be recommended for working fine.

```
Rswag::Ui.configure do |c|
c.swagger_endpoint "/api-docs/v1/swagger.json", "API V1 Docs"
end
```

But it's still showing this error from this link:
https://online.swagger.io/validator/debug?url=http://api.lvh.me:3000/api-docs/v1/swagger.json

`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://api.lvh.me:3000/api-docs/v1/swagger.json"}]}`

How can I avoid/hide this error message from UI?

**Comment by hlascelles** [comment]
I too am seeing an empty page using the default path: https://localhost:3000/api-docs

If you specify the json file specifically though, it works: https://localhost:3000/api-docs/index.html?url=v1/swagger.json

I still get the online swagger validator red error box though, but you can ignore it. It'd be nice to have it hidden though.

**Comment by cesar3030** [comment]
I'm using docker-compose to run my rails app and I had the same issue. I could access the swagger-ui but I would get the `No route matches [GET] \"/api-docs/v1/swagger` when trying to access http://localhost:3000/api-docs/v1/swagger.json. 
I thought restarting the rails app could help since we added new routes so I did a `docker-compose down` then a `docker-compose up --build` and it solved my problem! 

Also, I get the swagger validator red error box when i'm requesting http://0.0.0.0:3000/api-docs but I don't when I request http://localhost:3000/api-docs

**Comment by stefanosx** [comment]
I found out that the problem is on the documentation
By running this command: 
```
rails g rswag:api:install rswag:ui:install
```

It is only generating the api installation and not the ui. If you split the command to:
```
rails g rswag:api:install
rails g rswag:ui:install
``` 

Everything should work fine.

**Comment by razanjoshi** [comment]
Worked after i changed my routes from:
```
mount Rswag::Api::Engine => "/api-docs"
mount Rswag::Ui::Engine => "/[api]-docs"
```
to
```
mount Rswag::Api::Engine => "api-docs"
mount Rswag::Ui::Engine => "api-docs"
```

**Comment by mathieujobin** [comment]
Why do we need both lines in `config/routes.rb` 

I tried setting them up on different path.
`Rswag::Ui::Engine` standalone works
while `Rswag::Api::Engine` does not seems to be doing anything

**Comment by BookOfGreg** [comment]
I can see the install for both halves is currently in the docs, perhaps it wasn't in the past.
Going to close as it looks resolved.
