### ISSUE TITLE
Strict schema validation

### ISSUE THREAD

**Issue by dikond** [rswag/rswag#163]
Hello 👋 

First of all - thanks for the awesome gem!

I'd like to know your thoughts about adding support for a schema validation. Per json-schema gem passing `strict: true` option will make sure we won't allow undefined properties to exist in our schemas.

    schema = {
      "type" => "object",
      "required" => ["a"],
      "properties" => {
        "a" => { "type" => "integer" }
      }
    }

    JSON::Validator.validate(schema, { "a" => 1 }, strict: true)
    #=> true
    JSON::Validator.validate(schema, { "a" => 1, "b" => 2 }, strict: true)
    #=> false

Not sure about best API for that feature though. We can allow for a global setting, but with an option to override this per individual specs too. Something like the following maybe?

    run_test!(strict: true)

**Comment by dikond** [comment]
After implementing this feature and trying it with out test suite I found that strict validation treat all properties as required. It was undesirable but as it turned out we can set the [additionalProperties](https://stackoverflow.com/q/17530762/2533567) to `false` to protect against undocumented props.

Since I don't need this feature anymore I'll close the issue. If you'll ever need to support strict schema validation feel free to use my fork.

**Comment by StarSheriff2** [comment]
I have tried adding the config.swagger_strict_schema_validation = true flag to my swagger_helper file but get this error: "undefined method `swagger_strict_schema_validation=' for #<RSpec::Core::Configuration:0x0000ffff8e894d90"

![Screenshot 2023-04-19 at 16 03 21](https://user-images.githubusercontent.com/61250665/233209881-c7aa8015-dfaa-4de1-8ccd-3e34b6a9a2a9.png)

**Comment by romanblanco** [comment]
@StarSheriff2, the fix for this has been merged, but 2.9.0 was not yet released. The release is in progress (see https://github.com/rswag/rswag/releases/tag/untagged-28ccb4041c8c97dc50eb).

**Comment by StarSheriff2** [comment]
Thanks, @romanblanco . So to be clear, this flag doesn't work for 2.8.0, right?

**Comment by romanblanco** [comment]
@StarSheriff2, correct. This is not included in the 2.8.0 (currently latest) version. The new release will be out within a few days.

**Comment by StarSheriff2** [comment]
well, in that case, please say so in the documentation. I see it's still there. Is there any reason for this?

**Comment by romanblanco** [comment]
@StarSheriff2, https://github.com/rswag/rswag/issues/569#issuecomment-1304468877 could help you until 2.9.0 is released.

**Comment by StarSheriff2** [comment]
Thank you, @romanblanco . I saw this already; however, I think this section of the README should be removed until the latest version is released to avoid misunderstandings.
If someone reads this README, they assume everything in there works with the current version:
![Screenshot 2023-04-21 at 09 15 38](https://user-images.githubusercontent.com/61250665/233673480-b8624612-ecea-46c0-8c4e-488a8548e392.png)
May be add a small note to the README saying this is a feature for the next release.

**Comment by michaelwebb76** [comment]
+1 I just lost half an hour to this

**Comment by romanblanco** [comment]
@michaelwebb76 @StarSheriff2 Thanks for letting me know and for your suggestions. Sorry for the headache.

The version 2.9.0 has been released now. 

In the future, please feel free to help us by submitting a PR fixing the issue.

**Comment by michaelwebb76** [comment]
Thanks for the fix.
