### ISSUE TITLE
partially update swagger.json

### ISSUE THREAD

**Issue by ConorSheehan1** [rswag/rswag#165]
I have a pretty slow test suite. In some cases I'd like to run a single test and have the it update the output for that section only. Currently if I run a single spec, it'll delete the output of all the specs that were not run.

Is there any way I can run a single spec and have it update the relevant section of swagger.json, rather than replacing the entire file?

**Comment by jtannas** [comment]
heyo - I'm a new volunteer sorting through the issue backlog. Sorry it took 3 years to get a response :bow: 
I think the right tool for your case is `rake rswag:specs:swaggerize`. It will generate the JSON documentation without actually running the tests, so it's very quick.
I'm going to close this issue now assuming we were too late, but if you're running into problems feel free to open a new issue and I'll be happy to help :slightly_smiling_face: 
Cheers!

**Comment by pawlarius** [comment]
Rswag is wonderful for the auto generated examples, but using `rake rswag:specs:swaggerize` will remove the examples that we need 🤔 
Is there any other ideas to partial update the rswag swagger?
