### ISSUE TITLE
share response between examples

### ISSUE THREAD

**Issue by ConorSheehan1** [rswag/rswag#166]
I have a slow test suite. I have lots of cases where I'd benefit from running a request once and running multiple specs for the response. For example:

This works fine, but I resubmit the request every time, even though the request and response are always the same.

```ruby
  let(:user_token) { @example_user.authentication_token }
  before(:each) do |example|
    submit_request(exmaple.metadata)
    @json_response = JSON.parse(response.body)
  end

  it 'should have foo' do
    expect(@json_response['foo']).to eq('foo')
  end

  it 'should have bar' do
    expect(@json_response['bar']).to eq('bar') 
  end
```

I'd love to be able to do something like this, but then I can't use any lets, so I can't authenticate.

```ruby
  let(:user_token) { @example_user.authentication_token }
  before(:all) do |example|
    submit_request(self.class.metadata)
    @json_response = JSON.parse(response.body)
  end
```

```
let declaration `user_token` accessed in a `before(:context)` hook at:
.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:71:in `block (2 levels) in add_path'
     
       `let` and `subject` declarations are not intended to be called
       in a `before(:context)` hook, as they exist to define state that
       is reset between each example, while `before(:context)` exists to
       define state that is shared across examples in an example group.
```

Is there any way to run a request in advance and then test it, while still authenticating?

**Comment by cesar3030** [comment]
Hi @ConorSheehan1!
Did you find a way make this work? 
I'm trying to do it too but it doesn't work.

**Comment by ConorSheehan1** [comment]
Hi @cesar3030 ,

Sorry, I didn't find a way to share responses between examples.
I ended up using shared examples instead to dry out the code, but I still have one request per example.

Please let me know if you figure out how to do it!

**Comment by cesar3030** [comment]
@ConorSheehan1 Thanks fro your answer. 
If I find a way to do this, I'll comeback to you for sure!

Cheers

**Comment by lezorich** [comment]
Hi @cesar3030, did you find a way to share responses?
