### ISSUE TITLE
Test should fail but it passes

### ISSUE THREAD

**Issue by belgoros** [rswag/rswag#169]
I wonder if `rswag` really tests something or is just used to generate the documentation.
Here is a simple example:
```
#spec/integration/languages_spec.rb

require 'swagger_helper'

describe "Languages API" do
    
  path '/languages/{language.id}' do    
    get 'Retrieves a language tag by its ID' do  
      tags 'Languages'
      security [ oauth2: [] ]      
      parameter name: :id, in: :path, type: :string
      parameter name: :Authorization, in: :header, type: :string
      
      response '200', 'Language found' do
        schema type: :object,
          properties: {
            id:  { type: :integer },
            tag: { type: :string }
          },
          required: ['id']

        let!(:language) { create(:language, tag: 'tag-1') }
        let(:user) { create(:user) }
        let(:headers) { valid_headers(user.username) }
        let(:Authorization) { headers['Authorization'] }
        
        run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['attributes']['tag']).to eq('tag-2')
        end
      end
      
      response '401', 'Authentication failed' do
        run_test!
      end
    end
  end
  
end
```
Here is the output when running `rake rswag:specs:swaggerize`:
```
/Users/Serguei/.rvm/rubies/ruby-2.5.0/bin/ruby -I/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.7.1/lib:/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rspec-support-3.7.1/lib /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
Generating Swagger docs ...
Swagger doc generated at /Users/Serguei/projects/decastore/decastore-api/swagger/v1/swagger.json
```
All tests (2) are passing. Weird because the first one should not, - I created a language with `tag: 'tag-1'` but tested the response for `tag: 'tag-2'. 

More of that, if I use RSpec runner to execute the above test `rspec spec/integration/languages_spec.rb`, it fails with no related reason:
```
Failures:

  1) Languages API /languages/{language.id} get Language found returns a 200 response
     Failure/Error:
       raise WrongScopeError,
             "`#{name}` is not available from within an example (e.g. an " \
             "`it` block) or from constructs that run in the scope of an " \
             "example (e.g. `before`, `let`, etc). It is only available " \
             "on an example group (e.g. a `describe` or `context` block)."
     
       `id` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:66:in `block (2 levels) in add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:65:in `each'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:65:in `block in add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:64:in `tap'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:64:in `add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:19:in `block in build_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `tap'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `build_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:9:in `submit_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:87:in `block in run_test!'

  2) Languages API /languages/{language.id} get Authentication failed returns a 401 response
     Failure/Error:
       raise WrongScopeError,
             "`#{name}` is not available from within an example (e.g. an " \
             "`it` block) or from constructs that run in the scope of an " \
             "example (e.g. `before`, `let`, etc). It is only available " \
             "on an example group (e.g. a `describe` or `context` block)."
     
       `id` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:66:in `block (2 levels) in add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:65:in `each'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:65:in `block in add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:64:in `tap'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:64:in `add_path'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:19:in `block in build_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `tap'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:17:in `build_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:9:in `submit_request'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:87:in `block in run_test!'

Finished in 0.24972 seconds (files took 1.1 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/integration/languages_spec.rb:12 # Languages API /languages/{language.id} get Language found returns a 200 response
rspec ./spec/integration/languages_spec.rb:31 # Languages API /languages/{language.id} get Authentication failed returns a 401 response
```
The provided in *README* integration test example DOES NOT contain `RSpec` prefix for `describe` block. If I add it:
```
RSpec.describe "Languages API" do

  path '/languages/{id}' do
    get 'Retrieves a language tag by its ID' do
...
```
the error message is different:
```
1) Languages API /languages/{id} get Language found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
     
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' did not contain a required property of 'id' in schema 980d621b-6289-58db-9a7f-69b705750e27
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:46:in `validate_body!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'
...
```
I created a [separate branch](https://github.com/belgoros/draft-api/tree/swagger-with-rswag) on a classic Rails API project to reproduce the issue.
What's wrong with that ? Thank you.

**Comment by jaydorsey** [comment]
Regarding your first point about the tests not failing when you run `swaggerize`, I think this is working as designed. The README mentions:

> Once you have green tests, run a rake task to auto-generate corresponding Swagger files and expose them as JSON endpoints

I've been generating documentation & running specs as separate steps. This was, however, based on observing the behavior. My first thought was that it was doing both (like the first part of your question). I can see why it could be confusing.

**Comment by vittoriabitton** [comment]
I'm having exactly the same issue...does anyone have a clue?

**Comment by jaydorsey** [comment]
@belgoros one of your errors is due to this line:

          parameter name: :id, in: :path, type: :string

You need to assign an ID somewhere, via a `let`, because path parameters are required. The error message isn't clear, I think you'll need to change your path:

    path '/languages/{id}' do

And add a `let` for the id so it gets passed through with the request:

    let(:id) { language.id }

**Comment by belgoros** [comment]
@jaydorsey thank you for your response. Here is the latest implementation:
```
#spec/integration/languages_spec.rb

describe "Languages API" do
  let(:language) { create(:language) }
  let(:user) { create(:user) }
  let(:headers) { valid_headers(user.username) }
  let(:Authorization) { headers['Authorization'] }
...

path '/languages/{id}' do    
    get 'Retrieves a language by ID' do
      tags 'Languages'
      security [ oauth2: [] ]
      parameter name: :id, in: :path, type: :string
      parameter name: :Authorization, in: :header, type: :string

      response '200', 'Language found' do
        schema type: :object,
          properties: {
            data: {
              '$ref' => '#/definitions/language'
            }
          },

        required: ['id']
        run_test!
      end

      response '404', 'Language not found' do
        schema '$ref' => '#/definitions/errors_object'

        let(:user) { create(:user) }
        let(:headers) { valid_headers(user.username) }
        let(:Authorization) { headers['Authorization'] }
        let(:id) { 'invalid' }

        run_test!
      end
    end
  end
end
```
I'm setting the id in `let`, it still fails as follows:
```
Failures:

  1) Languages API /languages/{id} get Language found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
     
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' did not contain a required property of 'id' in schema 6452aecc-ca60-5f85-9c71-0a9cbaee7e84
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:46:in `validate_body!'
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'

Finished in 0.60187 seconds (files took 1.07 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/integration/languages_spec.rb:41 # Languages API /languages/{id} get Language found returns a 200 response
```

**Comment by jaydorsey** [comment]
You're still missing an ID in the first example (200)
 
It should look closer to this:

```
path '/languages/{id}' do    
    get 'Retrieves a language by ID' do
      tags 'Languages'
      security [ oauth2: [] ]
      parameter name: :id, in: :path, type: :string
      parameter name: :Authorization, in: :header, type: :string

      response '200', 'Language found' do
        schema type: :object,
          properties: {
            data: {
              '$ref' => '#/definitions/language'
            }
          },

        required: ['id']
        let(:id) { language.id } # HERE

        run_test!
      end

      response '404', 'Language not found' do
        schema '$ref' => '#/definitions/errors_object'

        let(:user) { create(:user) }
        let(:headers) { valid_headers(user.username) }
        let(:Authorization) { headers['Authorization'] }
        let(:id) { 'invalid' }

        run_test!
      end
    end
  end
end
```

Any time you have a `:path` parameter, you *must* assign a value for rswag to substitute it for when it runs the specs

The same goes for any param marked `required: true`, you have to use a `let` (or maybe an ivar works too, idk, I use `let` for everything).

**Comment by jaydorsey** [comment]
~Also, I'm not 100% sure that schema is correct, for that type of request/response. You're doing a 200, based on a specified path with an ID. Usually I've only used the schema parameter when I'm submitting some kind of JSON (via POST or PUT). When you do a GET, you're just hitting a path with potential optional query parameters (which you don't have in this example) and headers (which you do, and you've assigned)~

~If you need to send JSON in the body along with your request, it's not really a GET at that point, it's a POST or a PUT (and then you could add a schema)~

Scratch that; it's a response schema you added, not a request schema (in the parameter). I think that should work fine (I don't use them)

**Comment by belgoros** [comment]
@jaydorsey Hmm, weird and looks like a duplication, - why should I declare `id` inside of `path` block if it is already declared in the upper level, - `describe`?  Another point - why is only `id` that `rswag` can't see in the failing test ? There are also `Authorization` which is also used in `path` block and declared outside of it ?
Anyway, adding `id` in the place as you suggested didn't solve the issue, the error is still the same and points clearly to the response schema:
```
1) Languages API /languages/{id} get Language found returns a 200 response
     Failure/Error: raise UnexpectedResponse, "Expected response body to match schema: #{errors[0]}" if errors.any?
     
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' did not contain a required property of 'id' in schema 6452aecc-ca60-5f85-9c71-0a9cbaee7e84
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:46:in `validate_body!'
     # /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
```

**Comment by belgoros** [comment]
I think, the problem is that rswag testing does not work properly with the JSON response schema, especially in [JSON API format](https://jsonapi.org/format/). It generates nevertheless the documentation, no matter if the tests pass or not. The only solution I found for the moment is to comment out `run_test` in failing examples after generating the documentation with `rake rswag:specs:swaggerize` to have the tests passing, - anyway, the same behaviour has already been covered with RSpec requests specs.

**Comment by jaydorsey** [comment]
> why should I declare `id` inside of `path` block if it is already declared in the upper level

You declare where it "goes" here:

    path '/languages/{id}' do

You have to define what to replace it with inside (or in an outer scope) a `response` block. Much like you defined it for your invalid test:

    let(:id) { 'invalid' }

There's a snippet of code somewhere inside rswag that basically says "Replace any path variables with the instance variable you assigned", and if you don't assign it, you get the error you've been getting.

> Another point - why is only `id` that `rswag` can't see in the failing test ?

Some of the error messages that bubble up either a) don't, or b) aren't clear (they get swallowed by rswag and raise an error, but don't quite clearly translate that to what the issue is with your setup/configuration)

> the error is still the same and points clearly to the response schema

Can you comment out your response schema, and change your test block to this:

```
run_test! do
  puts response.body
end
```

And paste your output here? I'm not using the response schema validation but I'd be very surprised if it didn't work. The first step would be to look at your actual response output.

> It generates nevertheless the documentation, no matter if the tests pass or not.

This is the same behavior I've observed so I think it's working as designed (but may not be working as expected)

**Comment by jaydorsey** [comment]
Now that I look at it, your example might be failing because you failed to define the headers inside the request. You did so for the 404 example. Is there a reason why you don't use those `let` assignments for headers/authorization in one of the outer blocks so they're available for both the 200 and 404 response example?

```
path '/languages/{id}' do    
    get 'Retrieves a language by ID' do
      tags 'Languages'
      security [ oauth2: [] ]
      parameter name: :id, in: :path, type: :string
      parameter name: :Authorization, in: :header, type: :string

      # Define users & header here so both response examples get a logged in user
      let(:user) { create(:user) }
      let(:headers) { valid_headers(user.username) }
      let(:Authorization) { headers['Authorization'] }

      response '200', 'Language found' do
        schema type: :object,
          properties: {
            data: {
              '$ref' => '#/definitions/language'
            }
          },

        required: ['id']
        let(:id) { language.id } # HERE

        run_test!
      end

      response '404', 'Language not found' do
        schema '$ref' => '#/definitions/errors_object'

        let(:id) { 'invalid' }

        run_test!
      end
    end
  end
end
```

**Comment by belgoros** [comment]
@jaydorsey As I mentioned [earlier](https://github.com/domaindrivendev/rswag/issues/169#issuecomment-464121489), all the parameters are declared in the very upper, `describe` block:
```
describe "Languages API" do
let(:language) { create(:language) }
  let(:user) { create(:user) }
  let(:headers) { valid_headers(user.username) }
  let(:Authorization) { headers['Authorization'] }
...
```
and are available for all the below blocks.

**Comment by jaydorsey** [comment]
> @jaydorsey As I mentioned [earlier](https://github.com/domaindrivendev/rswag/issues/169#issuecomment-464121489), all the parameters are declared in the very upper, `describe` block:
> 
> ```
> describe "Languages API" do
> let(:language) { create(:language) }
>   let(:user) { create(:user) }
>   let(:headers) { valid_headers(user.username) }
>   let(:Authorization) { headers['Authorization'] }
> ...
> ```
> and are available for all the below blocks.

Sorry, I was looking off of my snippet (which didn't include that piece). The `id` parameter isn't defined where your `response 200` block can see it, and is a likely cause of the error.

Edit: My debug suggestion is still sound: without knowing what's in that response, it's hard to say whether it's properly evaluating it and it's rswag that's failing. It's entirely possible that your auth strategy could be causing an issue and it's returning an error message related to authentication. The `run_test!` block runs it's own expectations and when they fail the error message isn't always shown clearly. In this case, the error is pretty clear: you aren't giving it an `id` to work with because you don't have a `let(:id) { language.id }` anywhere in the snippet you posted)

**Comment by jaydorsey** [comment]
@vittoriabitton you should post your code snippet so we can look at it. Probably as a separate issue, or a stackoverflow post (i'm not sure which the gem author prefers)
