### ISSUE TITLE
rswag:ui:copy_assets fails to copy assets

### ISSUE THREAD

**Issue by belgoros** [rswag/rswag#172]
I tried to run `either 
rake rswag:ui:copy_assets public` or `rake rswag:ui:copy_assets public/api-docs` and both failed with the below error:
```
rake aborted!
TypeError: no implicit conversion of nil into String
/Users/Serguei/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:1456:in `path'
/Users/Serguei/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:1456:in `block in fu_list'
/Users/Serguei/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:1456:in `map'
/Users/Serguei/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:1456:in `fu_list'
/Users/Serguei/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:550:in `rm_r'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/rswag-ui-2.0.5/lib/tasks/rswag-ui_tasks.rake:7:in `block (3 levels) in <main>'
```
Reproduced with `rswag 2.0.5` and ruby `2.5.0`, Rails `5.2.0`

**Comment by rromanchuk** [comment]
@belgoros try `bundle exec rake 'rswag:ui:copy_assets[public/api-docs]'`

**Comment by jtannas** [comment]
Looks like this was answered and is in the documentation now. Closing it now so that we can get our backlog under control.
If you're still running into issues though, feel free to open another ticket. Cheers! :slightly_smiling_face:
