### ISSUE TITLE
Break Config Into Files

### ISSUE THREAD

**Issue by tf-tony** [rswag/rswag#173]
I may be missing something, but is there a way to break the main swagger_helper into multiple files?

My definitions block is getting huge, I'd like to find a cleaner way of keeping the files.

**Comment by marcelotto** [comment]
I've separated the swagger docs into their own YAML files with this helper:

```rb
module RswagHelper
  BASE_API_DOCS_DIR = 'doc/rswag/'

  class << self
    def base_api_docs
      Dir.chdir BASE_API_DOCS_DIR do
        Hash[
          Dir.glob('**/*.yml').map do |base_api_doc_yml_file|
            [
              swagger_file(base_api_doc_yml_file),
              swagger_base_api_doc(base_api_doc_yml_file)
            ]
          end
        ]
      end
    end

    private

    def swagger_file(base_yml_file)
      base_yml_file.sub(/yml$/, 'json')
    end

    def swagger_base_api_doc(file)
      YAML.safe_load(File.read(file)).deep_symbolize_keys
    end
  end
end
```

You can then include them in your `swagger_helper.rb` like this:

```rb
  config.swagger_docs = {
    'swagger.json' => {swagger: '2.0'}
  }.merge RswagHelper.base_api_docs
```

Of course it would be great if something like this would be supported out-of-the-box.

**Comment by tf-tony** [comment]
You sir, are a scholar and a gentleman.  I appreciate the solution.
