### ISSUE TITLE
Content Security Policy for UI middleware

### ISSUE THREAD

**Issue by eric-hemasystems** [rswag/rswag#174]
I am getting a problem where the UI is blank once I enable the CSP that is part of Rails 5.2. The reason is that the inline script tags which load the UI are blocked since I don't have `unsafe-inline` in my `script-src`.

Rails has the ability to let a controller override the CSP for a certain context but since the UI is served via middleware we don't have that option to override. I can add `unsafe-inline` to my global CSP and the problem is fixed but then my entire app allows inline scripts. :(

When looking at the Rails CSP module I noticed that [if the page already has a CSP header it won't add the global config](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/content_security_policy.rb#L21). I'm thinking this is the answer. Figure out what CSP header is appropriate for Swagger UI and have the RSwag middleware include that header.

I can do the leg work on making a PR for this but wanted to confirm this is the desired strategy and something you consider in-scope for this project.

**Comment by eric-hemasystems** [comment]
Didn't get any feedback on this so don't want to create a PR unless I think it will be accepted. But if anybody else hits this issue and doesn't want to open up their entire app for the API docs you can use this monkey-patch to delivery a wider CSP just for Rswag:

```ruby
module Rswag::Ui::CSP
  def call env
    _, headers, _ = response = super
    headers['Content-Security-Policy'] = <<~POLICY.gsub "\n", ' '
      default-src 'self';
      img-src 'self' data: https://online.swagger.io;
      font-src 'self' https://fonts.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
    POLICY
    response
  end
end

Rswag::Ui::Middleware.prepend Rswag::Ui::CSP
```

Place this in your `lib` directory and require it at the bottom of your `application.rb` file.

**Comment by sherllochen** [comment]
> Didn't get any feedback on this so don't want to create a PR unless I think it will be accepted. But if anybody else hits this issue and doesn't want to open up their entire app for the API docs you can use this monkey-patch to delivery a wider CSP just for Rswag:
> 
> ```ruby
> module Rswag::Ui::CSP
>   def call env
>     _, headers, _ = response = super
>     headers['Content-Security-Policy'] = <<~POLICY.gsub "\n", ' '
>       default-src 'self';
>       img-src 'self' data: https://online.swagger.io;
>       font-src 'self' https://fonts.gstatic.com;
>       style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
>       script-src 'self' 'unsafe-inline' 'unsafe-eval';
>     POLICY
>     response
>   end
> end
> 
> Rswag::Ui::Middleware.prepend Rswag::Ui::CSP
> ```
> 
> Place this in your `lib` directory and require it at the bottom of your `application.rb` file.

It works great for me.

**Comment by BookOfGreg** [comment]
Ah, Thanks for bringing this to my attention, yes CSP is something that should work for the middleware.
Lets see about getting something tested and merged as CSP is an important security feature to many.

**Comment by BookOfGreg** [comment]
Not stale.

**Comment by slayer** [comment]
any news?

**Comment by dwthien** [comment]
Hi, I have same this error.

**Comment by jtannas** [comment]
Oof... This just showed up in my inbox... Sorry it's been sitting here for so long :bow: 
I'm currently focused on getting through the backlog of unmerged PRs and then I'll swing back around to this starting with https://github.com/rswag/rswag/issues/174#issuecomment-557868338 as the solution. If something is needed more urgently then I'd welcome a PR for it so that it gets caught while I work through those.

**Comment by eric-hemasystems** [comment]
Just FYI. I had created a PR for this at https://github.com/rswag/rswag/pull/263. It's probably old by now and looks to have gotten auto-closed so it may need updating but might be a starting place.

**Comment by jtannas** [comment]
Thanks for pointing that out - I've reopened it. With a merge from the latest `master` and a CHANGELOG entry it looks like it'll be ready to merge :)

**Comment by keniiig21** [comment]
@jtannas img-src in scp should have https://validator.swagger.io too:

```
def csp
   <<~POLICY.gsub "\n", ' '
     default-src 'self';
     img-src 'self' data: https://validator.swagger.io;
     font-src 'self' https://fonts.gstatic.com;
     style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
     script-src 'self' 'unsafe-inline';
   POLICY
end
```
Without this option there is a problem with loading indicator of validation https://validator.swagger.io/validator?url=https........

**Comment by erimicel** [comment]
How can we implement the recent change to enable calling different endpoints from Swagger? Specifically, how can we add additional hosts to the default-src to facilitate this?

Especially if we aim to accommodate multiple server end-points for OpenApi 3.0
https://swagger.io/docs/specification/api-host-and-base-path/
