### ISSUE TITLE
Is it possible to document a 500 error response in swagger?

### ISSUE THREAD

**Issue by arianf** [rswag/rswag#178]
Is it possible to document a 500 error response in swagger?

I want my swagger docs to show what JSON structure will be passed when a 500 or other error occurs, but I'm unable to trigger the error in the Rspec test. Is it possible to have swagger document a method without running `run_test!` within that block?

for example, I may have this defined
```ruby
response '500', 'internal server error' do
  schema type: :object,
         properties: {
           message: { type: :string }
         }

  run_test!
end
```

when I run Rspec, I get an failure, if I knew how to trigger a 500, I would fix it. But that doesn't mean my API might never respond with such a response...

```
     Rswag::Specs::UnexpectedResponse:
       Expected response code '200' to match '500'
```

But when I generate docs... it works fine.
```bash
rake rswag:specs:swaggerize
```

<img width="459" alt="screen shot 2018-12-27 at 11 00 30 pm" src="https://user-images.githubusercontent.com/7397857/50506021-89021f80-0a2b-11e9-897f-d7887be40cf1.png">

Now my question is, is there a way to make Rspec ignore actually trying to test a spec for rswag?

like `xresponse` instead of `response`, or is there a way to remove `run_test!` while having rake swaggerize still look at those blocks? Maybe a `run_test` (without the !) to signify the test isn't passing, but you still want it to be included in the swagger docs?

This could apply to any error code that you might not be able to trigger, but you know if it does happen, this would be the response. How do you document that in rswag?

**Comment by ToniTornado** [comment]
Same problem here. I made my tests pass by manually triggering a `500` response if a certain condition is met. I'm authorizing every request with a token; in my tests I set this token to "500" (otherwise an invalid token) and check for that in the beginning of my authorize `before_action`.

my_spec.rb:
```ruby
response '500', 'internal server error' do
  let('X-API-TOKEN') { '500' }
  run_test!
end
```
base_controller.rb:
```ruby
def authorize
  api_token = request.headers['X-API-TOKEN']
  if api_token == '500'
    head 500
    return
  end
  # Check token here...
end
```

I like your `xresponse` solution to document status that I'm unable to trigger.

**Comment by rheasunshine** [comment]
Was there ever a solution for this?

**Comment by rheasunshine** [comment]
I put a new method in my swagger_helper.rb and call it instead of run_test! to accomplish this.

```
def document_response_without_test!
  before do |example|
    submit_request(example.metadata)
  end

  it 'adds documentation without testing the response' do |example|
    # Only check that the response is present
    expect(example.metadata[:response]).to be_present
  end
end
```

e.g.
```
response '500', 'internal server error' do
  schema type: :object,
         properties: {
           message: { type: :string }
         }

  document_response_without_test!
end
```

**Comment by jtannas** [comment]
heyo - new volunteer here sorting through the issue backlog.
I found a similar solution in another comment that's a bit cleaner, so I'm going to add that to the FAQ https://github.com/rswag/rswag/issues/140#issuecomment-449047723

Thanks for the ideas though :)
