### ISSUE TITLE
load javascript in swagger ui

### ISSUE THREAD

**Issue by ConorSheehan1** [rswag/rswag#179]
I want to customize the UI with jQuery. My goal is to add a link to generate an api token, and check if the token is valid when the authenticate button is clicked. I did the following:

```
bundle exec rails g rswag:ui:custom
# generated app/views/rswag/ui/home/index.html.erb
```

I'm getting the following error when I add any jQuery to the generated file
```
Uncaught ReferenceError: $ is not defined
    at index.html:104
```

jQuery is available in my regular views, and required in app/assets/application.js
```
//= require jquery
//= require jquery_ujs
```

What else do I need to do to add jQuery to the generated erb file?

**Comment by jtannas** [comment]
heyo - sorry it took a 3 years to get a response on this

I believe this is resolved by https://github.com/rswag/rswag#customizing-the-swagger-ui

Closing this issue due to it being old/resolved, but feel free to open another if you still have issues.
