### ISSUE TITLE
It's planned pass to Swagger OpenAPI Specification 3.0.x?

### ISSUE THREAD

**Issue by Gmarn** [rswag/rswag#183]
Hi,
I post this request because in some of my project I start using this gem and the result is great, thank so much for the work.
However, with the evolution of the projects, I started to need functionality of JSON scheme as `oneOf` and other. The issue is there are not include in swagger 2.x but only in Swagger 3.0.x.
Or maybe you have some tips to allow me using `oneOf` for json schema validation?

**Comment by displague** [comment]
Duplicate of https://github.com/domaindrivendev/rswag/issues/104

**Comment by BookOfGreg** [comment]
Closing as it's a duplicate.
Yes we are looking to upgrade eventually.
