### ISSUE TITLE
Setting headers when serving the swagger file in rswag-api

### ISSUE THREAD

**Issue by pjdavis** [rswag/rswag#186]
We have a partner that requires the 'Content-Type' response header specify the charset (eg: "Content-Type: application/json; charset=UTF-8". 

It looks like this is hardcoded into the response from the rswag-api rack app.

**Comment by pjdavis** [comment]
#187 Is a fix for this.

**Comment by BookOfGreg** [comment]
Been a while but thanks again for contributing that PR. Many people have benefited from your kindness there.
