### ISSUE TITLE
Parameter names matching rspec built-in matchers are always required

### ISSUE THREAD

**Issue by jaydorsey** [rswag/rswag#188]
Given a parameter defined like this:

    parameter name: :include, in: :query, type: :string, required: false

When running my specs, I get the following error:

```
URI::InvalidURIError:
bad URI(is not URI?): 
http://www.example.com:80/users/f86316df-6892-439f-af9e-ba15ba731c21?include=#<RSpec::Matchers::BuiltIn::Include:0x00007fd507afeb80>
```

Even though required is set to false, it still expects a value. It appears there is a conflict with the RSpec `include` matcher & the parameter name being `include`. 

I can overcome this error two ways:

- By defining `let(:include) {''}` in my `response` block (this is what I'm doing)
- Changing my parameter name (can't do this, because we're using jsonapi)

**Comment by jaydorsey** [comment]
For reference, the issue arises from [this line](https://github.com/domaindrivendev/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L71)

Since this is an issue for me I'll try and craft a PR for this rather than using my workaround

**Comment by jaydorsey** [comment]
After some more digging, it's actually [this line](https://github.com/domaindrivendev/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L36)

```
        (operation_params + path_item_params + security_params)
          .map { |p| p['$ref'] ? resolve_parameter(p['$ref'], swagger_doc) : p }
          .uniq { |p| p[:name] }
          .reject { |p| p[:required] == false && !example.respond_to?(p[:name]) }
```

In this case, it's because `example.respond_to?(p[:name])` always resolves to `true`, because `example.send(:include)` returns an instance of `RSpec::Matchers::BuiltIn::Include`.

I'll prepare a PR for this (along with a test). I've got it working locally but there's a few edge cases that I could probably use a 2nd set of eyes on (re: swagger docs)

**Comment by pernambucano** [comment]
If you have a test where you find yourself using include from both rswag and rspec, you should use the full path to rspec's include:
`expect(response).to RSpec::Matchers::BuiltIn::Include.new(something)` 

and give rswag's include an empty string:

`let(:'include') { '' }`

I don't know if it's important, but this is how I define my include param:

`parameter name: 'include', in: :query, required: false, type: :string`

**Comment by jaydorsey** [comment]
I'm going to close this issue. @pernambucano I think the solution you posted is the only clear way to make this work given how RSpec appears to handle `let` declarations. Thanks!
