### ISSUE TITLE
No ability to generate swagger.json during deploy

### ISSUE THREAD

**Issue by heaven** [rswag/rswag#193]
We have separate hosts in different environments and need to generate the docs during the deploy. Unfortunately, this preloads our entire test suite, unable to find some gems that are installed only in test env and finally tries to set up the test DB.

For example in swagger root we have `host: Settings.host('api')`.

**Comment by Petercopter** [comment]
Check `config/rswag-api.rb`, this worked for me
```
  # Inject a lamda function to alter the returned Swagger prior to serialization
  # The function will have access to the rack env for the current request
  # For example, you could leverage this to dynamically assign the "host" property
  #
  #c.swagger_filter = lambda { |swagger, env| swagger['host'] = env['HTTP_HOST'] }
````

**Comment by fabn** [comment]
> this preloads our entire test suite, unable to find some gems that are installed only in test env and finally tries to set up the test DB.

Did you solve this issue?

**Comment by heaven** [comment]
> > this preloads our entire test suite, unable to find some gems that are installed only in test env and finally tries to set up the test DB.
> 
> Did you solve this issue?

Nope, generating the docs locally and pushing them to git.

**Comment by fabn** [comment]
That's a pity. It defeats advantages of automatic generation. If one forgets to generate up to date documentation it will go online with wrong format.

**Comment by BookOfGreg** [comment]
If you have a standard 2 stage deployment pipeline of Build and Deploy, you can generate your docs in the build phase as they should be considered a build artifact anyway.

**Comment by BookOfGreg** [comment]
I'm going to close this as there's not really much way around loading the tests to generate docs as this gem does use rspec to generate docs. The best answer is to commit in the latest swagger docs.
