### ISSUE TITLE
Compatibility with new version of bundler

### ISSUE THREAD

**Issue by jaydorsey** [rswag/rswag#194]
After cloning the repo, and attempting to run `bundle install` with version `1.17.3` I get the error message `NoMethodError: undefined method `spec' for nil:NilClass`. It appears to be related to [this issue](https://github.com/bundler/bundler/pull/3559) which was fixed in bundler.

I'm able to get past this by using `gem install bundler -v 1.16.6` (I found this version from the travis logs) and installing via `bundle _1.16.6_`

This is pretty low priority, since 1.16.6 isn't super old (2 months older than 1.17.3) but noted in case anyone else is looking to contribute, but runs into issues with getting everything configured (and has 1.17.3 installed)

**Comment by BookOfGreg** [comment]
Thanks for your report.
Unfortunately I was unable to replicate this issue:
```
$ gem install bundler -v '< 2'
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 2 seconds
1 gem installed

$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
...
```
If you can still replicate this please let us know. For now I will close.

**Comment by jaydorsey** [comment]
I just tested and this seems to be resolved. Thanks for following up on this!

I'm unable to recreate it at the previous commit where I _thought_ it occurred so it may have been resolved by a `gem update --system` or something else. It was a combo of a bundler bug + something missing in one of the gemspec files IIRC (something that seems to be handled better, because I've seen it in other, older, gems before as well)

Side note: `bundle install` would have run your default bundle version, which may not be the 1.17.3 version you just installed. To try to replicate it you would need to run `bundle _1.17.3_ install` but I ran that locally, even with an older commit and it works fine now.

**Comment by BookOfGreg** [comment]
Thank you for confirming that it seems fine now.
Your concern about my bundler version is valid but I had just installed ruby 2.6.4 so it was fresh with no other bundlers that could have interfered in this case. I'll remember the trick for using a specific version in the future.
