### ISSUE TITLE
The README isn't clear regarding collections

### ISSUE THREAD

**Issue by heaven** [rswag/rswag#195]
There are no examples regarding the APIs that return collections. I have `Profile` class and an `index` endpoint in the API that returns a list of profiles. I have a definition for the `Profile` model but there are no examples of how to map this.

**Comment by heaven** [comment]
I figured out I can do the following:
```ruby
response '200', 'Ok' do
  schema type:  :array,
    items: { '$ref' => '#/definitions/profile_search' }
```

But would be great to reflect this in the README.

**Comment by domaindrivendev** [comment]
In the spirit of open source - why not submit a PR to update the docs?

**Comment by heaven** [comment]
Sure, will do, I just did this at random and wasn't sure this is the correct way.

**Comment by jtannas** [comment]
Added to the new `Examples` section of the wiki https://github.com/rswag/rswag/wiki/Examples#documenting-a-response-that-is-an-array-of-objects
