### ISSUE TITLE
Discrepancy in parameter names

### ISSUE THREAD

**Issue by heaven** [rswag/rswag#196]
I see a discrepancy between parameter names I specified in specs and what I get in the request.

We have the following routes:

```ruby
resources :profiles, only: %i[show] do
  collection do
    resources :searches, controller: :profile_searches, only: %i[index show create update]
  end
end
```

And this spec:

```ruby
path '/profiles/searches/{id}' do
  get 'Retrieves search results' do
    tags 'Searches'
    security [apiKey: []]
    parameter name: :id, in: :path, type: :string

    parameter name: :search, in: :body, schema: {
      '$ref' => '#/definitions/search'
    }

    let(:search) { {} }

    response '200', 'Ok', focus: true do
      schema type: :array, items: { '$ref' => '#/definitions/profile' }

      run_test!
    end
  end
end
```

I expected to have `params[:search]` on the server but get `params[:profile_search]`, I have no idea where it came from.

**Comment by heaven** [comment]
On the API docs page it shows `search`, not `profile_search`, which confuses front-end developers:
<img width="599" alt="screen shot 2019-02-16 at 21 21 44" src="https://user-images.githubusercontent.com/126732/52904175-00d11700-3231-11e9-8e85-80d97d736b35.png">

**Comment by jaydorsey** [comment]
What's your search definition look like in your request schema?

**Comment by heaven** [comment]
The definition looks like this:

```ruby
search: {
  type:       :object,
  properties: {
    page:     { type: :integer },
    per_page: { type: :integer }
  }
}
```

**Comment by jaydorsey** [comment]
> I expected to have `params[:search]` on the server

Where do you mean? In the controller? Everything you posted (barring knowing what's in the controller) looks to me like you'd send a send & receive a response with a `search` key.

The only other thing I could think this might be is in your controller, if you can post that as well that would be useful.

You could try inspecting the request with something like:

```
run_test! do |example|
  puts example.request.body.read # views the body
end
```

I might be misunderstanding the question but if you can provide a little more info I'd be happy to try and help. I've had pretty good luck setting up rswag across our app, including some some non-standard and slightly more complex examples.

**Comment by daan-b** [comment]
Maybe a little late. The problem you describe isn't related to Rswag. 
You created a nested route. Rails creates default a extra parameter with the Controller name.

More info at https://api.rubyonrails.org/v5.2.2/classes/ActionController/ParamsWrapper.html

**Comment by jtannas** [comment]
Heyo - new volunteer here sorting through the issue backlog and came across this.
It looks like a solution was provided and the original posted never followed up so I'm going to close this now, but if you're running into problems feel free to open a new issue and I'll be happy to help :slightly_smiling_face: 
Cheers!
