### ISSUE TITLE
Not specifying consumers/producers resolve in null on swagger definition

### ISSUE THREAD

**Issue by gottfrois** [rswag/rswag#2]
Hey there,

I moved the `consumers`, `producers` mime definitions in the gem configuration hook, for them to be at the top level of the swagger definition but this creates the following output for my path:

``` json
consumers: null,
producers: null,
```

Whereas it should be empty array right?

**Comment by dan-ding** [comment]
I'd think so. Another solution may be if the value is null, to not generate the attribute at all; 
Similarly with other attribute values. null isn't available in swagger (yet?)

**Comment by drewish** [comment]
Yeha, my preference is also to add the consumes produces at the top level:

``` rb
  config.swagger_docs = {
    'v1/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'API V1',
        version: 'v1'
      },
      consumes: ['application/json'],
      produces: ['application/json']
    }
  }
```

https://github.com/domaindrivendev/swagger_rails/pull/18 has a fix for this and the null descriptions.

**Comment by drewish** [comment]
In my gem I use the operation level consumes/produces values and if that's not present fall back to the document level values: https://github.com/drewish/rspec-rails-swagger/blob/master/lib/rspec/rails/swagger/request_builder.rb#L22-L28

**Comment by domaindrivendev** [comment]
Check out the latest version 1.0.0 as it has a fix for this and lots of other great features added. **NOTE**: the name change from swagger_rails to rswag. Also worth noting there's a minor breaking change - the "parameter" method in the rspec DSL now expects a single argument (attributes) that includes "name" instead of two arguments (name, attributes).
