### ISSUE TITLE
Rake Task: rswag:specs:swaggerize not available

### ISSUE THREAD

**Issue by nicwillemse** [rswag/rswag#200]
For some reason im not able to execute the swaggerize rake task, I have tried to reinstall this did not work

Environment Details :
```
Using rswag-api 2.0.5
Using rswag-specs 2.0.5
Using rswag-ui 2.0.5
```
Error: 

```
$ bundle exec rake rswag:specs:swaggerize
rake aborted!
Don't know how to build task 'rswag:specs:swaggerize' (See the list of available tasks with `rake --tasks`)
/Users/nic/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/nic/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by Petercopter** [comment]
@nicwillemse Same problem here. I see it in the list of tasks, but I'm unable to run it... did you resolve?

**Comment by nicwillemse** [comment]
hey @Petercopter , I ended up redoing the configuration and reinstalling which fixed the issue. 

So unfortunately I did not get to pin point the actual problem.

**Comment by Petercopter** [comment]
@nicwillemse Thanks for the response! I figured you closed the issue because it was something you were able to resolve by messing with it. I will do the same.

**Comment by ealvaro** [comment]
@nicwillemse and @Petercopter
You gotta execute the rake within the `test` environment as below:
`rails rswag:specs:swaggerize RAILS_ENV=test `
if you avoided loading rspec in other bundler groups like development or production.
