### ISSUE TITLE
feature request: enum description

### ISSUE THREAD

**Issue by ConorSheehan1** [rswag/rswag#201]
It'd be great if we could add a description to each enum value by passing a hash instead of an array to the enum param.

Something like this: https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-173336234

```ruby
# requested support
parameter name: :foo, in: :query, enum: {'bar': 'lists bars', 'baz': 'lists people named baz'}

# current support
parameter name: :foo, in: :query, enum: ['bar', 'baz']
```

**Comment by TheHussein** [comment]
any updates on this?
