### ISSUE TITLE
Missing root element

### ISSUE THREAD

**Issue by daan-b** [rswag/rswag#208]
From the examples with JSON as produces and consumes, I expect an blog root element in my json. As Rails also excepts params.require(:blog).permit(:title, :content)

`parameter name: :blog, in: :body, schema: {
  type: :object,
  properties: {
    title: { type: :string },
    content: { type: :string }
  },
  required: [ 'title', 'content' ]
}`
`response '201', 'blog created' do
    let(:blog) { { title: 'foo', content: 'bar' } }
    run_test!
end`

It will be posted to my Rails application as:

`{
  "title" => "foo",
  "content" => "bar"
}`

As I name my parameter blog, I expect the following structure:

`{
  "blog" => {
    "title" => "foo",
    "content" => "bar"
  }
}`

**Comment by mdmccoy** [comment]
Rails will automatically wrap your parameters in a root JSON element if you tell it to: https://api.rubyonrails.org/v5.2.3/classes/ActionController/ParamsWrapper.html

This may help with the missing root element in the tests.

**Comment by jaydorsey** [comment]
You haven't defined the root level element in either your `parameter` definition (for your documentation), or your spec. You'll need to define it in both places for the documentation to generate correctly & the spec to pass (in addition to your strong params in your rails code)

```
# I'm guessing on this, I don't use nested syntax hand-written like this
parameter name: :blog, in: :body, schema: { 
  properties: {
    blog: { 
      type: :object, 
      properties: { 
        title: { type: :string }, 
        content: { type: :string } 
      }, 
      required: [ 'title', 'content' ] 
    }
  }
}

response '201', 'blog created' do 
    let(:blog) { { blog: { title: 'foo', content: 'bar' } } }
   
    run_test! 
end
```

**Comment by jtannas** [comment]
Looks like this question has been answered to I'm going to close it now.
If you're still running into problems then feel free to make a new issue and I'll be happy to help :slightly_smiling_face: 
Cheers!
