### ISSUE TITLE
Support for custom properties

### ISSUE THREAD

**Issue by bubbavcita** [rswag/rswag#212]
Howdy,

Is there support for custom properties? I am specifically looking for a way to add the Amazon API Gateway custom properties such as: 'x-amazon-apigateway-integration' to my Swagger JSON.

Thanks!

**Comment by jtannas** [comment]
Hi @bubbavcita - I'm a new volunteer working my way through the issue backlog. Sorry it took so long to get a response.

I don't know if this is a new addition, but you're able to add properties within the header. Eg.
```ruby
      'Key-Inflection': {
        name: 'Key-Inflection',
        in: :header,
        schema: {
          type: :string,
          enum: %w[snake camel dash pascal],
        },
        required: false,
        default: 'camel',
      },
```

Does this fit what you're looking for?

**Comment by jtannas** [comment]
Added to an examples section https://github.com/rswag/rswag/wiki/Examples#documenting-a-header-parameter
