### ISSUE TITLE
rswag:specs:swaggerize not found

### ISSUE THREAD

**Issue by victorhazbun** [rswag/rswag#215]
The command `rake rswag:specs:swaggerize` is not available with using the following configuration from the README:

```ruby
# Gemfile
gem 'rswag-api'
gem 'rswag-ui'

group :test do
  gem 'rspec-rails'
  gem 'rswag-specs'
end
```

It only works when using:

```ruby
gem 'rswag'
```

**Comment by joshling1919** [comment]
This might be because `rswag:specs` is only inside of your test group.
try `RAILS_ENV=test rake rswag:specs:swaggerize`
