### ISSUE TITLE
Enums can't be nullable

### ISSUE THREAD

**Issue by marcelotto** [rswag/rswag#221]
The property `x-nullable` to allow `nil` values doesn't work for enums. 

I've noticed that Dredd has the same issue, maybe some of their investigations are relevant here too: https://github.com/apiaryio/dredd/issues/507

**Comment by and0x000** [comment]
stumbled upon this as well, you need to add both, `x-nullable` to the property and `null` as a value to your enum for it to work. Might be nice, if it would be possible to add the `null` value to the enum array implicitly, if `x-nullable: true` is defined.

**Comment by jtannas** [comment]
heyo - new volunteer clearing out our issues backlog. 
I've added this to our Examples section of the wiki. https://github.com/rswag/rswag/wiki/Examples#documenting-a-nullable-enum-parameter
I'm going to close this now, but feel free to open another issue if you're still running into problems. Cheers! :slightly_smiling_face:
