### ISSUE TITLE
Support OPTIONS verb

### ISSUE THREAD

**Issue by anjumjfax** [rswag/rswag#231]
Having a peek into the code, I see the verbs `[ :get, :post, :patch, :put, :delete, :head ]` are supported, but no [OPTIONS](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html). I think it would be good to be able to write calls that respond to the options verb.

This isn't as esoteric of a feature request as it may appear, I think. I discovered a potential opportunity to make use of it recently while working on a moderately complex web service method for querying records, where it would benefit from a counterpart OPTIONS verb call to retrieve a (albeit, mostly static) list of query keys. I guess I could do this as a separate GET call, but you know, being able to cease an available rfc to do the job would be nice.

**Comment by BookOfGreg** [comment]
https://swagger.io/specification/#fixed-fields-7
OpenAPI themselves seem to support the following and so should we:

Field Name | Type | Description
-- | -- | --
get | Operation Object | A definition of a GET operation on this path.
put | Operation Object | A definition of a PUT operation on this path.
post | Operation Object | A definition of a POST operation on this path.
delete | Operation Object | A definition of a DELETE operation on this path.
options | Operation Object | A definition of a OPTIONS operation on this path.
head | Operation Object | A definition of a HEAD operation on this path.
patch | Operation Object | A definition of a PATCH operation on this path.
trace | Operation Object | A definition of a TRACE operation on this path.

**Comment by BookOfGreg** [comment]
@anjum-ahmed how are you routing `:options` verbs in Rails? I didn't think it came out of the box.
An example app would be useful here to test against, and we may need something of a guide to explain how options works if it's not standard Rails.

**Comment by anjumjfax** [comment]
@BookOfGreg Thank you! Funny to learn that options wasn't even available in Rails.

**Comment by BookOfGreg** [comment]
No problem 😄 
Technically it still isn't until they deploy it. Also this gem will not correctly swaggerize Trace or Options verbs unless a Rails patch is made by the user. I'm still considering how best to describe that to end users.
