### ISSUE TITLE
Run spec, but skip docs

### ISSUE THREAD

**Issue by brateq** [rswag/rswag#244]
Hi, 
I would like to use rswag to test some edge cases, but without generating results into documentation. 
Should I write these tests in separate places, or is there some flag to skip documentation for some specs?
Thanks!

**Comment by BookOfGreg** [comment]
If you have your tests in the spec directory, they will run when you run rspec with your other tests. Docs are only generated when you run the swaggerize rake task.

If this is not the case then let me know but I believe it should already do what you want.

**Comment by brateq** [comment]
What I need is to still be able to generate documentation for most cases in my integration tests. 
In rspec_api_documentation there is a `document: false` flag for this. Is there something like this in rswag?
I will give you an example:

```
path '/v1/test' do
  get 'Get all objects' do
    response '200', 'Get objects' do
      # here I want a normal case with nice looking response for documentation
    end

    response '200', 'Get differen set of object to test edge case' do
      # and this response I would like to test, but not include in document
    end
  end
end
```

**Comment by BookOfGreg** [comment]
Ah I understand, you want to write extra tests that are not generated in your document.

I don't believe that currently exists.
It could be simulated by changing the file glob that swaggerize uses to generate documentation and putting all examples you don't want to output in other files but it's not a good solution.

I'd consider a PR for it if you have an idea of how you might implement it.

**Comment by BookOfGreg** [comment]
A workaround in the meantime would be to add the following to your response block:
```
        after do |example|
          example.metadata[:response] = nil
        end
```
This causes [`Rswag::Specs::SwaggerFormatter.example_group_finished`](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L20) to skip over it.

**Comment by karljohansson85** [comment]
I've uploaded a pull request where you can specify document: false #255 

Let me know if it needs tweaking. Thanks for a nice swagger gem!

**Comment by amuntasim** [comment]
Instead of using `response` block, I'm using this:


```
    before do |example|
       submit_request(example.metadata)
    end
        
    it "returns something" do |example|
      data = JSON.parse(response.body)
      #expectations
    end
```

**Comment by biglovisa** [comment]
@amuntasim are you using that ^ strategy because `document: false` didn't work for you? I am debugging an issue with where it is generating documentation even with the `document: false` metadata present and am curious about what you're seeing.

**Comment by brateq** [comment]
`document: false` from fooki works great, thanks!
