### ISSUE TITLE
Load error: swagger_generator.rb

### ISSUE THREAD

**Issue by ryan-plated** [rswag/rswag#248]
I get the error `require': cannot load such file -- generators/rspec/swagger/swagger_generator.rb (LoadError)` when trying to run console or anything.

Looks like `generators/rspec/swagger/swagger_generator.rb` doesn't exist but `generators/rspec/swagger_generator.rb` does

**Comment by LolWalid** [comment]
Having the same issue with rails 5.1.4 and 6.0.0

Version of rswag gems:

```
rswag-api (2.1.0)
rswag-specs (2.1.0)
rswag-ui (2.1.0)
```

**Comment by BookOfGreg** [comment]
Can you give more information? I can run console just fine on Rails 5.1.4, rswag-api,ui,specs 2.1.0.

Edit: I'm correcting that anyway as it's clearly pointing in the wrong place, but if you're able to do so I'd still like to know how to reproduce it so I can learn to avoid this mistake again.

**Comment by BookOfGreg** [comment]
Should be fixed in [2.1.1](https://travis-ci.org/rswag/rswag/builds/599878948)
Please let me know what the reproduction was and let me know if it works for you. Thanks.
