### ISSUE TITLE
How to create proper :array parameters

### ISSUE THREAD

**Issue by Kutomore** [rswag/rswag#256]
One of the most common standards for sending an array in a hash is something along the lines of:

`array[]=value_1&array[]=value2`

If you get that in rails, and call params[:array] you can check that it is indeed an proper array. But how could I set up the parameters in a schema in a way to reflect this syntax.

I need to send an array of channel_ids, I have tought of something along the lines of:
```
parameter name: :channel_ids, in: :query,  type:  :array,  description: 'filter by channel ids', required: false, items: {
    type: :string,
    example: "ebfec9ec-ba72-4b24-95b8-68aebe5f0024"
  }
```

But it sent the data as `channel_ids=value`, instead of `channel_ids[]=value`.

Then the idea came to use:

```
parameter name: "channel_ids[]", in: :query,  type:  :array,  description: 'filter by channel ids', required: false, items: {
        type: :string,
        example: "ebfec9ec-ba72-4b24-95b8-68aebe5f0024"
      }
```
Which does send `channel_ids[]=value`, but I'm still unable to send multiple values, like `channel_ids[]=value1&channel_ids[]=value2`.

Is there an way to properly do it?

**Comment by vladflorescu** [comment]
Check https://github.com/rswag/rswag/issues/99. Looks like `collectionFormat: :multi` does the magic.

I found out from the  source code but looks like it's actually documented [here](https://swagger.io/docs/specification/2-0/describing-parameters/).

**Comment by Kutomore** [comment]
Thanks man, really helpfull @vladflorescu94

**Comment by jackchi** [comment]
This doesn't actually pass the OpenAPI V3 standards. Running [OpenAPIV3 parser](https://github.com/kevindew/openapi3_parser) we do get an error of `Unexpected fields: collectionFormat`. It looks like this is the [default OpenAPI V3 serialization method](https://swagger.io/docs/specification/serialization/). But I cannot figure out how to set my `lets!(...)` so that it matches the parameter set up. 

```ruby
parameter({
        name: 'kind[]',
        in: :query,
        required: false,
        schema: {
          type: :array,
          items: {
            type: :string,
            enum: [
              'file',
              'photo',
              'video',
            ],
            nullable: true,
            description: 'Kind of Attachment'
          }
        }
      })

...
let!(:'kind[]') { ['file', 'video'] }
```

**Comment by jtannas** [comment]
Added to the documentation here: https://github.com/rswag/rswag/wiki/FAQ#how-can-i-submit-arrays-through-query-parameters

**Comment by ShPakvel** [comment]
@jtannas documented example that you mentioned doesn't work (OpenAPI 3). It build wrong params from provided let like `let('widget') { %w[foo bar] }`. 

I've updated documentation with the only correct way to define query array parameter for OpenAPI 3. https://github.com/rswag/rswag/wiki/FAQ#for-openapi-3

**Comment by jtannas** [comment]
Thanks @ShPakvel 
I'm a bit puzzled since it seems to be working for me though :thinking: 
What do you mean by "build wrong params from provided let"?

**Comment by artur79** [comment]
@ShPakvel it works good from swagger api panel, it's passed like
```
parameters: {"filter"=>{"datetime_range"=>["2023-02-25T21:05:00Z", "2023-02-25T21:16:00Z"]}}
```

but when I try to spec it like
```
parameter name: 'filter[datetime_range][]', in: :query, style: :form, explode: true, description: 'Datetime in ISO 8601 format',
        schema: {
          type: :array,
          items: { type: :string, example: '2023-02-25T21:00:00Z' }
        }

let(:'filter[datetime_range][]') { [range_starts_at, range_ends_at] }
```
I'v got it passed like 

```[["2023-02-23T00:00:00Z,2023-02-25T22:00:00Z"]]```

so different form than passed from swagger api. Am I missing sth ?

**Comment by ShPakvel** [comment]
@artur79 I've tested nested parameter locally (your example and extended examples). Everything passed in my case. So my guess, issue is in different place. Check version of the OpenAPi is 3 (properly configured), check version of the gem.

**Comment by jeff-free** [comment]
> [@ShPakvel](https://github.com/ShPakvel) it works good from swagger api panel, it's passed like
> 
> ```
> parameters: {"filter"=>{"datetime_range"=>["2023-02-25T21:05:00Z", "2023-02-25T21:16:00Z"]}}
> ```
> 
> but when I try to spec it like
> 
> ```
> parameter name: 'filter[datetime_range][]', in: :query, style: :form, explode: true, description: 'Datetime in ISO 8601 format',
>         schema: {
>           type: :array,
>           items: { type: :string, example: '2023-02-25T21:00:00Z' }
>         }
> 
> let(:'filter[datetime_range][]') { [range_starts_at, range_ends_at] }
> ```
> 
> I'v got it passed like
> 
> `[["2023-02-23T00:00:00Z,2023-02-25T22:00:00Z"]]`
> 
> so different form than passed from swagger api. Am I missing sth ?

I got similar result. With parameter defined like this:
```
parameter name: 'vendor_sku_ids[]', in: :query, style: :form, explode: true, type: :array,
        items: { type: :integer }

let('vendor_sku_ids[]') { [1, 2] }
```

Parameter received in controller action is `"vendor_sku_ids"=>["1,2"],`, which combines all the element into one element. The `request.url` is `&vendor_sku_ids[]=1,2"`

`parameter name: 'vendor_sku_ids[]', in: :query, type: :array, collectionFormat: :multi, items: { type: :integer }` does the trick, though. Produced url: `&vendor_sku_ids[]=1&vendor_sku_ids[]=2"`
