### ISSUE TITLE
'Try it out' example does not use the body params

### ISSUE THREAD

**Issue by jmdfm** [rswag/rswag#257]
Swaggerizing and running the specs are all fine. But when I go to the Swagger UI, click into the example and click Try it out, hitting execute does not use the body params that have been specified:

![image](https://user-images.githubusercontent.com/237175/69385210-76ac5800-0c73-11ea-9816-283a9e7187b7.png)

RSpec:
```ruby
require 'swagger_helper'

describe 'Users API' do
  path '/api/v1/users' do
    post 'Creates a User' do
      tags 'Users'
      consumes 'application/json'
      produces 'application/json'

      parameter name: :user, in: :body, required: true, schema: {
        type: :object,
        properties: {
          user: {
            type: :object,
            properties: {
              email: { type: :string },
              password: { type: :string }
            },
            required: ['email', 'password']
          }
        },
      }

      response '201', 'User created' do
        let(:user) { { user: { email: 'test@test.com', password: 'skylarplease' } } }
        run_test!
      end
    end
  end
end
```

**Comment by idoqo** [comment]
I think this happens because the generated `swagger_helper.rb` file defaults to OpenAPI 3, and that version replaced the body parameter with requestBody (See: https://swagger.io/docs/specification/describing-request-body/) - At least it was what happened in my case.

I replaced
```ruby
 openapi: '3.0.1',
```
with:
```ruby
swagger: '2.0',
```
in my `swagger_helper.rb` and got swagger ui to send the data with the request.

**Comment by toshipon** [comment]
@idoqo It works for me too. thanks!

**Comment by BookOfGreg** [comment]
> I think this happens because the generated swagger_helper.rb file defaults to OpenAPI 3

Yep this was a recent change in prep for me finishing off the OpenAPI 3 changes. Seems I was a bit hasty on that one.

**Comment by x1wins** [comment]
@idoqo thanks you!!. you save me. I did spend time above a weeks for not generate curl and body  parameters....

**Comment by briri** [comment]
thank you @idoqo! Have been struggling with this for 1/2 a day now. rswag should update their generator so that the default `swagger_helper.rb` file does not default to `openapi: '3.0.1'` if they don't fully support it.
