### ISSUE TITLE
Any roadmap to support open api 3.0 ?

### ISSUE THREAD

**Issue by Sbfrr** [rswag/rswag#260]
Hi,

I was wondering if you had any roadmap planned to support changes that occur in version 3.0 of Open API and more specifically in the Authentication description (I'm referring to https://swagger.io/docs/specification/authentication/ ) : 

- SecurityDefinitions were renamed to securitySchemes and moved inside components.
- type: basic was replaced with type: http and scheme: basic.
- The new type: http is an umbrella type for all HTTP security schemes, including Basic, Bearer and other, and the scheme keyword indicates the scheme type.
- API keys can now be sent in: cookie.
- Added support for OpenID Connect Discovery (type: openIdConnect).
- OAuth 2 security schemes can now define multiple flows.
- OAuth 2 flows were renamed to match the OAuth 2 Specification: accessCode is now authorizationCode, and application is now clientCredentials.

Thanks :)

**Comment by BookOfGreg** [comment]
Yes but it Christmas so I'm taking a break.
I'm trying to do it while being vaguely backward compatible within reason.
AKA if you declare swagger 2.0 in your manifest it will still generate that with existing code alongside the new openapi 3.0.0 declarations.

Thanks for the interest in our project :)

**Comment by BookOfGreg** [comment]
This is a dup of our oldest open issue so going to close this specific one but we will be getting this to all in the hopefully not too distant future. If you'd like to contribute I'd LOVE to see it as I'm currently the only active maintainer and any help is greatly appreciated.

**Comment by ramytamer** [comment]
@BookOfGreg I would be glad to help if you want 🙂

**Comment by BookOfGreg** [comment]
OA3 is now supported. Check out the latest release.
Let me know if you encounter any issues.
