### ISSUE TITLE
Should bundle exec rake rswag run rspec tests?

### ISSUE THREAD

**Issue by silasb** [rswag/rswag#264]
I have an application that I'm integrating RSwag in.  Running `bundle exec rake rswag` after doing the Getting Started seems to produce the Swagger file. Should `bundle exec rake rswag` also run the integration tests?

my trivial example:

```
  after do |example|
    p 'here'
    example.metadata[:response] = { 'application/json' => {id: 1, title: 'hello world'} }
  end

  run_test!
```

which doesn't print out anything when calling `bundle exec rake rswag`.  Is this expected?

**Comment by Kutomore** [comment]
In my experience yes, according to the doc `rake rswag`is an alias task to the swaggerize task that generates the swagger.json file. If you want to actually run the tests you can run them like any regular spec(`bundle exec rspec`)

**Comment by silasb** [comment]
Then how does https://github.com/rswag/rswag#enable-generation-examples-from-responses work with `bundle exec rspec spec/integrations/` then?  Should I expect to see the Rspec run which modifies the swagger.yaml?

**Comment by Kutomore** [comment]
I have not used that feature before, but rading it does seem like that's the case, you run the specs with rspec and they generate it based on the responses you get.

**Comment by silasb** [comment]
Maybe I'm missing something, but I have `example.metadata[:response]` assigned and nothing gets updated.

I'll try to reproduce this in a new Rails 6 project to see what's happening.

**Comment by brcebn** [comment]
I have the same questioning. How `rake rswag` can use
```ruby
RSpec.configure do |config|
  config.after do |example|
    example.metadata[:response] = { 'application/json' => JSON.parse(response.body, symbolize_names: true) }
  end
end
```
if specs are not run? 
Currently, examples are nothing more than the value of `schema('$ref' => '#/definitions/YouDef')` on the spec itself. 

What am I missing?

**Comment by BookOfGreg** [comment]
The specs are run? This gem is a wrapper around RSpec Example helpers that makes heavy use of RSpec metadata.
https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L7
During validation those references get expanded into real JSON Schema objects and the response.body is run through the V4 validator.
https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/response_validator.rb#L46
After each example group it reformats the metadata to merge into the swagger_doc:
https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L23
And after all tests finish it dumps it into a file:
https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L51

I'm not sure what it is you're missing but the whole thing doesn't work without RSpec having access to a response, which unless something funky happens should still be there in an after block.

**Comment by jtannas** [comment]
This seems resolved so I'm going to close this issue. Feel free to make another issue if you're still running into problems.
Cheers 🙂
