### ISSUE TITLE
How do you test formData?

### ISSUE THREAD

**Issue by Kutomore** [rswag/rswag#265]
I have the following structure right now:

```
      parameter name: 'product[name]', in: :formData, type: :string,
                required: true, example: 'Tomato'
      parameter name: 'product[description]', in: :formData, type: :string,
                required: true,
                example: 'The tomato is an edible, often red, berry.'
      parameter name: 'product[image]', in: :formData, type: :file
```

It's just the default test as well with `run_test!`, but the issue I have is when I try to run this test it states

`undefined method `product[name]'`

Which seems to me like instead of using my product object and getting the values from inside it, it's actually simply trying to run the full string ad an method. I guess i could just use something like:

`let('product[name]') { 'name' }`

But it doesn't really seem right, is there a proper way to handle this?

**Comment by bitwerx-tyler** [comment]
Parameters must be symbols, not hashes:

```
parameter name: :name, in: :formData, type: :string,
          required: true, example: 'Tomato'
parameter name: :description, in: :formData, type: :string,
          required: true,
          example: 'The tomato is an edible, often red, berry.'
parameter name: :image, in: :formData, type: :file
```

**Comment by Kutomore** [comment]
Well, it shouldn't matter, but I tried with the same approach you suggested but the error was the same. Right now I'm going to try to do let(:name){} and see if I get a different message. But the issue is the same wether I'm using a hash or a symbol.

Nonetheless Rails does expect form data as hashes, so I assume they should be sent as such.

edit:

So as expected params wrapper does not work with formData, so it requires me to use a hash.

**Comment by sobrinho** [comment]
See #300.
