### ISSUE TITLE
OAS3.0 Query param 

### ISSUE THREAD

**Issue by alecslupu** [rswag/rswag#271]
When trying to add a query param based on the OAS 3 specs (https://swagger.io/docs/specification/describing-parameters/ ), using the following syntax, 
`      parameter name: :product, in: :query, schema: { type: :string }`

A NoMethodError error is generated, 

`NoMethodError:
       undefined method `to_sym' for nil:NilClass
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:78:in `build_query_string_part'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:71:in `block (2 levels) in add_path'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:69:in `each'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:69:in `each_with_index'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:69:in `block in add_path'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:64:in `tap'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:64:in `add_path'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:19:in `block in build_request'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:17:in `tap'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/request_factory.rb:17:in `build_request'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/example_helpers.rb:9:in `submit_request'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rswag-specs-2.2.0/lib/rswag/specs/example_group_helpers.rb:87:in `block in run_test!'
     # /Users/alecslupu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'`

The issue seems to reside in the implementation of the following file : 

https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L76

**Comment by helderasmoreira** [comment]
I'm experiencing the same issue I believe.

What would be the correct way to detail the `type` of a `query` param?

**Comment by alecslupu** [comment]
The V2 version still works perfectly.
Also, i had some issues, and moved back to Svagger 2. 

`parameter name: :product, in: :query, type: :string`

**Comment by malkovro** [comment]
Looks like OAS 3.0 is expecting something like:
```

parameter name: :product, in: :query, schema: { type: :string }
```
But rswag expects it to be set directly as type (without wrapping schema):
https://github.com/rswag/rswag/blob/7ceedab4cb7788ab6b86b96bd2d8f2419e11ebbb/rswag-specs/lib/rswag/specs/request_factory.rb#L119-L135

However if you provide it as 
```
parameter name: :product, in: :query, type: :string 
```
Some other part of the code I didn't identify yet (probably related to retro compatibility with specification 2) wraps your type into the OAS3 expected `schema` key.

As a workaround you can provide both and it seems to work for now:
```
parameter name: :product, in: :query, type: :string, schema: { type: :string }
```

**Comment by iainbryson** [comment]
This is unfortunate; I was hoping to use OAS's free-form parameters as in https://stackoverflow.com/questions/49582559/how-to-document-dynamic-query-parameter-names-in-openapi-swagger , which requires setting the schema.

Is it a lot of work to add this?

**Comment by jtannas** [comment]
heyo - new volunteer here sorting through the issue backlog.
Looks like this was resolved by you PR so big thank you on that :bow: 

I've just added an OAS3 query parameter example to our Wiki and will close this issue now. Cheers! :slightly_smiling_face:
