### ISSUE TITLE
Error handling for test, placed outside of 'path' block

### ISSUE THREAD

**Issue by privorotskii** [rswag/rswag#276]
The correct way to write spec is:
```
...
  path '/some_path' do

    get 'Makes some get request' do
      response '200', 'Ok response' do
        run_test!
      end
    end
  end
...
```

But it happens (especially when the specs get big) that you may accidentally get confused with block nesting and leave the spec's body outside of `path` block, like this:

```
...
  path '/some_path' do
    ...
    ...
  end

  get 'Makes some get request' do
    response '200', 'Ok response' do
      run_test!
    end
  end
...
```
And then you get an error, which gives no sense at all, like this:
```
Failure/Error: example.run

NoMethodError:
  undefined method `[]` for nil:NilClass

# /home/user/.rvm/gems/ruby-2.6.3/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:29 in `expand_parameters`
# /home/user/.rvm/gems/ruby-2.6.3/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:15 in `build_request`
# /home/user/.rvm/gems/ruby-2.6.3/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:9 in `submit_request`
# /home/user/.rvm/gems/ruby-2.6.3/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:87 in `block in run_test!`
...
```

The only possibility to find out what caused error - is to debug rswag-specs. It happens due to no checking of `metadata` existing [here](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L27).
It would be great to check it for presence before getting and raise a descriptive error if it is blank. 

Could I make a PR?

**Comment by anjumjfax** [comment]
I've encountered similar confusion and fuss when writing specs. Specifically my issue was, that I was forgetting to declare a `path` block in the first place. That's how I would more generically characterise the issue you describe, that the `get` block (or post, put, etc...) is orphaned from a `path` block, which is what I think an error should say.

**Comment by jtannas** [comment]
Heyo - I'm a new volunteer sorting through the issue backlog.
I'm removing the `wontfix` label because this seems like a very valid problem that's worth addressing.
I think my biggest personal frustration with RSwag as it is right now is the cryptic error messages.

That being said, we're pretty shorthanded as we catch up on a year on inactivity in this gem so any contributions you can make towards a fix would be greatly appreciated :bow:
