### ISSUE TITLE
Is OA 3.0 supported? 

### ISSUE THREAD

**Issue by PhilippeChab** [rswag/rswag#282]
The title says it all. I've seen some issues and PR talking about it but nothing in the README. Or is it a WIP?

**Comment by BookOfGreg** [comment]
WIP :)
There's a fork that does it already but I'm trying to make one that is backward compatible, at least can support 2 and 3.

**Comment by jordanmaguire** [comment]
For others looking for the fork, I think this is it: https://github.com/jdanielian/open-api-rswag

**Comment by BookOfGreg** [comment]
https://github.com/rswag/rswag/pull/286

**Comment by BookOfGreg** [comment]
Merged. Version 2.3.0 of rswag supports Openapi 3.0.

Just change your swagger_helper from `swagger: 2.0` to `openapi: '3.0.1'` and it will attempt to output openapi3 with no changes needed to your tests.
You will get deprecation warnings if there's anything that can be made more like openapi 3's syntax, usually done in the swagger_helper.

If anyone notices that it does not generate valid openapi3 on their existing tests please open an issue. Not we know that the common trick of adding `example` onto the response metadata will result in a validation warning, we will look at that for 2.4.x

Hope this helps!
