### ISSUE TITLE
`rake rswag` does not correctly generate response models

### ISSUE THREAD

**Issue by ty-porter** [rswag/rswag#287]
@spikeheap mentioned an issue (#270 & [comment](https://github.com/rswag/rswag/issues/268#issuecomment-570533891)) a few months ago regarding `rake rswag` not correctly generating response models.

### **Actual:**
The following code:

```ruby
RSpec.describe 'Games API', type: :request, swagger_doc: 'v1/swagger.json' do
  path '/games' do
    get 'Retrieves a record' do
      tags 'Games'
      produces 'application/json'

      response '200', 'game found' do
        schema '$ref' => '#/definitions/game_index_response'
        run_test!
      end
    end
  end
end
```

generates the following JSON:

```json
  "paths": {
    "/games": {
      "get": {
        "summary": "Retrieves a record",
        "tags": [
          "Games"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "game found",
            "schema": {
              "$ref": "#/definitions/game_index_response"
            }
          }
        }
      }
    }
  }
```

and produces no model in the UI:

![image](https://imgur.com/57fMq8M.png)

### **Expected:**

According to the [OpenAPI 3.0.1 ResponseObject spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#responseObject):

```json
  "responses": {
          "200": {
            "description": "game found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/game_index_response"
                }
              }
            }
          }
        }
```

And generates the correct model:

![image](https://i.imgur.com/Fnh43XD.png)

The issue appears to be in `rswag-specs/lib/rswag/specs/example_group_helpers.rb`:

```ruby
def schema(value)
  metadata[:response][:schema] = value
end
```

This appears to set the schema value in an incorrect manner.

**Comment by BookOfGreg** [comment]
Agreed, will look at merging the related PR into https://github.com/rswag/rswag/pull/286
Both the Consumes and Produces array are incorrectly handled in the same way.
