### ISSUE TITLE
Definition DSL

### ISSUE THREAD

**Issue by hlascelles** [rswag/rswag#292]
We use rswag successfully for routes/tests etc, but there is some repetition when we write out our definitions for our resources. We can reduce some of it by using a small DSL.

Having looked around, we didn't find anything that would fit our needs so are currently doing something like this:

```
# "Definition" is a DSL class we have defined.
Definition.define(
  :food,
  Definition.object(
    id: { type: :string, description: "The id", example: "FD2345", required: true },
    purpose: { type: :string, description: "Main ingredient", example: "Cheese" }
  )
)
```

The output just just a nested hash that we use in rswag as normal.

Does `rswag` intend (or want) to cover this area? Or do you know of any projects that perform this job?

**Comment by BookOfGreg** [comment]
Is this what swagger definitions are for?
https://github.com/rswag/rswag/blob/master/test-app/spec/swagger_helper.rb#L37
Used as:
https://github.com/rswag/rswag/blob/master/test-app/spec/integration/blogs_spec.rb#L13

Worth noting in our OpenAPI 3.x branch, this will be moved from `/definitions` to `/content/schemas`.

If this is not what you meant let me know.

**Comment by hlascelles** [comment]
That's the desired output, yes. Once constructed, the `Definition` tree is output to a hash and used there. Our goal was to make their construction just _a little_ more formal. Just glancing through it, I see it:

1. Sets `additionalProperties: false` everywhere.
1. Catches invalid /misspelled hash keys
1. Provides a `required: true` we can make the building of the `required: []` section easier.
1. Allows reuse of "types": eg names, emails, address values can all use a same base type / sharing of regexes.

It really doesn't do very much, maybe not necessary for simple APIs. If it's not in rswag's wheelhouse, not a problem, I can close this.
