### ISSUE TITLE
Please unrequire bye bug

### ISSUE THREAD

**Issue by mhenrixon** [rswag/rswag#295]
In `rswag-specs-2.3.0/lib/rswag/specs/request_factory.rb:6` there is a `require 'byebug'` statement and I do NOT want to add the byebug gem to be able to use rswag :)

**Comment by yxhuvud** [comment]
Either that, or at the VERY least add it to the gem requirements, because as is, this is breaking our deploy in certain environments.

**Comment by BookOfGreg** [comment]
Oops! Yep that's a mistake.

**Comment by BookOfGreg** [comment]
https://github.com/rswag/rswag/releases/tag/2.3.1
Let me know that fixes it for you.

**Comment by tomasdundacek** [comment]
@BookOfGreg Yep, thank you very much! 🙂

**Comment by mhenrixon** [comment]
That worked :)
