### ISSUE TITLE
Rails 5.0 compatibility

### ISSUE THREAD

**Issue by ktopolski** [rswag/rswag#3]
Hey,

Thanks for awesome gem! It's working really good with rails `5.0.0.rc2`!

However, there seems to be a problem with the recent 5.0 version. The gem depends on `rails < 5`. Bundler versioning assumes that any `5.0` release candidate is satisfying the `< 5` conditional. Is there any barrier for bumping the version in Gemfile.lock to `<= 5.0` ? If there are any unresolved urgent issues I may be able to help.

Cheers!

**Comment by dima4p** [comment]
+1

**Comment by dima4p** [comment]
I tried it in my project, it works
https://github.com/domaindrivendev/swagger_rails/pull/4

**Comment by dnswus** [comment]
Support all 5.0 versions after this https://github.com/domaindrivendev/swagger_rails/pull/7.

**Comment by drewish** [comment]
One issue I've noticed with a Rails 5 site generated with the API mode (`rails new backend --api`) is that swagger generator blows up:

```
% rails g --help
/Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007faa62ed0940> (NoMethodError)
Did you mean?  asset_host
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/swagger_rails-5003b7ccd9ff/lib/swagger_rails/engine.rb:10:in `block in <class:Engine>'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
    from /Users/andrew/projects/accounting_integration/config/environment.rb:5:in `<top (required)>'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:60:in `generate'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/andrew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by drewish** [comment]
Uncommenting the `require "sprockets/railtie"` in `config/application.rb` got past the error. 

It would be nice to either document the requirement or just test for sprockets before trying to add the path. It seems like it could be optional since you could still use it to generate the JSON and host the swagger-ui assets elsewhere.

I'll open up a separate issue for this though.

**Comment by domaindrivendev** [comment]
My plan for this is to seperate into two gems - one for the json and another for the swagger-ui so you do exactly what you proposed.

**Comment by drewish** [comment]
Great! Could you do a release of the current gems now so it's Rails 5 compatible? It'd be nice to avoid sourcing it from the master branch.

**Comment by drewish** [comment]
@domaindrivendev seems like there's actually a few other gems with engines for serving up swagger-ui:
- https://github.com/batdevis/swagger_engine
- https://github.com/ruby-grape/grape-swagger-rails

So it might make more sense to just look at adding one of those as a dependency and pushing necessary customizations upstream.

**Comment by domaindrivendev** [comment]
Check out the latest version 1.0.0. It should be Rails 5 compatible and also has lots of other great features added. NOTE: the name change from swagger_rails to rswag and the decomposition into components so you can pick and choose which parts you need. Also worth noting there's a minor breaking change - the "parameter" method in the rspec DSL now expects a single argument (attributes) that includes "name" instead of two arguments (name, attributes).
