### ISSUE TITLE
Is it possible to use this gem without swagger specs?

### ISSUE THREAD

**Issue by rusikf** [rswag/rswag#306]
Hi swagger hackers!

Is it possible to generate docs without writing specs?

I want to generate swagger docs, But in the same way as here https://github.com/ruby-grape/grape-swagger#overriding-the-tags-

For example, if developer right specific comments before def in api controller, they can be parsed and used for generating swagger docs

**Comment by oblakeerickson** [comment]
Nope. Pretty sure you can only generate docs from specs. The nice side effect of this though is that you also have tests you can run to validate your api hasn't deviated from your api docs.
