### ISSUE TITLE
Should this require rspec-core?

### ISSUE THREAD

**Issue by cenotaph** [rswag/rswag#308]
I am struggling with the issue #60 so I tried to create a new blank Rails project to start over with Rails 6.0.2.2, just following the directions. Generating the rswag:install fails because rspec-core is not a requirement.

Obviously it is assumed that people will be using rspec already, but just to make the documentation work out of the box, it might be good to either require this as a dependency or add it to the documentation?

And back to figuring out why I'm stuck on issue #60....

**Comment by BookOfGreg** [comment]
Yes it should be part of the gemspec for rswag-specs. PR welcome to any of the people who +1'ed this.
