### ISSUE TITLE
Feature: Inject swagger-ui config into default template

### ISSUE THREAD

**Issue by reshleman** [rswag/rswag#309]
The README [explains](https://github.com/rswag/rswag#customizing-the-swagger-ui) how to customize swagger-ui by generating and editing the `app/views/rswag/ui/home/index.html.erb` template file. This works!

It would be neat if I could configure swagger-ui -- particularly the [parameters](https://github.com/swagger-api/swagger-ui/tree/2.x#swaggerui) described in the docs -- by setting the desired key-value pairs in `config/initializers/rswag-ui.rb` so that they are injected into the default template file without needing me to generate it.

Perhaps something like this (in `config/initializers/rswag-ui.rb`):

```ruby
Rswag::Ui.configure do |c|
  c.swagger_endpoint '/api-docs/v1/swagger.yaml', 'API V1 Docs'

  c.parameters = {
    'apisSorter' => 'alpha',
    'operationsSorter' => 'alpha',
  }
end
```

... and then these provided `parameters` would get merged into the `configObject` in the default template.

(PS- Thanks for your work on this gem! 😃)

**Comment by jtannas** [comment]
not stale
