### ISSUE TITLE
Refused to execute inline script chrome error

### ISSUE THREAD

**Issue by rusikf** [rswag/rswag#310]
After generate first spec, I receive 

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-j4Lx1FqFgvYDBEjW7NQaEY7/HhCi8WVsLWkqC4+wJ3w='), or a nonce ('nonce-...') is required to enable inline execution.

On index.html 71,80. Is it possible to fix this ?
In chrome console http://localhost:3000/api-docs/index.html with empty swagger specs

**Comment by jacksonj04** [comment]
I think this is a duplicate of #174

**Comment by jtannas** [comment]
Heyo - new volunteer here sorting through the issue backlog and came across this.
I'm going to close this issue since it's a duplicate of an older ticket with discussion in it.
Thank you for contributing though! :slightly_smiling_face:
