### ISSUE TITLE
Multiple request types for same endpoint

### ISSUE THREAD

**Issue by Evilbits** [rswag/rswag#315]
I'm running into an issue while documenting my OAuth `password` and `refresh_token` grant type flows.
Either the user can send the `password` grant which requires one body or they can send the `refresh_token` grant which requires another body type.
It seems that I can display this in the schema but is it possible to create two separate example body?

This is my current approach however it leaves me with no "Example Value". I can add it but then it would be only for one of the two possible request types.
![image](https://user-images.githubusercontent.com/562749/81037312-6f4cd400-8ecc-11ea-80e0-354d05bd9d6b.png)
This however shows no example. I can get either of the examples by adding the properties outside the `oneOf` however I'd like to be able to display both if possible.
![image](https://user-images.githubusercontent.com/562749/81037436-f26e2a00-8ecc-11ea-9cda-159eb17b10d4.png)

It should be noted that I also tried with multiple `parameters` and multiple integration tests for the same endpoint however neither seemed to work correctly.

**Comment by heo001997** [comment]
I have this problem too
+1 upvote

**Comment by phlegx** [comment]
I have this problem too. Have you found a solution?

**Comment by Evilbits** [comment]
I resorted to simply writing a description directing the user to look at the `schema` since the example values are missing. Sadly it doesn't look very good but I guess it gets the problem solved (however not the intended way).
