### ISSUE TITLE
OAS v3 tests fail without `basePath`, but `basePath` generates invalid Swagger

### ISSUE THREAD

**Issue by reshleman** [rswag/rswag#318]
With the removal of [`basePath`](https://swagger.io/docs/specification/api-host-and-base-path/) in OpenAPI v3, I now define API host(s) using the `servers` field, like this:

```ruby
RSpec.configure do |config|
  config.swagger_docs = {
    'v1/swagger.yaml' => {
      openapi: '3.0.1',
      info: {
        title: 'My API V1',
        version: 'v1'
      },
      servers: [
        {
          url: 'https://api.example.com/v1',
        },
      ],
      # ...
    },
  }
end
```

And I define my endpoints using rswag like this:

```ruby
describe 'My API', type: :request, swagger_doc: 'v1/swagger.yaml' do
  path '/resources' do
    # ...
  end
end
```

This results in the generation of the expected, valid Swagger docs.

However, attempting to run the integration tests using this configuration will fail with a routing error, because the version (previously the `basePath`) is no longer prefixed to the path when running the tests:

```ruby
     ActionController::RoutingError:
       No route matches [GET] "/resources"
```

(The expected generated path is `/v1/resources`.)

OTOH, including the `basePath` in the Swagger config, in addition to the `servers` key, results in passing tests; however, the generated Swagger docs fail validation, because they include the invalid `basePath` property:

```yaml
openapi: 3.0.1
info:
  title: My API V1
  version: v1
basePath: "/v1"
servers:
- url: https://api.example.com/v1
```

Any suggestions on how to resolve this?

**Comment by d11wtq** [comment]
Agree it would be good to fix this internally, but we've solved this by putting the `/v1` in each path and leaving `servers.url` as the host-only. You can probably just remove `basePath` from the resulting file though too.

**Comment by phlegx** [comment]
@d11wtq your solution is not correct. It works but it is not correct. Read here how Swagger 3.0 defines [API Server and Base URL](https://swagger.io/docs/specification/api-host-and-base-path/).

```
https://api.example.com/v1/users?role=admin&status=active
\________________________/\____/ \______________________/
         server URL       endpoint    query parameters
```

It is an internal problem of Rswag and should be solved.

**Comment by NicoSa** [comment]
I have the same issue 👋

**Comment by helderasmoreira** [comment]
Same issue here! Is there a "proper" way of handling this that we're missing?

**Comment by oblakeerickson** [comment]
Not yet. As a temporary workaround looks like maybe you can add `base_path` in rswag, but then remove it from the openapi.json output so that it is still valid?

This is on my list to fix.

**Comment by helderasmoreira** [comment]
> Not yet. As a temporary workaround looks like maybe you can add `base_path` in rswag, but then remove it from the openapi.json output so that it is still valid?
> 
> This is on my list to fix.

Yes, I've decided to do just that 👌

**Comment by developingchris** [comment]
#397 
I've created a PR to close this gap, as I starting having this issue a few days ago as well.
I'm working on a description for it.

**Comment by 0x7466** [comment]
+1

**Comment by dostapn** [comment]
+1
