### ISSUE TITLE
Parameters always empty

### ISSUE THREAD

**Issue by heaven** [rswag/rswag#320]
```ruby
require 'swagger_helper'

describe 'Golfer Registration API', swagger_doc: 'v1/golfer/swagger.yaml' do
  path '/registration' do
    post 'Creates a Golfer record' do
      tags 'Golfer Registrations'

      parameter name: :registration, in: :body, schema: {
        '$ref' => '#/components/schemas/registration'
      }

      let(:registration) do
        {
          email:                 Faker::Internet.email,
          first_name:            Faker::Name.first_name,
          last_name:             Faker::Name.last_name,
          phone:                 Faker::PhoneNumber.phone_number,
          password:              "Test1234",
          password_confirmation: "Test1234"
        }
      end

      response '201', 'Created' do
        schema '$ref' => '#/components/schemas/user_access_token'

        run_test! do |response|
          expect(Golfer.count).to eq 1
          expect(Golfer.last.access_tokens.last.key).to eq parsed(response)[:user_access_token][:key]
        end
      end
    end
  end
end
```
Produces:
```yaml
paths:
  "/registration":
    post:
      summary: Creates a Golfer record
      tags:
      - Golfer Registrations
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_access_token"
```

Parameters empty even though there's `parameter name: :registration`.

**Comment by heaven** [comment]
It doesn't work with both `yaml` and `json` formats even though specs do pass.

**Comment by heaven** [comment]
Probably a duplicate of #290

**Comment by heaven** [comment]
Here's the bug! https://github.com/rswag/rswag/blob/7ceedab4cb7788ab6b86b96bd2d8f2419e11ebbb/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L67

Commented out this line and parameters now appear in the UI.

This commit https://github.com/rswag/rswag/commit/2af7c13e59a1bacccdd8136db93894acf0e71dac

Should I use anything else instead of `in: :body`?

**Comment by deXterbed** [comment]
@heaven what version you are on? v2.3.1 works fine for me

**Comment by heaven** [comment]
I am on 2.3.1 and it doesn't work. The problem is in the UI, when you click try it out -> execute:
<img width="1155" alt="Screen shot 2021-01-22 at 10 59 56" src="https://user-images.githubusercontent.com/126732/105469487-fb906880-5ca0-11eb-9ba5-e2a8cc10adde.png">

**Comment by deXterbed** [comment]
@heaven did you try using `let` within the `response` block? Something like this:

![image](https://user-images.githubusercontent.com/1491315/105470597-c3e4e900-5cbf-11eb-87ce-46b6732f183b.png)
 
Not saying this is the solution, but could be a temporary workaround

**Comment by heaven** [comment]
@deXterbed Yep, here's the spec I created yesterday:
```
require 'swagger_helper'

describe 'Registration API', swagger_doc: 'v1/swagger.yaml' do
  path '/registration' do
    post 'Creates a Member account' do
      tags 'Registrations'

      parameter name: :registration, in: :body, schema: {
        '$ref' => '#/components/schemas/registration'
      }

      let(:registration) do
        {
          kind:                  Member.kinds.keys.sample,
          email:                 Faker::Internet.email,
          first_name:            Faker::Name.first_name,
          last_name:             Faker::Name.last_name,
          password:              "Test1234",
          password_confirmation: "Test1234"
        }
      end

      response '201', 'Created' do
        schema '$ref' => '#/components/schemas/user_access_token'

        run_test! do |response|
          expect(Member.count).to eq 1
          expect(Member.last.access_tokens.last.key).to eq parsed(response)[:user_access_token][:key]
        end
      end

      response '422', 'Unprocessable Entity' do
        let(:registration) do
          {
            kind:                  Member.kinds.keys.sample,
            first_name:            Faker::Name.first_name,
            last_name:             Faker::Name.last_name,
            password:              "Test1234",
            password_confirmation: "Test1234"
          }
        end

        run_test!
      end
    end
  end
end
```

The spec works (and it did before) but the swagger.yml is wrong and the UI doesn't work as expected. This is how it looks like:
<img width="1442" alt="Screen shot 2021-01-22 at 11 13 41" src="https://user-images.githubusercontent.com/126732/105471242-32677e00-5ca3-11eb-9923-35daee3f3956.png">

You can see no `registration` body parameter.

This https://github.com/codeart/rswag/commit/deb4f52884a88ced5c6c4ad06b64404701f10ef4 brings the body parameter back to the UI so front-end developers who work with this API can at least see the parameners. But when you try to send a test request from the UI `registration` body parameter is missing in the request.

**Comment by deXterbed** [comment]
@heaven can you share the schema for `registration` ?

**Comment by deXterbed** [comment]
@heaven you might have to explicitly add that parameter in the schema, i personally avoid using '$ref' for readability, so this is how i've done it for one of my tests:

```ruby
parameter({
        name: :user, 
        in: :body, 
        schema: {
          type: :object,
          properties: {
            name: :user,
            user: {
              type: :object,
              properties: {
                first_name: { type: :string, example: 'John' },
                last_name: { type: :string, example: 'Doe' },
                email: { type: :string, example: 'john@doe.com' },
                password: { type: :string, example: '123456' }
              }
            }
          },
        }
      })
```
And this is the output in the UI:

![image](https://user-images.githubusercontent.com/1491315/105475071-fa713280-5cc4-11eb-9621-d492582e97d7.png)

Hope that helps!

**Comment by heaven** [comment]
Sure, here's the schema:
```
schemas:     {
  null: {
    type: :null
  },

  registration: {
    type:       :object,
    properties: {
      kind:                  { type: :string, enum: Member.kinds.keys },
      email:                 { type: :string },
      first_name:            { type: :string },
      last_name:             { type: :string },
      password:              { type: :string },
      password_confirmation: { type: :string }
    },
    required:   %i[kind email first_name last_name password password_confirmation]
  },
```

Our schema file on another project is 3k lines, putting that to specs doesn't seem reasonable. Even though this might work but there's definitely a bug.

**Comment by heaven** [comment]
@deXterbed I just tried this:
```
parameter name: :registration, in: :body, schema: {
  type:       :object,
  properties: {
    name: :registration,
    registration: {
      type:       :object,
      properties: {
        kind:                  { type: :string, enum: Member.kinds.keys },
        email:                 { type: :string },
        first_name:            { type: :string },
        last_name:             { type: :string },
        password:              { type: :string },
        password_confirmation: { type: :string }
      },
      required:   %i[kind email first_name last_name password password_confirmation]
    }
  }
}
```

No luck, the `registration` param doesn't show in the Swagger UI.

**Comment by heaven** [comment]
@deXterbed it clearly tries to do something with the body params here: https://github.com/codeart/rswag/blob/deb4f52884a88ced5c6c4ad06b64404701f10ef4/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L61

Trying to convert them perhaps to the new format and then deletes them here:
https://github.com/codeart/rswag/blob/deb4f52884a88ced5c6c4ad06b64404701f10ef4/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L67

**Comment by deXterbed** [comment]
@heaven did you also update the definition inside the `let(:registraion)` block, it should also have the `registration` key, something like this:

```ruby
let(:registration) { { registration: attributes_for(:registration, first_name: 'xyz') }}
```

**Comment by heaven** [comment]
The problem is on this line:
https://github.com/codeart/rswag/blob/deb4f52884a88ced5c6c4ad06b64404701f10ef4/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L59

I just put debugger there and can see it's `nil`. 

Adding `consumes` to my spec like this fixed the problem:
```
consumes 'application/json'
parameter name: :registration, in: :body, schema: {
  '$ref' => '#/components/schemas/registration'
}
```

This is strange because I have this in `swagger_spec.rb`:
```
config.swagger_docs = {
  'v1/swagger.yaml' => {
    openapi:    '3.0.1',
    info:       {
      title:   'User API',
      version: 'v1'
    },
    paths:      {},
    servers:    [...],
    consumes:   ['application/json', 'multipart/form-data', 'application/x-www-form-urlencoded'],
    produces:   ['application/json'],
    basePath:   '/api/v1',
    components: {
```

@deXterbed shouldn't it be inherited from there?

**Comment by heaven** [comment]
@deXterbed can you please have a look?

**Comment by rubykachu** [comment]
I also had the same problem. How to fix it :'(

**Comment by weezing** [comment]
@rubykachu in your `swagger_helper.rb` file just change proper line from `openapi: '3.0.1'` to `swagger: '2.0'`

After that just re-generate docs.

Openapi 3.0.x does not support body params, it consumes requestBody instead (source: https://swagger.io/docs/specification/describing-request-body/)
