### ISSUE TITLE
How to not include optional parameters in cURL

### ISSUE THREAD

**Issue by zkatemor** [rswag/rswag#328]
Request body:

```
requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                area:
                  type: string
                country:
                  type: string
```

If I send a request within Swagger with empty value in some field, the evaluates the request like this:
`curl -X PUT "http://localhost:3000/cities/1" -H "accept: */*" -H "Content-Type: multipart/form-data" -d {"name":"","area":"","country":"Russia"}`

But I need not to have the empty fields added in the request body, like this:
`curl -X PUT "http://localhost:3000/cities/1" -H "accept: */*" -H "Content-Type: multipart/form-data" -d {"country":"Russia"}`

Tell me how to fix this situation? Thanks!

**Comment by theKirill** [comment]
I have a same problem!

**Comment by pechorin** [comment]
Add length validation for string

**Comment by romanblanco** [comment]
@zkatemor does [this advice](https://github.com/rswag/rswag/issues/586#issuecomment-1450056842) help your case?
