### ISSUE TITLE
How to Access Original Response

### ISSUE THREAD

**Issue by fny** [rswag/rswag#34]
I'm trying to access RSpecs `response` to ensure the values returned are actually correct for a given requrest, but it doesn't look like I'm able to do so since it's been overridden by rswag's `response`.

How can I access the original response?

**Comment by domaindrivendev** [comment]
For additional response assertions, you should be able to access the original response by creating an additional "example" block. For example:

``` ruby
get 'Searches stuff' do
  produces 'application/json'

  response '200', 'success' do
    schema type: 'array', items: { type: 'string' }
    run_test!

    it 'returns a unicorn' do
      expect(response.body).to eq("[ \"unicorn\" ]") 
    end
  end
end
```
