### ISSUE TITLE
Document requestBody

### ISSUE THREAD

**Issue by seanstory** [rswag/rswag#343]
I tried to update my specs from `swagger: 2.0` to `openapi: 3.0.1`, and all my `:in => :body` parameters went away. I saw in the OpenAPI 3 docs that `requestBody` had replaced these old params, but couldn't find in the `rswag` documentation how to get the right behavior.

I found the `jdanielian` fork that had `requestBody` [documented in the README](https://github.com/jdanielian/open-api-rswag#open-api-rswag-helper-methods), and then finally found that documentation _does_ exist in rswag, but has [been commented out](https://github.com/rswag/rswag/commit/4ab432080b795672c66c81e3a8bf7f44c20059d7), so it's not visible unless you view the README as "raw" or clone it.

I don't think those docs are up to date, and should probably be removed (not just commented out). But there should also probably be a note that to get request bodies to show up, the parameter needs to have a `:schema => { :$ref => '#/components/schemas/something' }`, where before a simple `:$ref => '#/components/schemas/something'` was sufficient.

**Comment by joshuaswilcox** [comment]
I dont see how this gem can be "OpenApi 3.0 and Swagger 2.0 compatible!" if it doesnt allow setting the request body?

**Comment by seanstory** [comment]
It does allow setting the request body @joshuaswilcox - it's just not documented. This issue is to request that the functionality be documented.

use: 

```
 parameter :name => :something, :in => :body, :schema => { :$ref => '#/components/schemas/something' }
```

**Comment by stefanondisponibile** [comment]
I don't think it does (if it does, I don't know how).

Using:
```
parameter :name => :something, :in => :body, :schema => { :$ref => '#/components/schemas/something' }
```

is *not* equivalent to setting the path operation [`requestBody`](https://swagger.io/specification/#request-body-object) property.

`parameter` sets parameters at `PathItem` level (not `PathOperation`s like `get`, `post`, etc...).

How can `requestBody` be set in the [`PathOperationObject`](https://swagger.io/specification/#operationObject)?

**Comment by seanstory** [comment]
This issue is still relevant. Please remove the "wontfix" label unless there is a reason why you would not support `requestBody` and document how to set it.

**Comment by Drowze** [comment]
Still relevant!

**Comment by rotemiara** [comment]
Still relevant!

**Comment by slayer** [comment]
still relevant

**Comment by mkllnk** [comment]
I just tried using `request_body_json` with the latest rswag version 2.9.0 and I got:

```
NoMethodError:
  undefined method `request_body_json' for RSpec::ExampleGroups::SuppliedProducts::ApiDfcV17EnterprisesEnterpriseIdSuppliedProducts::Post:Class
  Did you mean?  request_body_example
```

So it looks like those undocumented methods got removed. Does that close this issue?

The given example above works for me:
```
parameter :name => :something, :in => :body, :schema => {}
```

Please note that if you omit the `schema` then it won't show. If you move the declaration one level up to the `path` instead of `post` then it does show without the schema. But then it appears as general parameter and not as request body. So just in case someone stumbles over this again:

> You need the `schema` keyword and you need to nest the parameter declaration in the pathOperation (put, patch, post) block for it to appear as request body parameter.
