### ISSUE TITLE
Describing Empty Response Body

### ISSUE THREAD

**Issue by psmandzich** [rswag/rswag#346]
Currently, describing an empty response body is not feasible. As mentioned in [documentation](https://swagger.io/docs/specification/describing-responses/#empty) `content` should be left out to enable responses without content.

I found the default insertion of an empty `content` block at [formatter](
https://github.com/rswag/rswag/blob/42fdf6d482b2e5d4aee4f461abf697b2aa9c3894/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L132). To my mind, that hash should be initialized after the return statement in line 135.

**Comment by oblakeerickson** [comment]
Can you do something like this?

```
  produces 'application/json'
  response '200', 'empty response' do
    let(:group) { { name: 'awesome' } } 
    run_test!                           
  end    
```

which should result in output like:


```
    responses:
      '200':
        description: empty response
        content: {}
```

**Comment by oblakeerickson** [comment]
looks like this is addressed in PR https://github.com/rswag/rswag/pull/347 ?

**Comment by psmandzich** [comment]
> Can you do something like this?
> 
> ```
>   produces 'application/json'
>   response '200', 'empty response' do
>     let(:group) { { name: 'awesome' } } 
>     run_test!                           
>   end    
> ```
> 
> which should result in output like:
> 
> ```
>     responses:
>       '200':
>         description: empty response
>         content: {}
> ```

initially I tried this implementation first. But other tools such as swagger-ui require a correct implementation of the specification. The output `content: {}` leads in swagger-ui to introduce a broken response content-type (https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/response.jsx#L180). Based on documentation the response should left out the `content`-key alike: 

```
    responses:
      '200':
        description: empty response
```

**Comment by oblakeerickson** [comment]
Oh okay I didn't realize swagger-ui was showing a broken response type. I'm currently using ReDoc on a project and it doesn't display an error:

![image](https://user-images.githubusercontent.com/1490496/90778116-7d770280-e2b9-11ea-8f65-835a28fd9fbb.png)

**Comment by psmandzich** [comment]
with filled `content`
<img width="271" alt="Bildschirmfoto 2020-08-28 um 12 59 35" src="https://user-images.githubusercontent.com/7753474/91553890-704bba80-e92e-11ea-9917-f2eb623a3def.png">

with `content: {}`
<img width="205" alt="Bildschirmfoto 2020-08-28 um 13 02 03" src="https://user-images.githubusercontent.com/7753474/91554072-b274fc00-e92e-11ea-8700-d59ef2d6d95e.png">

When I remove `content: {}` from output `Media type` is left out in the GUI.
