### ISSUE TITLE
How to send parameter outside of the RSwag schema in the RSpec test?

### ISSUE THREAD

**Issue by wscourge** [rswag/rswag#356]
With RSwag and RSpec in Ruby on Rails, is it possible to send a parameter that is not defined as a `parameter` via the `run_test!`?

Example test:

```
# frozen_string_literal: true

require "swagger_helper"

describe "Resources", type: :request, swagger_doc: "api/resources.json" do
  path "/resources" do
    get "get resources" do
      tags "resources"

      parameter name: "sort[column]",
                in: :query,
                type: :string,
                enum: ["created_at", "updated_at"]
                required: false
      parameter name: "sort[order]",
                in: :query,
                type: :string,
                enum: ["asc", "desc"]
                required: false

      response "422", "Unprocessable Entity" do
        context "with unrecognized param" do
          # define sort[direction] here

          run_test! do |respone|
            expect(json_response["errors"]).to contain_exactly(
              # my serialized response error
            )
          end
        end
      end
    end
  end
end
```

I'd like to send `sort[direction]` in my `context`. What I have tried so far:

```
let(:"sort[direction]") { "asc" }
let(:sort) { { direction: "asc" } }
let(:sort) { { "direction" => "asc" } }
```

with no avail - I got HTTP 200 Success, even though the same request sent via Postman with `sort[direction]` defined responds with expected HTTP 422 Unprocessable Entity.

**Comment by oblakeerickson** [comment]
I'm able to get this working in my dev environment following the example in the README

```
      response '422', 'invalid request' do
        let(:blog) { { title: 'foo' } }
        run_test!
      end
```

but that isn't using query params. I think maybe the query params aren't even being sent in the tests if they aren't specified.

Could you `puts params` inside of your controller and see if the `direction` param is even getting there?

**Comment by wscourge** [comment]
I have managed to do it this way:

```
context "with unrecognized sort param" do
  before do |example|
    example.metadata[:example_group][:operation][:parameters] += [{
      name: "sort[direction]",
      in: :query,
      type: :string,
      required: false
    }]
  end

  let(:"sort[direction]") { "asc" }

  run_test! do |respone|
    expect(json_response["errors"]).to contain_exactly(
    # my serialized response error
    )
  end
end
```

It does not add the params to the generated OpenAPI JSON file, which is good.

**Comment by jtannas** [comment]
Heyo - new volunteer here sorting through the issue backlog and came across this.
I'm going to keep this one alive to add to an FAQ, since testing how and API responds to unexpected parameters seems like it'd be a common use case

**Comment by jtannas** [comment]
Added to the FAQ: # Source: https://github.com/rswag/rswag/issues/356#issuecomment-692473556

Thanks @wscourge ! Hopefully we get around to adding an easier way someday :tired_face:
