### ISSUE TITLE
Config swagger_dry_run not respected.

### ISSUE THREAD

**Issue by phlegx** [rswag/rswag#359]
Hi!

I have placed in many parts of my code the `swagger_dry_run` config like here:

```ruby
RSpec.configure do |config|
  config.swagger_dry_run = false
end
```

But no one is working if I call `rails rswag` or `rake rswag` from console.

**Comment by M-H-Mukit** [comment]
@phlegx  try putting the code in config/application.rb instead

swagger_dry_run issue will be solved.

After that, I stuck on. The example is not auto-generating in swagger docs.

Please let me know if you can figure out.

**Comment by phlegx** [comment]
@M-H-Mukit putting code at the end of file config/application.rb works! Thx

**Comment by M-H-Mukit** [comment]
@phlegx  Do you get success on "auto-generating the response example for swagger docs"?

**Comment by phlegx** [comment]
Yep! See my comment on issue [325](https://github.com/rswag/rswag/issues/325#issuecomment-692707935).

**Comment by schmijos** [comment]
I think it's not so nice to put the configuration into `config/application.rb` because it's production code. I've put it into the `Rakefile` instead (still may be run in production, but at least only for tasks):

```ruby
require_relative 'config/application'

# Workaround for https://github.com/rswag/rswag/issues/359
if defined? RSpec
  RSpec.configure do |config|
    config.swagger_dry_run = false
  end
end

Rails.application.load_tasks
```

**Comment by kwent** [comment]
Above solution worked well for me

**Comment by knarewski** [comment]
A little bit of explanation:
`rswag` rake task relies on the config being set before the `rspec` command is invoked. Therefore putting this config in a file like `spec_helper.rb` doesn't have any effect (as the `spec_helper.rb` is not loaded at that point). See:
https://github.com/rswag/rswag/blob/83567e0ee24dfd77fff96450e3b3031c7da81ec4/rswag-specs/lib/tasks/rswag-specs_tasks.rake#L15

The workarounds above seem reasonable. The one I settled on is to skip `rswag` rake task altogether and invoke the command directly to generate the `swagger.yml` file:
```ruby
bundle exec rspec --format Rswag::Specs::SwaggerFormatter --order defined --pattern 'spec/requests/**/*_spec.rb, spec/api/**/*_spec.rb, spec/integration/**/*_spec.rb'
```
It's less compact, but mitigates the `dry_run` issue as well as removes some of the `rswag` magic.

**Comment by purian** [comment]
You can use this ENV to control the dry run as well SWAGGER_DRY_RUN=0
Like this:
`SWAGGER_DRY_RUN=0 rake rswag:specs:swaggerize  `

**Comment by jtannas** [comment]
Looks like this issue predates v2.4.0 which added the `SWAGGER_DRY_RUN` variable and updated the README https://github.com/rswag/rswag/releases/tag/2.4.0

I'm going to close this issue because of those changes, but feel free to reopen it or create another if you think more needs to be done.

**Comment by StarSheriff2** [comment]
putting this 
```
RSpec.configure do |config|
    config.swagger_dry_run = false
  end
```
inside the config/environments/test.rb or the config/environments/development.rb files has no effect whatsoever, as per README.md.

Please remove this or update this line of instruction as I have lost precious time trying to figure out why this doesn't work. It's incredibly frustrating to not know if you can or cannot rely on the documentation of this gem.

**Comment by KellyBennett** [comment]
I just wasted a bunch of time on this exact issue. I'm still trying to evaluate if I want to use RSwag at my company, so I'm not sure how invested I am in this, and can just use the workaround for now. If it turns out that we do want to integrate this gem into our workflow I might try to add a Pull Request to fix the issue. 

But at the very least I wanted to put in my 2 cents and say that this is a pretty major issue.

**Comment by elik-ru** [comment]
Putting `ENV["RSWAG_DRY_RUN"] = "false" unless ENV.key?("RSWAG_DRY_RUN")` to the end of `Rakefile` solved the problem for me.

Or in a rake taks to use together with redocly:

```
desc "Run redocly on documentation file"
task redocly: :environment do
  ENV["RSWAG_DRY_RUN"] = "false" unless ENV.key?("RSWAG_DRY_RUN")

  Rake::Task["rswag"].invoke
  sh "redocly build-docs swagger/v1/swagger.json -o swagger/v1/swagger.html"
end
```
