### ISSUE TITLE
Generated files are empty

### ISSUE THREAD

**Issue by jfrojo** [rswag/rswag#365]
So after following each step from the getting started guide, all I get are almost empty files, with no content. Any ideas on why this could be happening?

**Comment by jfrojo** [comment]
Bump

**Comment by BookOfGreg** [comment]
No idea I'm afraid, it works for most people. I assume you have run the swaggerize rake task? Did you get any output?

**Comment by buntine** [comment]
The swaggerize rake task looks for specs in a set of predefined locations. If your specs are defined somewhere else in your app, you should pass in the `PATTERN` env variable.

```
PATTERN=spec/path/to/your/tests/*.rb rake rswag:spec:swaggerize
```

**Comment by jfrojo** [comment]
Sorry for the delay on the response, yes I did't use rake, i used rails: 'rails g rswag:specs:install' is it the same? And regarding the specs location it's under '/spec' isn't it where it search for?

**Comment by oblakeerickson** [comment]
This is the command to generate the api doc files: `rake rswag:specs:swaggerize` as indicated by [step 4 in the readme](https://github.com/rswag/rswag#getting-started), but `rails rswag:specs:swaggerize`. Also this command will output the location of where the docs are located:

> Swagger doc generated at ...

**Comment by jtannas** [comment]
heyo - new volunteer here helping sort through our issues backlog.
Since this is quite an old issue and there's very little information to go on, I'm going to close it.
If you're still having issues, feel free to make a new issue and we'll be happy to help. Cheers! 🙂
