### ISSUE TITLE
Support for Array of files

### ISSUE THREAD

**Issue by goldendragon1988** [rswag/rswag#367]
Hi,

Is there a support for array of files? 
For a single file it is working great. 

Here is my sample spec.
```
  post 'Creates a product' do
      tags 'Product'
      consumes 'multipart/form-data'
      parameter name: :product, in: :formData, schema: {
        type: :object,
        properties: {
          'product[images][]': { type: :array, items: { type: :string, format: :binary, nullable: true } }
        }
      }
  end
```

![image](https://user-images.githubusercontent.com/12995652/95850043-cbbcf500-0d82-11eb-96db-c2d691949474.png)

![image](https://user-images.githubusercontent.com/12995652/95850560-9d8be500-0d83-11eb-9db7-458cfdb10b76.png)

I also tried `'product[images][]': { type: :array, items: { type: :file nullable: true } }` same result, having `[object File]` in the images column.

Thanks,

**Comment by mdiaz25** [comment]
Hey @goldendragon1988. Could you solve it? I'm having the same issue
