### ISSUE TITLE
Can I split definitions schema to small files then include them to swagger_helper?

### ISSUE THREAD

**Issue by lexuantrung-Peter** [rswag/rswag#368]
As document, I have to declare schema in swagger_helper then reference them in rspec. But too hard to maintain them if I have too much schema in one file. So Can I split them to small files?

**Comment by pernambucano** [comment]
yes! you can store them in the swagger/v1/stuff.yaml path (same lvl as app), for example, and use it in the response like so: 
`
        schema type: :object,
               properties: {
                 data: {
                   '$ref' => 'schema_file.yaml#/Stuff'
                 }
               }
`

**Comment by lexuantrung-Peter** [comment]
> yes! you can store them in the swagger/v1/stuff.yaml path (same lvl as app), for example, and use it in the response like so:
> `schema type: :object, properties: { data: { '$ref' => 'schema_file.yaml#/Stuff' } }`
Thank you!!!
It's work fine!!!
