### ISSUE TITLE
Tests: Fix pending spec on Github Issues

### ISSUE THREAD

**Issue by jamie** [rswag/rswag#370]
There's one spec marked `skip` which depends on headless browser support, which I haven't yet figured out how to properly get running (either locally or on Actions).

**Comment by BookOfGreg** [comment]
So you may discover over time that Google Chrome is a terribly annoying browser. At some point they changed from using [chromedriver to using webdriver](https://github.com/flavorjones/chromedriver-helper), and we had to re-do the headless browser, and that test probably simply never got re-written in the new driver.
For our current purposes it can probably be deleted, re-written, or ignored until later and not worry about it other than the coverage.

**Comment by jamie** [comment]
Yeah, headless browser testing is indeed a pain in the butt :)
