### ISSUE TITLE
Query param `type` key gets overriden between response blocks in single `path`

### ISSUE THREAD

**Issue by kamilsluszniak** [rswag/rswag#374]
Code:

```
path '/dashboard/active_users' do
          get(summary: 'Get active users stats') do
            tags 'Dashboard'
            produces 'application/json'
            parameter name: :project_id, in: :query, type: :string
            parameter name: 'authorization', in: :header, type: :string
            security [JWT: {}]

            response '200', 'success' do
              schema '$ref' => '#/components/schemas/aggregate_response'
              let(:project_id) { project.id }
              let(:auth_headers) { Devise::JWT::TestHelpers.auth_headers({}, user) }
              let(:authorization) { auth_headers['Authorization'] }
              
              run_test! do
                allow(EventReactionLogEntry).to receive(:search) do
                  OpenStruct.new(response: event_reaction_log_entry_test_response)
                end
              end
            end

            response '401', 'unauthorized' do
              schema '$ref' => '#/components/schemas/aggregate_response'
              let(:project_id) { project.id }

              run_test! do
                allow(EventReactionLogEntry).to receive(:search) do
                  OpenStruct.new(response: event_reaction_log_entry_test_response)
                end
              end
            end
          end
        end
```
Issue:

In lib/rswag/specs/request_factory.rb:113
```
112:           parameters.select { |p| p[:in] == :query }.each_with_index do |p, i|
 => 113: 	    binding.pry
    114:             path_template.concat(i.zero? ? '?' : '&')
    115:             path_template.concat(build_query_string_part(p, example.send(p[:name])))
    116:           end
```

`parameters` variable is `[{:name=>:project_id, :in=>:query, :type=>:string}, {:name=>"authorization", :in=>:header, :type=>:string}]` while in `response '200'` block
`parameters` variable is `[{:name=>:project_id, :in=>:query, :schema=>{:type=>:string}}, {:name=>"authorization", :in=>:header, :schema=>{:type=>:string}}]` while in `response '401'` block

This results in:
```
Failure/Error: return "#{name}=#{value}" unless param[:type].to_sym == :array
     
     NoMethodError:
       undefined method `to_sym' for nil:NilClass
```

Need to duplicate the whole `path` block to only define `401` response.

**Comment by quolpr** [comment]
The same issue here.

@kamilsluszniak as a workaround you mentioned, "Need to duplicate the whole path block to only define 401 response.". Am I right, that all `tags`/`produces`/`parameter` need to be duplicated in that new path block too?

**Comment by kamilsluszniak** [comment]
@quolpr Correct, the whole path must be valid with all stuff going on there like there was no path specified before. Looks like docs are generated correctly tho, but examples from readme with one path defined and few response blocks inside doesn't work.

**Comment by phacks** [comment]
I had the same issue, and upgrading to `2.3.3` did the trick. Looks like https://github.com/rswag/rswag/pull/392 fixed it!

**Comment by c100k** [comment]
> I had the same issue, and upgrading to `2.3.3` did the trick. Looks like #392 fixed it!

I confirm with `2.4.0` as well ! So I guess this issue can be closed.
