### ISSUE TITLE
How to change request host?

### ISSUE THREAD

**Issue by slim1979** [rswag/rswag#376]
I have got several microservices in docker-compose. Can I dynamically change host to call each of them? Something like:

```ruby
host: 'myhost.com'
```

**Comment by whyayen** [comment]
@slim1979 I change host not working. But it works after I change the `servers`.

Something like this in `rswag_api.rb`: 
```ruby
c.swagger_filter = lambda do |swagger, env|
	  api_url = "%s://%s" % [
	    env['rack.url_scheme'],
	    env['HTTP_HOST'].sub('docs', 'api')
	  ]
	  swagger['servers'] = [{ url: api_url }]
end
```

**Comment by duychaufit** [comment]
This works in my case:

```
  c.swagger_filter = lambda do |swagger, _|
    swagger['servers'] = [{ 'url' => ENV['API_URL'] }]
  end
```

with `ENV['API_URL']` is your desired url, which is defined in my local env variable file.
