### ISSUE TITLE
Authorization Header is not being sent with request

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rswag/rswag#377]
I've done everything that was shown on the web, to get the authorization header to be included with all API transactions. Nothing seems to work. How do go about doing this?

**provider_forms_spec.rb**

```
RSpec.describe 'api/v1/provider_forms_controller', type: :request do

path '/api/v1/provider_forms' do 
 get 'provider forms' do 
  tags "ProviderForm"
  produces "application/json'
  response "302", "found" do
 let(:Authorization) {"X-User-Username: d...; X-User-Token: .......;"}
 run_test!
   end 
  end
 end
end
```

**Comment by RailsCod3rFuture** [comment]
I'm getting 401 every time I run the spec.

**Comment by RALIST** [comment]
did you try to include security option in example?
something like this:
`security [Bearer: []]`

**Comment by markkvdb** [comment]
It seems that you have an error in the formatting of your Authorization specification. You either have to set the `X-User-Username` and `X-User-Token` or the `Authorization` header. Right now it's a mix of both.
