### ISSUE TITLE
Request examples

### ISSUE THREAD

**Issue by cw6365** [rswag/rswag#380]
Is there a way or fix to add request examples like you can do in Swagger eg.

      requestBody:
        content:
          application/json:     # Media type
            schema:             # Request body contents
              $ref: '#/components/schemas/User'   # Reference to an object
            examples:    # Child of media type
              Jessica:   # Example 1
                value:
                  id: 10
                  name: Jessica Smith
              Ron:       # Example 2
                value:
                  id: 11
                  name: Ron Stewart

**Comment by reiz** [comment]
I have the same question. Would like to add request examples but could not figure out how to do it.

**Comment by oblakeerickson** [comment]
This recent commit https://github.com/rswag/rswag/commit/cbaf6cd3e44c317948520f96abb1e42eb379fef5 fixed support for response examples, but I don't think I've seen any recent commits for request examples. Currently I just include the example field on each individual request param instead of the whole request, but yes, a way to do this for whole request we should add support for.

**Comment by jaydorsey** [comment]
I think this might be related to #444? There's a code example there that might help address this.

**Comment by rgisiger** [comment]
Request examples as implemented by kriston-costa works as expected.
Why not doing a Pull Request for that or adding it directly ?

I vote for it but I have no time to implement this at the moment.

**Comment by seliverstov-maxim** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/4324963/190268355-286312da-ce37-4bf6-ac4d-4ef57155b245.png">
example value looks ugly. Could you fix this please?

**Comment by romanblanco** [comment]
@seliverstov-maxim I think that what you're showing is a style of Swagger UI and is not something to fix in this gem.

**Comment by kstevens715** [comment]
I tested out @romanblanco's PR (#555) in my project and if it gets merged it'll solve this same issue for me.
