### ISSUE TITLE
Validate parameter request schema

### ISSUE THREAD

**Issue by kwent** [rswag/rswag#387]
Hi,

I thought the following line would generate the documentation **AND** perform the **schema validation** but apparently not.

```ruby
parameter name: :new_blog, in: :body, schema: { '$ref' => '#/components/schemas/new_blog' }
```

My workaround is the following

```
parameter name: :new_blog, in: :body, schema: { '$ref' => '#/components/schemas/new_blog' }
...
let(:new_blog) do
  data = {title: 'Hello world'}
  JSON::Validator.validate!({type: 'object', properties: { title: {type: 'string'}}}, data)
  data
end
...
```

Would be nice to have a `validate: true` option in which will do the above thing for us.

```ruby
parameter name: :new_blog, in: :body, schema: { '$ref' => '#/components/schemas/new_blog' }, validate: true
```

Regards

**Comment by oblakeerickson** [comment]
Yes I agree, I'm doing something similar with the more up to date json_schemer gem: https://github.com/davishmcclurg/json_schemer

**Comment by ngouy** [comment]
Agree too, I thought it was working out of the box

Why are we validating the response body against the expected schema, but not the send params against the likely declared schema?

**Comment by smridge** [comment]
Just ran into this as well, really surprising.

**Comment by jtannas** [comment]
heyo - just to confirm I understand correctly: you want RSwag to validate your test parameters before they are submitted to your API? Or am I misunderstanding?

**Comment by jtannas** [comment]
I'm trying to clear out our issue backlog so I'm going to close this issue under the assumption it's covered by our new Wiki: https://github.com/rswag/rswag/wiki/FAQ#why-isnt-rswag-validating-my-submitted-parameters

If I've misunderstood please feel free to open a fresh issue and I'll be happy to help :)
