### ISSUE TITLE
Update endpoint example

### ISSUE THREAD

**Issue by jtmkrueger** [rswag/rswag#389]
The documentation doesn't seem to flesh out how a `put` or `patch` would work. 
I'm struggling to figure out how to correctly structure a `patch` request to get a working `200` test. I have `204` covered now, but I don't fully understand how to set up a put/patch and there's nothing in the docs.
Any help even just pointing to a working example of how it should look, would be awesome.

**Comment by oblakeerickson** [comment]
Just like how the documentation does a `post` request you can substitute it with `put` or `patch`:

```
  path '/blogs' do

    post 'Creates a blog' do
```

```
 path '/blogs/{id}' do

   put 'Updates a blog' do
```

**Comment by jtmkrueger** [comment]
So I already figured this much out. As I stated above, I have a 204 example covered, but can't figure out how to `put` and get a 200.

**Comment by jtmkrueger** [comment]
NM, I figured this out on my end.
