### ISSUE TITLE
Yet another issue where the assets do not load

### ISSUE THREAD

**Issue by unRARed** [rswag/rswag#39]
Commented on a related and [previously closed issue here](https://github.com/domaindrivendev/rswag/issues/30#issuecomment-266929920).

**Comment by CollinGraves** [comment]
@unRARed setting a Rails 5 app to `config.api_only = true` removes your asset pipeline and any pre-compilation from the equation, which is a dependency of rswag's asset structure.

(Just had to figure this out the hard way)

As proof, if you open a console you'll find that:

```
Rails.application.respond_to?(:assets)
```
will return `true`, yet trying to access its value:
```
Rails.application.assets
```
will return `nil`, which will make rswag blow up in the initialization process.

It's also telling that you don't have an `assets` directory in your root, which is what `asset_path` in `rswag/ui/home/index.html.erb` is referencing.

**Comment by scarroll32** [comment]
Should this be closed?

**Comment by CollinGraves** [comment]
Yes.

**Comment by unRARed** [comment]
Sorry, have been busy with other projects and haven't had a chance to revisit this.
