### ISSUE TITLE
Splitting schemas into separate files doesn't generate proper examples

### ISSUE THREAD

**Issue by wujuu** [rswag/rswag#393]
Hey, I have a problem with rswag, specifically with splitting schemas into separate files. I need to do that in order to access them from my API controllers to validate incoming POST payload using JSON::Validator (**unless there is a way to directly access schemas defined in `swagger_helper.rb`** - please let me know if there is). 

I am storing my schemas in `#{Rails.root}/swagger/v1`, in json format. I am referencing them from rspec rswag tests as:
`schema "$ref" => "swagger/v1/service.json"`

Unfortunately, generated Swagger view doesn't show the schemas loaded form files properly:

![Screenshot from 2021-01-29 15-59-13](https://user-images.githubusercontent.com/30239467/106290634-fad07700-624a-11eb-9a18-76e5af288eb1.png)
![Screenshot from 2021-01-29 15-31-08](https://user-images.githubusercontent.com/30239467/106290747-1471be80-624b-11eb-8381-91ead07921eb.png)
![Screenshot from 2021-01-29 15-57-25](https://user-images.githubusercontent.com/30239467/106290501-d5dc0400-624a-11eb-9b81-9f9b61484e6e.png)

Am I doing something wrong or is it a known issue? What is the proper workflow when working with rswag and schemas defined in files other than `swagger_helper.rb`?

**Comment by oblakeerickson** [comment]
You are on the right track. I'm also reading my .json schema files directly into rswag as you are, so likely there is some minor change you will need to make.

I think you will need to parse the json schema files first with something like this inside of your rswag specs:


```
require 'json'

schema(JSON.parse(File.read('swagger/v1/service.json')))

```
