### ISSUE TITLE
Validation for unknown properties is missed

### ISSUE THREAD

**Issue by VitaliiLazebnyi** [rswag/rswag#402]
Spec says:
```
When the test is executed, rswag also validates the actual response code and, where applicable, the response body against the provided JSON Schema.
```

My code:
```
      # schema
      components: {
        schemas: {
          endpoint: {
            type: :object,
            properties: {
              property1: { type: :boolean },
              property2: { type: :string }
            },
            required: %w[property1],
            "dependencies": {
              "property2": ["property1"]
            }
          }
        }
      }

      # spec
      response(200, 'existing records') do
        schema '$ref' => '#/components/schemas/endpoint'

        let(:id) { '1' }

        run_test! 
      end
```

When I pass into response `property3` the test still passes. 👎 
When I remove `property1` - the test fails 👍 
when I pass `property2` without `property1` - the test fails 👍 

So my question is: should I make any additional configuration to make the test fail if passed `property3` (because `property3` absent in schema). Or is it a bug that unknown properties passed without errors?

**Comment by DominikAlberski** [comment]
I maybe wrong here but haw do you validate this in your controller? If controller accepts unknown properties then the test should pass. And from my understanding this schemas in test are just used to generate proper swagger documentation.

**Comment by VitaliiLazebnyi** [comment]
```
I maybe wrong here but haw do you validate this in your controller? If controller accepts unknown properties then the test should pass. And from my understanding this schemas in test are just used to generate proper swagger documentation.
```

Please check [the documentation ](https://github.com/rswag/rswag)?
>>>When the test is executed, rswag also validates the actual response code and, where applicable, **the response body against the provided JSON Schema**.

I don't really understand what is the difference what exactly are my validations in controllers. A schema should validate response automatically according to the doc.
And it does. Except for cases when a service response contains unknown properties. (which are not included in a schema)

**Comment by DominikAlberski** [comment]
Ok I misunderstood you there.

**Comment by DominikAlberski** [comment]
I think I found what a problem could be.  You could try to set in your schema definition `"additionalProperties": false`

**Comment by VitaliiLazebnyi** [comment]
@DominikAlberski 
you are right. It works with `"additionalProperties": false`
I was sure that all checks are done by `rswag` itself. but it looks like I was wrong.

**Comment by jtannas** [comment]
Looks like this issue is resolved so I'm going to close it, but feel free to open another if you'd like any further help. Cheers 🙂
