### ISSUE TITLE
Rswag ignores Webmock stubbed requests

### ISSUE THREAD

**Issue by tonyv** [rswag/rswag#408]
Does webmock work with rswag? I've stubbed some API requests using Webmock in my rswag specs but it seems to be completely ignoring them and instead making real requests

**Comment by oblakeerickson** [comment]
I would like to add better support for webmock and the like, but for now can you see if this vcr example helps?

https://github.com/rswag/rswag/issues/207

**Comment by jaydorsey** [comment]
I've been using webmock and it appears to be working correctly:

```
before do
  WebMock.enable!

  stub_request(:post, 'https://www.google.com').to_return(body: '{"foo":"bar"}')
end

after { WebMock.disable! }
```

Only configuration I have is `require 'webmock/rspec'` in my `spec_helper.rb` file. WebMock 3.13.0

Can you give an example of your configuration (gem version, do you have the require) & an example test?

**Comment by alexeevit** [comment]
Ran into the same issue. I found that if you stub requests outside of `response` block it works fine.

So we've got to change this:
```
response 200, 'Success' do
  before { stub_request(:post, 'https://www.google.com').to_return(body: '{"foo":"bar"}') }
  
  run_test!
end
```

Into this:
```
before { stub_request(:post, 'https://www.google.com').to_return(body: '{"foo":"bar"}') }

response 200, 'Success' do
  run_test!
end
```

And if we want to test it with different responses, we can use contexts:
```
context 'when google responds with 200' do
  before { stub_request(:post, 'https://www.google.com').to_return(body: '{"foo":"bar"}') }

  response 200, 'Success' do
    run_test!
  end
end

context 'when google responds with 422' do
  before { stub_request(:post, 'https://www.google.com').to_return(status: 422) }

  response 422, 'Unprocessable entity' do
    run_test!
  end
end
```
