### ISSUE TITLE
Problem with enabling auto generation examples from responses

### ISSUE THREAD

**Issue by jjercx** [rswag/rswag#412]
I'm using rswag 2.4.0.

I'm doing this in my spec, as [said in the docs](https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses).

```ruby
      response '200', 'Success' do
        let(:first_name) { 'test' }
        let(:last_name) { 'user' }
        let(:email) { 'test@mail.com' }
        let(:password) { 'passw0rd' }
        let(:udid) { '1234' }
        let(:username) { 'user.test' }

        after do |example|
          example.metadata[:response][:content] = {
            'application/json' => {
              example: JSON.parse(response.body, symbolize_names: true)
            }
          }
        end

        run_test!
      end
```

However, it's not generating examples as expected when running `be rspec` or `be rake rswag:specs:swaggerize`, what am I missing?

**Comment by volkov-sergey** [comment]
Hi @jjercx, 

I had the same issue, `SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag` works for me

**Comment by aemadrid** [comment]
adding those ENV vars did not solve the problem for me.  still no working examples.

**Comment by up_the_irons** [comment]
Same for me, adding examples to the response metadata has no effect.

**Comment by descovi** [comment]
Same for me (rswag 2.4).
This is my code

```
path '/api/v1/imgs/' do
    get 'list of images' do
      tags 'Images'
      produces 'application/json'
      response '200', 'ok' do
        after do |example|
          example.metadata[:response][:content] = {
            'application/json' => {
              example: JSON.parse(response.body, symbolize_names: true)
            }
          }
        end
        run_test!
      end
    end
  end
```

This is my output

![Image from swagger with output that seems incomplete](https://user-images.githubusercontent.com/104249/113556557-f6368f00-95fc-11eb-9f02-503c90cf0ddd.png)

**Comment by volkov-sergey** [comment]
@descovi I also added this:

```
config.swagger_format = :yaml

config.after do |example|
  if respond_to?(:response) && response&.body.present?
    example.metadata[:response][:content] = {
      'application/json' => {
        example: JSON.parse(response.body, symbolize_names: true)
      }
    }
  end
end
```

to `spec/swagger_helper.rb`

and it looks like:

![Screenshot 2021-04-05 at 13 24 03](https://user-images.githubusercontent.com/16163520/113564514-33594c00-9612-11eb-8f21-5cf8c31f3c44.png)

**Comment by TyGuy** [comment]
For anyone who still hits this issue and none of these answers work: this slightly different format finally did the trick for me (from the same `after` block in `swagger_helper.rb`):

```ruby
    unless response.body.empty?
      example.metadata[:response][:examples] = {
        'application/json' => JSON.parse(response.body, symbolize_names: true),
      }
    end
```

(rswag 2.3.1)

**Comment by coins-black** [comment]
> I'm using rswag 2.4.0.
> 
> I'm doing this in my spec, as [said in the docs](https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses).
> 
> ```ruby
>       response '200', 'Success' do
>         let(:first_name) { 'test' }
>         let(:last_name) { 'user' }
>         let(:email) { 'test@mail.com' }
>         let(:password) { 'passw0rd' }
>         let(:udid) { '1234' }
>         let(:username) { 'user.test' }
> 
>         after do |example|
>           example.metadata[:response][:content] = {
>             'application/json' => {
>               example: JSON.parse(response.body, symbolize_names: true)
>             }
>           }
>         end
> 
>         run_test!
>       end
> ```
> 
> However, it's not generating examples as expected when running `be rspec` or `be rake rswag:specs:swaggerize`, what am I missing?

Does you solve this problem?

I'm using `rswag (2.4.0)` and face with this issue too

**Comment by coins-black** [comment]
`SWAGGER_DRY_RUN=0 rails rswag:specs:swaggerize` solve this issue

**Comment by jtannas** [comment]
Looks like this issue is pretty old and resolved. If it comes up again I'll put something in the wiki.
