### ISSUE TITLE
[Swagger UI] Disable validation when auth is enabled

### ISSUE THREAD

**Issue by gitjul** [rswag/rswag#414]
I can't find a way of disabling the validator check to get rid of the "INVALID" badge in my deployed applications' Swagger docs.

<img width="117" alt="Screenshot 2021-04-06 at 15 44 19" src="https://user-images.githubusercontent.com/457999/113720828-4beb6400-96ef-11eb-88a4-e3da1bb2de97.png">

`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://example.com/api-docs/swagger.yaml"}]}`

I believe this is because I've got basic authentication turned on, still it would be great to get rid of this badge. I don't think the validation should even be happening at all if basic auth is on.

**Comment by ivanbrennan** [comment]
After some trial and error, I managed to disable validation by adding this to the initializer:
```ruby
  c.config_object["validatorUrl"] = "none"
```
So a complete example would look like:
```ruby
Rswag::Ui.configure do |c|
  c.basic_auth_enabled = true
  c.basic_auth_credentials "username", "password"
  c.config_object["validatorUrl"] = "none"
end
```
I referenced these docs: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
