### ISSUE TITLE
Authorization header is not passed in request 

### ISSUE THREAD

**Issue by Bilal14078** [rswag/rswag#418]
Hi,

I'm unable to pass bearer token as an authorization in request header.

swagger_helper
![image](https://user-images.githubusercontent.com/29977481/115444225-bc38d000-a22d-11eb-9c6b-4fb07d4f18e1.png)

user_spec

![image](https://user-images.githubusercontent.com/29977481/115444330-dc688f00-a22d-11eb-8216-d1c4b84c6249.png)

Please help as soon as possible

**Comment by brunocalmels** [comment]
I'm facing this issue as well.

**Comment by jaydorsey** [comment]
A few things jumped out, comparing your configuration against mine (which works as expected):

Do you have an `openapi` definition in your `swagger_helper.rb` file?

In my examples, which are nearly identical to yours, I'm using `securitySchemes`, not `securityDefinitions`. I also have `openapi: '3.0.1'` defined. The `securitySchemes` is also nested under `components` key

I can't see enough of your config to see if you have that defined but maybe that will work?

Also, my specs use `security [Bearer: []]` (Array, not a Hash)

```
      openapi: '3.0.1',

      servers: [
        {
          url: 'http://localhost:3001/',
          description: 'Local Development'
        }
      ],

      components: {
        securitySchemes: {
          Bearer: {
            description: 'JWT key necessary to use API calls',
            type: :apiKey,
            name: 'Authorization',
            in: :header
          }
        },
        schemas: {
          ...
        }
```

Spec:

```
    delete 'Delete an entry' do
      security [Bearer: []]
```

**Comment by jtannas** [comment]
I'm using a very similar setup to Jay and it's working. 

<details>
<summary>Sample</summary>

```ruby
# swagger_helper.rb definitions
  components: {
    securitySchemes: {
      cookie_auth: {
        type: :apiKey,
        name: 'access_token',
        in: :cookie,
      },
      bearer_auth: {
        type: :http,
        scheme: :bearer,
        bearer_format: :JWT,
      },
    },
  },
```

```ruby
# request spec
RSpec.describe '/examples', type: :request do
  path '/examples' do
    get 'Returns all examples' do
      security [{ bearer_auth: [] }]
      let(:Authorization) { BearerToken.new(resource_owner: admin_user).token }
```


</details>

What version of OpenAPI are you using? The `openapi` key in your swagger definitions will say (eg. `  openapi: '3.0.3'`) There were some changes between v2 and v3 that might be the source of your troubles.
> ## Changes from OpenAPI 2.0
> If you used OpenAPI 2.0 before, here is a summary of changes to help you get started with OpenAPI 3.0:
> - securityDefinitions were renamed to securitySchemes and moved inside components.
> - type: basic was replaced with type: http and scheme: basic.
> - The new type: http is an umbrella type for all HTTP security schemes, including Basic, Bearer and other, and the scheme keyword indicates the scheme type.
> - API keys can now be sent in: cookie.
> - Added support for OpenID Connect Discovery (type: openIdConnect).
> - OAuth 2 security schemes can now define multiple flows.
> - OAuth 2 flows were renamed to match the [OAuth 2 Specification](https://tools.ietf.org/html/rfc6749#section-1.3): accessCode is now authorizationCode, and application is now clientCredentials.
> 
> source: https://swagger.io/docs/specification/authentication/

**Comment by Sagar535** [comment]
@jtannas ,  This particular line `let(:Authorization) { BearerToken.new(resource_owner: admin_user).token }` is not working....

I'm getting error:

```
Failure/Error: let(:Authorization) { BearerToken.new(resource_owner: admin_user).token }
          
          NameError:
            uninitialized constant BearerToken

```

**Comment by jtannas** [comment]
> @jtannas , This particular line `let(:Authorization) { BearerToken.new(resource_owner: admin_user).token }` is not working....
> 
> I'm getting error:
> 
> ```
> Failure/Error: let(:Authorization) { BearerToken.new(resource_owner: admin_user).token }
>           
>           NameError:
>             uninitialized constant BearerToken
> ```

`BearerToken` is just a little OAuth2 test helper class that have in our codebase. It's not something that's generally applicable to RSwag.
