### ISSUE TITLE
Tests pass regardless of schema.

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [rswag/rswag#419]
No matter what I put in the `schema` section in my `response` block my tests always pass.

For example
```ruby
schema type: object,
             properties: {
               nonsense: { type: :string }
             }

             run_test! do |response|
               JSON.parse(response.body) # { id: '', name: '', address: '' }
             end
```

The above schema would pass, i.e. the test doesn't fail due to the response body containing properties that aren't defined in my schema.

I feel like this was failing before, and I haven't changed anything about my `rwag` configuration. Has anyone else encountered similar issues?

**Comment by jaydorsey** [comment]
I see the same behavior locally and from what I recall this is intended; json schema is intentionally lax about certain things:

There are two key pieces that you can change to make this work as expected:

You need to add the required fields:

```
schema type: :object,
             properties: {
               nonsense: { type: :string }
             },
             required: %i[nonsense] 
```

With the above, you'll get an error similar to this:

    Expected response body to match schema: The property '#/' did not contain a required property of 'nonsense' in schema

You can also ensure there are no "extra" keys:

```
schema type: :object,
             properties: {
               nonsense: { type: :string }
             },
             additionalProperties: false,
             required: %i[nonsense] 
```

That will give you something like this (when it fails validation):

    Expected response body to match schema: The property '#/' contains additional properties ["id"] outside of the schema...

For your use case, you want something like this:

```
schema type: :object,
             properties: {
               id: { type: :string },
               name: { type: :string },
               address: { type: :string }
             },
             additionalProperties: false,
             required: %i[id name address] 
```

**Comment by Buzzkill-McSquare** [comment]
Alright, so I need to keep in mind that I'll need to be explicit about the presence of fields. Thanks!
