### ISSUE TITLE
How to mark path parameters as optional?

### ISSUE THREAD

**Issue by cesartalves** [rswag/rswag#421]
Given:

routes.rb:
` put '(/:id)/add_to/:order_number', to: 'my_controller#my_action'`

spec:

```ruby
path '/api/tags/{id}/add_to/{order_number}' do
      parameter name: :id, in: :path, type: :integer, required: false
      parameter name: :order_number, in: :path, type: :string, nullable: false
...
end
```

How do I tell rspec-swag that the id param is optional? 
I've tried both required and nullable with no success.

**Comment by jaydorsey** [comment]
> How do I tell rspec-swag that the id param is optional?

If you omit the `id`, it's technically a different path. Path values are always required.

You can create two separate specs for when the `id` is present:

```ruby
path '/api/tags/{id}/add_to/:order_number' do
end
```

And when it's not present:

```ruby
path '/api/tags/add_to/:order_number' do
end
```

**Comment by cesartalves** [comment]
Got it. Thanks!
