### ISSUE TITLE
Parameters showing up in strange ways

### ISSUE THREAD

**Issue by caj** [rswag/rswag#423]
I have a legacy endpoint (which I cannot change) that I need to write an Rswag specification for.

The endpoint takes a `website_uuid` as a query param and an `email` as a body param.

The test currently looks like this:

```ruby  
  path('/api/leads/request_reset_password') do
    post('request a password reset email') do
      tags 'Leads'
      produces 'application/json'
      consumes 'application/json'

      parameter name: :website_uuid, in: :query, type: :string, description: 'Website UUID'
      parameter name: :email, in: :body,  type: :string, description: 'Email of lead requiring password reset'

      response(204, 'email sent') do

        let(:website_uuid) { website.uuid }
        let(:email) { lead.email }

        describe 'with valid parameters' do
          it 'succeeds' do
            binding.pry
          end
        end
      end
    end
  end
```

when I hit the `binding.pry`, I check my params:

```ruby
[1] pry> response.request.params
=> {
      "_json"=>"nobody@example.com", 
      "website_uuid"=>"f63cdc54-qf02-400e-a96c-5722f7d00fc0", 
      "format"=>:json, 
      "controller"=>"api/leads", 
      "action"=>"request_reset_password", 
      "lead"=>{}
   }
```

Why is the email showing up in this `_json` param?

Where's the `email` param?

Why does an empty `lead` param appear when I didn't specify it?

**Comment by elhowm** [comment]
As I see, this gem requires the way of wrapping everything in objects. So, email could be passed as `{ data: { email: "..." } }` in request body. But just `{ email: "..." }` doesn't work here...
I have the same pain here and have no idea how to handle it.

**Comment by caj** [comment]
@elhowm after messing with this for a while I realized that the required toplevel param doesn't even show up in the generated swagger docs. So even if you need to write it as `{ data: { thing_1: '...', thing_2: '...' } }` to get the specs to work, the generated docs just show `thing_1` and `thing_2` being needed, with no toplevel `data`. So it ended up being a nonissue for me. Hope that's useful to you as well.

**Comment by AlexWayfer** [comment]
I don't understand the approach and would like to hear answers from maintainers. It should not work in this way.

**Comment by BookOfGreg** [comment]
@AlexWayfer what's the problem?

**Comment by AlexWayfer** [comment]
> @AlexWayfer what's the problem?

I've already found the similar open issue: #290
