### ISSUE TITLE
Don't work Validation of incoming parameters (in: :body) in rswag specs (Rails)

### ISSUE THREAD

**Issue by kshnyakin** [rswag/rswag#435]
Hello all!  I have spent a lot of time trying to emplement ability of validation incoming params is rswag specs, my code:
```
# incoming-parameter
params = {
  login: 'www',
  id: 15
}

# test rswag-spec
path '/controller/hello' do
  post('Say Hello!') do
    tags 'users'
      consumes 'application/json'
      produces 'application/json'

      parameter name: :my_params, in: :body, schema: {
        type: :object,
        required: %i[id name],
        properties: {
        id: { type: :string },
        name: { type: :string }
        }
      }  

      response(200, 'successful') do
        # schema '$ref' => '#/components/schemas/UserRegistrationResponse'

        describe 'new user with valid reg_params' do
          let(:my_params) { params }

          run_test! do |response|
            data = JSON.parse(response.body)
            puts "data = #{data}"
          end
        end
     end
  end
end
```
You **expecting** that incoming params won't pass validation, because **id - is an integer**, and **name field is absent**. But that's doesn't matter and test is compliting with success.

Can you say what's wrong with my code an why don't work validation of incoming parameters those declarated in rswag docs?

**Comment by andreylitvinchuk** [comment]
Looks like you try to check that you pass valid parameters from the test. I think it's strange case. 
In addition, if rswag falls in this case, you will not be able to test the processing of the request with invalid params.

**Comment by kshnyakin** [comment]
> Looks like you try to check that you pass valid parameters from the test. I think it's strange case.
> In addition, if rswag falls in this case, you will not be able to test the processing of the request with invalid params.

Hello! Here is a meeting :-)
And what for in rswag there is ability to check parameters by the schema? For viewing that in openapi.json?

**Comment by jtannas** [comment]
heyo - I'm a new volunteer sorting through our issue backlog and came across this.
The reason RSwag isn't failing is that we don't validate params that are being submitted to the API. The reasons are
- We want to be able to submit invalid parameters to the API to ensure it throws the correct error response
- That would just be testing your test code and not the API, so it doesn't add any value

**Comment by jtannas** [comment]
I'm trying to clear out our issue backlog to I'm going to close this ticket under the assumption that it's covered by our new wiki: https://github.com/rswag/rswag/wiki/FAQ#why-isnt-rswag-validating-my-submitted-parameters

If I've misunderstood then please open a new ticket and I'll be happy to help :)
