### ISSUE TITLE
[Doubt] Multiple examples when responses 422

### ISSUE THREAD

**Issue by lucassimon** [rswag/rswag#438]
Hello,

How can I generate a documentation with multiple 422 responses?

Example:

```ruby
response '422', 'invalid request' do
  parameter name: :profile, in: :body, schema: { '$ref' => '#/components/schemas/update_profile' }
  schema '$ref' => '#/components/schemas/profile'
  include_context 'with jwt authentication'

  let(:profile) { attributes_for(:profile, fullname: '') }

  run_test! do |response|
    data = JSON.parse(response.body)
    expect(data['message']).to eq('A validação falhou: Fullname não pode ficar em branco')
  end
end

response '422', 'parameter is missing' do
  parameter name: :profile, in: :body, schema: { '$ref' => '#/components/schemas/update_profile' }
  schema '$ref' => '#/components/schemas/profile'
  include_context 'with jwt authentication'

  let(:profile) { }

  run_test! do |response|
    data = JSON.parse(response.body)

    expect(data['message']).to eq('Parameter is missing')
  end
end

response '422', 'gender with wrong data' do
  parameter name: :profile, in: :body, schema: { '$ref' => '#/components/schemas/update_profile' }
  schema '$ref' => '#/components/schemas/profile'
  include_context 'with jwt authentication'

  let(:profile) { attributes_for(:profile, gender: 'not_specified_wrong') }

  run_test! do |response|
    data = JSON.parse(response.body)

    expect(data['message']).to eq("'not_specified_wrong' is not a valid gender")
  end
end
``` 

And when I ran the `swaggerize` it only takes the last one case test.

![Screenshot from 2021-07-26 11-08-17](https://user-images.githubusercontent.com/355496/127002850-13fb2e21-91e1-472d-87fa-ca2930803997.png)

**Comment by kassi** [comment]
OpenAPI documentation doesn't allow several different entries for the same response code.
However you can add multiple examples for one response.

Unfortunately, rswag doesn't make use of the `examples` key in responses, but generates the singular version `example` from the result.

The way I worked around this is a bit tricky and probably a bit flaky, but as long as you run all the tests when updating the documentation it works.
The key is to "collct" the examples rom your response blocks and manually write the "examples" section.

I usually have my error cases set up as a hash beforehand so I don't have to write the whole response all the time. This gives me the following:

```ruby
# all test cases with different responses for unauthorized
unauthorized_contexts = {
  "without attributes" => {
    params: nil, # <-- used for preparing the operation
    error: "The error description your API returns",
    description: "Some more descriptive text"
  },
  "with invalid email" => {
    params: {
      email: "This is not an email adress",
      password: "something"
    },
    error: "Invalid email adress",
    description: "..."
  }
}
# Var to hold the examples! Not nice, but works
unauthorized_contexts_examples = {}

RSpec.describe "users/sessions", type: request do
  path "/api/users/sign_in" do
    let(:valid_params) { { user: { email: user.email, password: password } } }

    post("Create Session") do
      # handle success case here

      # now handle all cases for unauthorized error
      unauthorized_contexts.each do |key, value|
        context key do
          let(:body) {
            if value.key?(:params)
              value[:params] ? { user: value[:params] } : nil
            else
              valid_params
            end
          }
          let(:headers) { value.key?(:header) ? value[:header] : valid_headers }

          response(401, "Unauthorized.") do
            schema "$ref" => "#/components/schemas/error"

            after do |example|
              # Only add a documented example if this is set. Otherwise you may end up in having duplicated examples in the output
              if value[:description] 
                error_response = JSON.parse(response.body, symbolize_names: true)
                # Add the example for this test to the examples. Key for selection is my error response, so I can easily grab it.
                unauthorized_contexts_examples[error_response[:error].to_s] = {
                  description: value[:description],
                  value: error_response
                }
              end
              Set the examples section manually as rswag doesn't do it, and set it to the current result
              example.metadata[:response][:content] = {
                "application/json" => {
                  examples: unauthorized_contexts_examples
                }
              }
            end

            run_test!
          end
        end
      end
    end
  end
end
```

Example is stripped to minimum to explain what I'm doing (there's valid_headers, headers etc. missing, but you should get the point). The key is that rswag will take the last response object for the same code for the final output and I'm attaching one more example to it on every test case.
This lets you select 401 under responses, and underneath there should be an example selection, showing the possible errors. When you select them you see a description and the example response.

I'm not using swagger-ui but RapiDoc and it looks a bit like this:

<img width="1065" alt="Bildschirmfoto 2022-01-31 um 14 10 10" src="https://user-images.githubusercontent.com/993392/151799368-e56c67a1-450a-4210-aa64-0bacd9c3bb8e.png">
<img width="1061" alt="Bildschirmfoto 2022-01-31 um 14 10 21" src="https://user-images.githubusercontent.com/993392/151799376-dfecdd23-5f2e-43d2-97af-f2f7798edace.png">
<img width="1048" alt="Bildschirmfoto 2022-01-31 um 14 10 30" src="https://user-images.githubusercontent.com/993392/151799383-15b940a7-a8e4-42e0-9364-ec7ca43f7936.png">

**Comment by jtannas** [comment]
Feature added for supporting multiple examples per response in #529; closing
