### ISSUE TITLE
Deprrecation warning from json-schema

### ISSUE THREAD

**Issue by shkrt** [rswag/rswag#44]
`[DEPRECATION NOTICE] The preferred way to extend a Validator is by subclassing, rather than #extend_schema_definition. This method will be removed in version >= 3.`

https://github.com/ruby-json-schema/json-schema/blob/099357540ab40bb611b7e8d767c0d9f39032e4cc/lib/json-schema/schema/validator.rb#L16

**Comment by domaindrivendev** [comment]
Fixed by #47
