### ISSUE TITLE
Referring schema from Remote Reference failed Integration test cases

### ISSUE THREAD

**Issue by ankita-agr** [rswag/rswag#440]
My swagger_helper.rb have below configuration
```
RSpec.configure do |config|
config.swagger_docs = {
components: {
        schemas: {
           api_error: { '$ref': 'api_error.json' }
       }
}
end
```

whereas `api_error.json` file containing json schema below
```
{
  "type": "object",
  "properties": {
    "error": {
      "type": "object",
      "properties": {
        "code": { "type": "integer" },
        "message": { "type": "string" },
        "description": {"type": "string" }
      },
      "required": ["code", "message", "description"]
    }
  },
  "required": ["error"]
}
```
When I am calling `schema "$ref": '#/components/schemas/api_error'` In any of my test cases It is throwing an exception
`Expected response body to match schema: The property '#/' was not a valid schema in schema
`
 Excepted Behaviour is that it should pass the test case as response contain valid JSON that match with content with file but it is failing when I am loading schema from file

**Comment by jtannas** [comment]
Hi @ankita-agr 
`'$ref'` only works for referencing other parts of your current schema, and cannot be used to reference other files.
In order for your `api_error.json` to work, it needs to be loaded into code somewhere and then provided to the schema. The way you have it written is as a simple string.

Something like this might be what you're looking for:

```ruby
error_file = File.read('./api_error.json')
error_definition = JSON.parse(error_file)

RSpec.configure do |config|
	config.swagger_docs = {
		components: {
			schemas: {
				api_error: error_definition,
			}
		}
	}
end
```

**Comment by tambakoo** [comment]
@jtannas what's the limitation here, what help is needed here ?

**Comment by jtannas** [comment]
@tambakoo sorry for the slow reply - I've been concentrating on other things for the last few months
Since there's no follow-up from the author I think we're safe to close this issue now.
I suspect at the time I was thinking of "help wanted" as "the author wants some help".
