### ISSUE TITLE
Ability to make response headers not mandatory

### ISSUE THREAD

**Issue by ffscalco** [rswag/rswag#443]
Hey everyone, 

There is a problem setting some details in the response header.

```ruby
response "200", "ok" do
  header "X-Total-Count", schema: {
    type: :integer,
    example: 100
  }, description: "The total number of the resource"
  header "X-Total-Pages", schema: {
    type: :integer,
    example: 4
  }, description: "The total number of pages of the resource"
  header "X-Previous-Page", schema: {
    type: :integer,
    example: 2
  }, description: "The number of the previous page of the resource"
  schema type: :object, properties: {
    ...
  }
end
```

The header `X-Previous-Page` can be nil (when you're on the first page), however, the spec fails, giving the following error:
```
Rswag::Specs::UnexpectedResponse:
  Expected response header X-Previous-Page to be present
```

I've tried using the `required` option but it doesn't seem to work.

I could solve the problem by giving an empty string instead of nil, however, I think it would be better to not have the header `X-Previous-Page` instead of having it with an empty string.

Thoughts?

**Comment by jtannas** [comment]
I think what you're looking for is `required: false`
eg.
```diff
  header "X-Previous-Page", schema: {
    type: :integer,
+   required: false,
    example: 2,
  }, description: "The number of the previous page of the resource"
  ```

**Comment by lukecivantos** [comment]
Hey there I'm currently running into this issue as well where I'm having trouble with `required` and `nullable`. I just put up a PR here that makes an attempt at resolving the issue: https://github.com/rswag/rswag/pull/527 

Let me know what you think @jtannas 🙂

**Comment by jtannas** [comment]
Oops... I totally misinterpreted this one as being a request header instead of a response header - my bad :bowing_man: 
Thank you for the PR to fix it!

**Comment by jtannas** [comment]
Feature added in #527
