### ISSUE TITLE
Consumes 'application/json' does not parse JSON with `get` requests

### ISSUE THREAD

**Issue by cesartalves** [rswag/rswag#446]
Well, it does work, but the parameters don't get serialized to hash on the controller 😅.
Just changing the type of request from `get` to `put` solves this.

**Comment by rickmax** [comment]
same problem here

**Comment by markkvdb** [comment]
This is expected, right? A `get` request should not have a body request.

**Comment by cesartalves** [comment]
> This is expected, right? A `get` request should not have a body request.

According to the [specification](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3), it seems like it 🤔. But I'm aware that some systems do allow it so I'm not sure. There's an incredibly lengthy discussion about the topic on https://stackoverflow.com/questions/978061/http-get-with-request-body (somebody mentioned that say, Postman and Elasticsearch do allow GET with a body)

I can see that Swagger [does not support it on 3.0](https://swagger.io/docs/specification/describing-request-body/), so I can close this anyway 👍
