### ISSUE TITLE
Code coverage with rswag

### ISSUE THREAD

**Issue by matiaskorhonen** [rswag/rswag#449]
Controller actions tested with Rswag don't seem to count towards code coverage, at least as measured by [SimpleCov](https://github.com/simplecov-ruby/simplecov).

Is this a known issue or is there some fix or workaround for this that I'm missing?

**Comment by jaydorsey** [comment]
I'm using simplecov, my controllers are showing coverage (mixed, not always 100% so not a bug or anything I don't think)

Here's my configuration:

```
# spec/spec_helper.rb

require 'simplecov'

SimpleCov.minimum_coverage 90

SimpleCov.start('rails') do
  enable_coverage :branch
end
```

I run my tests with just `bundle exec rspec`

Example output:

![image](https://user-images.githubusercontent.com/191564/135501784-18fe67ba-81d8-4a3c-937f-b1be9019027f.png)

We don't have any controller specs, only request specs, all using RSwag

Can you share your configuration?

**Comment by matiaskorhonen** [comment]
Sorry, this ended up being an oddity of how SimpleCov was integrated into our project (due to _reasons_).
