### ISSUE TITLE
Examples Generation Fails When Body is Gzip Encoded

### ISSUE THREAD

**Issue by ALockwood** [rswag/rswag#45]
I'm running the master build locally and was having problems getting a simple response body to parse. Some quick troubleshooting confirmed my theory that the response body was gzip encoded when passed to the metadata handler (not sure that's the right term... sorry, ruby noob).

I've come up with a workaround for now and will probably create a helper method to simplify all this, but I thought I'd submit the issue in case you want to address it. I've added comments to the example provided in the readme as well as my hacky temp workaround.

Thanks for the work you've done -- loving the gem! :)

```
after do |example|
                    #puts response.header #shows response is gzip compressed
                    #puts response.body #compressed body
                    #puts ActiveSupport::Gzip.decompress(response.body) #proper JSON body
                    #puts JSON.parse(response.body, symbolize_names: true) #blank
                    #example.metadata[:response][:examples] = { 'application/json' => JSON.parse(response.body, symbolize_names: true) } #fails silently
                    if response['Content-Type'].start_with?('application/json') && response['Content-Encoding'] == 'gzip'
                        example.metadata[:response][:examples] = { 'application/json' => JSON.parse(ActiveSupport::Gzip.decompress(response.body), symbolize_names: true) } #success
                    else
                        example.metadata[:response][:examples] = { 'application/json' => JSON.parse(response.body, symbolize_names: true) }
                    end
                end
```

**Comment by ALockwood** [comment]
FWIW I created an 'rswag_helper' in spec/support  and added `require 'support/rswag_helper'` to swagger_helper.rb:
```
require 'spec_helper'

module RswagHelper
    def add_body(response, example)
        if response['Content-Type'].start_with?('application/json') && response['Content-Encoding'] == 'gzip'
            example.metadata[:response][:examples] = { 'application/json' => JSON.parse(ActiveSupport::Gzip.decompress(response.body), symbolize_names: true) }
        else
            example.metadata[:response][:examples] = { 'application/json' => JSON.parse(response.body, symbolize_names: true) }
        end
    end
end

RSpec.configure do |config|
    config.include RswagHelper
end
```

This makes the example loading as simple as:
```
after do |example|
    add_body(response, example)
end
```

**Comment by dan-ding** [comment]
Could you just not compress the response?
Do you mean you're running production locally? The build/generation should be fine to run where ever.
I don't think that the rswag tests should be run on production, regardless of the location. The generation can be, it's not actually running tests, so there aren't any responses for it to parse.

**Comment by ALockwood** [comment]
Yes, I ultimately ended up having to turn off compression because it was also causing problems with validation parsing. I was running in local dev but had configured it to use compression just to keep things as similar to staging/prod as possible. It's helpful for finding little things like this ;)
I had/have no intention of ever running this in production, but I was thinking of having the tests run as part of a build/test/CI process and again would have had compression turned on in that environment config.

**Comment by ALockwood** [comment]
I'm going to close this issue given that there are other problems when compression is enabled. If I ever get the time maybe I'll try to create a PR that would enable compatibility with compression, but truthfully that's probably still pretty far out of my skill set with ruby/rails now.
