### ISSUE TITLE
Rswag doesn't recognise parametes. It says "No parameters"

### ISSUE THREAD

**Issue by SteveRedka** [rswag/rswag#454]
When I generate specs with rswag gem, it says that there are **No parameters** required for this route. 

Here is an example:

```ruby
    post('create tracker') do
      tags 'tracker'
      consumes 'application/json'
      parameter name: :tracker, in: :body, schema: {
        type: :object,
        properties: {
          gps_id: { type: :string },
          driver_initials: { type: :string },
          vehicle_registration_id: { type: :string }
        },
        required: ['gps_id', 'driver_initials', 'vehicle_registration_id']
      }
      response '201', 'tracker created' do
        let(:tracker) { { gps_id: 'foo', driver_itinials: 'bar', vehicle_registration_id: 'KR123A' } }
        run_test!
      end
    end
```
Result:

[![Screenshot-2021-10-25-Swagger-UI.png](https://i.postimg.cc/sXwqL2yX/Screenshot-2021-10-25-Swagger-UI.png)](https://postimg.cc/G8TX8d4w)

  rswag-api 2.4.0
  rswag-specs 2.4.0
  rswag-ui 2.4.0

**Comment by jtannas** [comment]
Looks like you're missing `required: true` in your body parameter definition. The way you have it written all the properties of `body` are required, but the `body` itself is optional.

Does this change solve your problem?

```diff
    post('create tracker') do
      tags 'tracker'
      consumes 'application/json'
-     parameter name: :tracker, in: :body, schema: {
+     parameter name: :tracker, in: :body, required: true, schema: {
        type: :object,
        properties: {
          gps_id: { type: :string },
          driver_initials: { type: :string },
          vehicle_registration_id: { type: :string }
        },
        required: ['gps_id', 'driver_initials', 'vehicle_registration_id']
      }
      response '201', 'tracker created' do
        let(:tracker) { { gps_id: 'foo', driver_itinials: 'bar', vehicle_registration_id: 'KR123A' } }
        run_test!
      end
    end
 ```

**Comment by dollerbill** [comment]
> Looks like you're missing `required: true` in your body parameter definition

@jtannas I added `required: true` like you mentioned but the only change is now I see that the entire body is required but still no individual parameters. 

```
      parameter name: :order, in: :body, required: true, schema: { '$ref' => '#/components/schemas/order' }
```
![Screen Shot 2022-03-04 at 4 21 11 PM](https://user-images.githubusercontent.com/11497835/156858892-77eb7fd2-ce49-4d1b-b4ff-073ed49d5224.png)


Based on my tests that have a parameter in the path vs the body it seems like only path attributes are listed as parameters?

![Screen Shot 2022-03-04 at 4 29 07 PM](https://user-images.githubusercontent.com/11497835/156859303-e14f3d1c-5a67-4425-aa00-8b45317213b0.png)


All gems on 2.5.1

**Comment by jtannas** [comment]
> Based on my tests that have a parameter in the path vs the body it seems like only path attributes are listed as parameters?

I think just path parameters, query parameters, and header parameters will show up in there. The body itself shows up in the request body section.

**Comment by dollerbill** [comment]
> I think just path parameters, query parameters, and header parameters will show up in there. The body itself shows up in the request body section.

Ok, I must have misread your previous reply. This is the behavior I'm currently seeing so seems like everything is working as expected. Thanks!

**Comment by jtannas** [comment]
Happy to help :)
