### ISSUE TITLE
Multiple Consumes Kind And Schema References

### ISSUE THREAD

**Issue by MatthewKennedy** [rswag/rswag#458]
Is it possible to document two or more different consumes kinds for one endpoint? 

For example I might have a resource that has several fields I want to update via `application/json`, but then this same resource and same endpoint I might also allow uploaded images, these ideally want to be documented as `multipart/form-data`.

Do you have any way to pass different `consumes` and parameters for the one `patch` request.

**Comment by romanblanco** [comment]
@MatthewKennedy, you should be able to describe diferent mime-types under `content` key. This should give you a drop-down like this:

![image](https://user-images.githubusercontent.com/1187051/193354238-0e29df1d-b8a3-43b3-9d5e-337934465b92.png)
