### ISSUE TITLE
Multiple response examples not supported

### ISSUE THREAD

**Issue by coolprobn** [rswag/rswag#460]
I researched for a way to generate multiple response example and after digging a bit in the source code, I think this is not supported yet.

If there is a way to do this, your help is very much appreciated.

If this is not supported yet, I would like to work on this if someone provides me pointers on right direction. I will need help on writing tests though, I am not much proficient with it 😅 

Feature
---

In OpenAPI 3.0 multiple response example is supported like the following:

![Multiple response examples](https://user-images.githubusercontent.com/15196941/140861061-5d3df22a-4546-4f93-92b7-95872aa104a5.png)

Current Implementation and UI
---

Code:

```
response '200', 'Array of contacts' do
          examples 'application/json' => {
            all: {
              value: [
                {
                  id: 1,
                  cell_number: '9849247889',
                  asterisk_custom_extension_id: 12,
                  pbx_id: 12,
                  name: 'Support'
                },
                {
                  id: 2,
                  default_cell_number: '9849247889',
                  name: 'John Doe',
                  status: 'active',
                }
              ] },
            shared: {
              value: [
                {
                  id: 1,
                  cell_number: '9849247889',
                  asterisk_custom_extension_id: 12,
                  pbx_id: 12,
                  name: 'Support'
                }] },
            colleagues: {
              value: [
                {
                  id: 2,
                  default_cell_number: '9849247889',
                  name: 'John Doe',
                  status: 'active',
                }] }
          }

          run_test!
```

Generates following yaml:

```
responses:
        '200':
          description: Array of contacts
          content:
            application/json:
              example:
                all:
                  value:
                  - id: 1
                    cell_number: '9849247889'
                    asterisk_custom_extension_id: 12
                    pbx_id: 12
                    name: Support
                  - id: 2
                    default_cell_number: '9849247889'
                    name: John Doe
                    status: active
                shared:
                  value:
                  - id: 1
                    cell_number: '9849247889'
                    asterisk_custom_extension_id: 12
                    pbx_id: 12
                    name: Support
                colleagues:
                  value:
                  - id: 2
                    default_cell_number: '9849247889'
                    name: John Doe
                    status: active
```

UI looks like this with the above code:

![Multiple examples doesn't generate dropdown](https://user-images.githubusercontent.com/15196941/140861413-041e9637-d5cf-4f9a-b67f-593fb5d67daa.png)

Issue
---

Issue is that it doesn't generate dropdown to choose/toggle response example depending on the key (or type)

Multiple response examples
---

If I change `example` to **examples** in yaml file then multiple response examples are generated

yaml after change:

```
responses:
        '200':
          description: Array of contacts
          content:
            application/json:
              # changed just this
              examples:
                all:
                  value:
                  - id: 1
                    cell_number: '9849247889'
                    asterisk_custom_extension_id: 12
                    pbx_id: 12
                    name: Support
                  - id: 2
                    default_cell_number: '9849247889'
                    name: John Doe
                    status: active
                shared:
                  value:
                  - id: 1
                    cell_number: '9849247889'
                    asterisk_custom_extension_id: 12
                    pbx_id: 12
                    name: Support
                colleagues:
                  value:
                  - id: 2
                    default_cell_number: '9849247889'
                    name: John Doe
                    status: active
```

Will generate UI with dropdown options for toggling between responses:

![With the change in key example to examples dropdown is generated in UI](https://user-images.githubusercontent.com/15196941/140861947-4b1d1fe6-bcd7-414a-b660-9a1d2bfe364d.png)

Code that generates response example
---

I think this is the code that is being used to generate examples and it's always assigned to `example`. If we also had option to make it plural for supporting multiple examples then it would be awesome.

![Ruby code that is generating examples is always assigning examples to example key which seems to be the issue](https://user-images.githubusercontent.com/15196941/140860898-e1f66cc6-c0c2-44a1-a379-1cc0fd30e158.png)

**Comment by oblakeerickson** [comment]
Hey thanks for writing this up! I believe you are correct that rswag only allows for one example right now. It looks like you are on the right track with the code for adding support for multiple examples. So, yes, if this is a feature you'd like to have and want to work on it please do :) Start by making a PR when you get a chance and I can review it and help out with some tests.

**Comment by coolprobn** [comment]
Sure, I will work on this and create a PR as soon as I complete it, probably by next week.

**Comment by sergioisidoro** [comment]
Please note that there are a already 2 PRs attempting to address this issue since Apr 2020

https://github.com/rswag/rswag/pull/305
https://github.com/rswag/rswag/pull/302

**Comment by coolprobn** [comment]
> Please note that there are a already 2 PRs attempting to address this issue since Apr 2020
> 
> #305 #302

I didn't get to work on it and turns out that happened for the good.

Thanks for mentioning it here, I should do better to check up existing PRs. I only had checked issues.

I will close the issue in favor of those PRs and instead see if I can help in any one of them so we have this feature.

**Comment by sergioisidoro** [comment]
Glad we were in time to avoid duplicate work :)
Feel free to participate in those discussions to try and push them forward 👍
