### ISSUE TITLE
Can I augment the request made to the /authorization endpoint?

### ISSUE THREAD

**Issue by stevehobbsdev** [rswag/rswag#462]
I'm using the `:openIdConnect` security scheme but would like to somehow hook into that request in order to add a custom query parameter - is that possible with rswag currently?

For context, the IdP I'm using accepts an `audience` query param that affects the format of the returned Access Token, so I would like to specify what that `audience` value is.

**Comment by oblakeerickson** [comment]
I'm not sure if rswag has support for the query params or not in the security scheme. But I'm also not sure if the OAS has support for it either? 

From the OpenId Section in 
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#securitySchemeObject

it has: 

openIdConnectUrl | string | openIdConnect | REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL.
-- | -- | -- | --

So maybe you can just put the query param in the URL?

**Comment by stevehobbsdev** [comment]
It's a nice idea. Unfortunately that URL is not the one I need to modify. That's a configuration discovery document that _contains_ the URL I need to modify. There will be something that downloads it, finds the URL for the authorization endpoint and then invokes it with some params, and I would like to be able to tack my own params onto that if possible.

It's a good point though, this feels less and less like an rswag problem and more like something that would have to be exposed elsewhere in the Swagger ecosystem. Thanks for your help!

**Comment by stevehobbsdev** [comment]
In case anyone stumble across this, I got this working without any real hackery.

Swagger UI has some config where you can specify things like the client ID, client secret etc through some config specified when initializing Swagger in JavaScript (see [OAuth2 config](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/)). There is an option to specify custom additional params for the authorization and token endpoint URLs.

It's not documented (maybe it should be?), but `rswag` allows you to set this config in the `rswag-ui` initializer, which is then [passed through in the template to Swagger UI](https://github.com/rswag/rswag/blob/095906da5881cd36480d0a2acf04893d59a9d117/rswag-ui/lib/rswag/ui/index.erb#L83).

So in order to pass through an `audience` parameter to my IdP when authenticating in Swagger, I can specify some config in the initializer like this:

```ruby
Rswag::Ui.configure do |c|

  # List the Swagger endpoints that you want to be documented through the swagger-ui
  # The first parameter is the path (absolute or relative to the UI host) to the corresponding
  # endpoint and the second is a title that will be displayed in the document selector
  # NOTE: If you're using rspec-api to expose Swagger files (under swagger_root) as JSON or YAML endpoints,
  # then the list below should correspond to the relative paths for those endpoints

  c.swagger_endpoint '/api-docs/v1/swagger.yaml', 'API V1 Docs'

  # Add Basic Auth in case your API is private
  # c.basic_auth_enabled = true
  # c.basic_auth_credentials 'username', 'password'

  # Configure IdP for logging in through the Swagger UI
  c.oauth_config_object = {
    clientId: AuthConfig.client_id,
    clientSecret: AuthConfig.client_secret,
    additionalQueryStringParams: {
      audience: AuthConfig.api_identifier
    },
    usePkceWithAuthorizationCodeGrant: true
  }
end
```

Should be noted that while my original issue was raised in the context of using the OpenIDConnect scheme, I am using the OAuth2 scheme here.
