### ISSUE TITLE
Support of Rails 7

### ISSUE THREAD

**Issue by manaka** [rswag/rswag#465]
subject says it all

**Comment by edimossilva** [comment]
yep, can I try to create a PR for it?

**Comment by helmiattastify** [comment]
@edimossilva thanks!!!

**Comment by edimossilva** [comment]
Guys, looks like using `gem 'rswag', git: 'https://github.com/rswag/rswag.git', branch: 'master'` instead of `gem 'rswag'` at the Gemfile solves the issue

**Comment by BookOfGreg** [comment]
Yep, merged it a few days back. Master supports Rails 7

**Comment by jlestavel** [comment]
> Yep, merged it a few days back. Master supports Rails 7

Is it possible to have a new release of the gem please 🙏  ?

**Comment by joelbiffin** [comment]
Is there anything I can do to help with preparing a release of the Gem?  It looks like Github actions are failing on master due to failing dependency installs. It would be great to help everyone move over to Rails 7 🙂 @BookOfGreg

**Comment by jscharf** [comment]
Lots of discussion happening on this issue https://github.com/rswag/rswag/issues/468 for those hoping for a release.

**Comment by BookOfGreg** [comment]
Yep. We're trying.

**Comment by jscharf** [comment]
@BookOfGreg thank you to you and others for your hard work and diligence in getting this release out!

We are proceeding with our Rails 7 upgrade and this is a huge help 👏
