### ISSUE TITLE
nil is not a symbol nor a string

### ISSUE THREAD

**Issue by paulomcnally** [rswag/rswag#474]
rswag-specs: 2.4.0

```
parameter in: :body, schema: {
        type: :object,
        properties: {
          payment_id: { type: :integer, description: 'Payment.id' },
        },
        required: [ 'payment_id' ]
      }
```

This code work fine on documentation (`/api-docs`), but on test have this error:

```
 nil is not a symbol nor a string
```

File on gem rswag/specs/request_factory.rb

**Comment by jtannas** [comment]
Hi Paulo,
Could you please include the full stack trace of the error so we can see where it's coming from?

**Comment by paulomcnally** [comment]
Ok. Tomorrow at 8am when Open the project.

**Comment by jtannas** [comment]
@paulomcnally any updates on this?
