### ISSUE TITLE
Send the header values in request

### ISSUE THREAD

**Issue by Manidavid** [rswag/rswag#48]
not able to pass the header values in the spec, please help to send the values in the headers
example:

```
require 'swagger_helper'
describe 'Test API' do
  path '/api/v1/visit/{id}' do
    before { header "X-Token", 'api_key' }
     get "visiting information" do
      tags 'Page'
      produces 'application/json'
      parameter name: :id, :in => :path, :type => :string      
      # before do
      #   header "X-Token", 'api_key'
      # end
      response '200', 'success'  do
        let(:id) { 1 }
        run_test!
      end
  end
end
```

giving the blow error when i run the above integration spec.

  `header` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).

**Comment by domaindrivendev** [comment]
Headers are just another type of parameter. Like all parameters you set their value for an example with the let syntax:

**Comment by domaindrivendev** [comment]
Sorry closed accidentally. You can use the "let" syntax as follows:

    let(:'X-Token') { 'some value' }

**Comment by Manidavid** [comment]
`let(:'X-Token') { 'some value' }` this let parameter value is not able to fetch in request headers.
`request.headers["X-Token"]`  - returns nil instead of token passed.

It would be great help if you could add more clarification or examples.

**Comment by domaindrivendev** [comment]
Agreed - the docs could definitely be more in depth. Then again, the provided DSL is 100% based on the [Swagger Specification](http://swagger.io/specification/) and a basic understanding of that is kind of assumed for users of this library. Perhaps when I get some free time, I could add more thorough docs. Or better still, users who figure this stuff out would contribute back via PR's to update the readme :)

Anyway, back to your problem. As per the Swagger spec - you specify input to an operation as a list of "parameter" objects. In each case, you describe the parameter location with the "in" field which can have any one of the following values: "path", "query", "header", "body" or "form". So, in your case you need to start by specifying that your operation expects a header parameter in addition to the id parameter. Then for a given example, you set the value of that parameter via the let syntax:

```ruby
path '/api/v1/visit/{id}' do
  get "visiting information" do
    tags 'Page'
    produces 'application/json'
    parameter name: :id, :in => :path, :type => :string
    parameter name: 'X-Token', :in => :header, :type => :string

    response '200', 'success'  do
      let(:id) { 1 }
      let(:'X-Token') { 'some value' }
      run_test!
    end
  end
end
```

**Comment by Manidavid** [comment]
Thanks it works :+1:

Please add more examples with usage of integration specs so that users could easily understand the implementation without digging into the [Swagger Specification](http://swagger.io/specification/) docs.

**Comment by moserke** [comment]
Though this does work to pass in the headers for tokens, this is cumbersome because these headers are really securityDefinitions.  Is there a way to pass in these values without having to re-define the parameter on every endpoint which only serves to clutter and confuse the UI because it's already defined as a securityDefinition.

**Comment by rociiu** [comment]
Same situation here, is there anyway to add this kind of token in one place, tried to add parameters in global meta, seems not work.

**Comment by pbelouin-mpiwg** [comment]
I'm actually still struggling to manage to get the Accept header to be set properly - I use it as a routing constraint for versionning - here's what I've tried so far:
parameter name: 'Accept', in: :header, type: :string
and then
let(:'Accept') { 'application/vnd.rise_api.v1' }

but it doesn't route properly - If I could get access to the request object I could probably debug it, but I'm not sure how to do this... In addition I've also tried to setup the "consumes" value but to no avail. neither... Anybody has any idea perhaps? thanks a lot in advance!

**Comment by pbelouin-mpiwg** [comment]
mmmh I think I got a bit mixed up and the error is probably coming from configuration errors in my constraints

**Comment by radubogdan** [comment]
What's the status with this one? Is there a better way to set auth headers like (client, uid, access-token) for all the requests made before execution of each test?

**Comment by SampsonCrowley** [comment]
this is a VERY obscure way of passing data... there should be a way to pass parameters directly to the request without requiring let definitions

**Comment by kinsomicrote** [comment]
Posting this in case anyone has an idea of what I could be missing (and if there's now an improved means of passing parameters directly for requests).
I have this;
```
path '/api/v1/posts', as: :json do
  get 'Retrieves all incomes' do
    tags 'Incomes'
    produces 'application/json'
    parameter name: :uid, in: :header, type: :string
    parameter name: :client, in: :header, type: :string
    parameter name: :'access-token', in: :header, type: :string
    parameter name: :expiry, in: :header, type: :string

    response '200', 'posts found' do

      run_test! do |response|
        let(:uid) { @headers['uid'] }
        let(:client) { @headers['client'] }
        let(:access_token) { @headers['access-token'] }
        let(:expiry) { @headers['expiry'] }
        data = JSON.parse(response.body)
        expect(data.length).to eq(1)
      end
    end
  end
end
```
And I get this error;
```
NoMethodError:
       undefined method `uid' for #<RSpec::ExampleGroups
```
