### ISSUE TITLE
Rails 7.x release?

### ISSUE THREAD

**Issue by pedrofurtado** [rswag/rswag#480]
Is there any plans to release an official release with Rails 7.x compatibility?

Thanks a lot! 🤝 🍻

**Comment by wheatevo** [comment]
Looks like this is resolved in master on https://github.com/rswag/rswag/issues/465 and a new release will need to be performed.

Other related PRs:
https://github.com/rswag/rswag/pull/477
https://github.com/rswag/rswag/pull/481

**Comment by sergioisidoro** [comment]
@wheatevo yes. Me and @BookOfGreg are making sure the testing and CI are reliable with Rails 7, and we'll make a release hopefully quite soon.

**Comment by BookOfGreg** [comment]
This should now be done. Let us know if any issues on Rails 7.0.x are discovered!
