### ISSUE TITLE
v2.5.0: Static `swagger-ui` assets 404ing

### ISSUE THREAD

**Issue by jtannas** [rswag/rswag#489]
![image](https://user-images.githubusercontent.com/22785056/153106037-797f1451-e22f-455b-98c7-b616bb52db40.png)

## Version Information
gem: 2.5.0
ruby: 3.0.3
rails: 6.1.4.4

## Notes
- bug not present in ~v2.3.2~ v2.4.0 of the gem
- possibly related to #469
- currently investigating; suspect it's something to do with the bundling of `swagger-ui` assets

**Comment by BookOfGreg** [comment]
> bug not present in v2.3.2 v2.4.0 of the gem

That was a risk. Guess we have our 2.5.1 candidate, do we have a clue as to what's the cause?

**Comment by jtannas** [comment]
> do we have a clue as to what's the cause?

Not yet; I got sidetracked last night with a plumbing mishap before I could narrow it down. I'll keep looking ~later today~ tomorrow (forgot I had a prior commitment and was away from my dev machine).

**Comment by BookOfGreg** [comment]
Linked 467 which appears to link the issue to node-modules missing due to a change of build process.

**Comment by BookOfGreg** [comment]
Should be fixed in 2.5.1
