### ISSUE TITLE
Maintainer Tooling Discussion

### ISSUE THREAD

**Issue by jtannas** [rswag/rswag#490]
Making a thread here for discussing different things we can do to make maintaining the project less time consuming.

Ideas:
- Add a `SECURITY.md` file for reporting vulnerabilities to head off tickets like #135
- Add a `rubocop.yml` to keep everyone on the same page for project styling; lint & autocorrect PRs
- Add in spellchecker ([cspell](https://cspell.org/)?) for PRs
- Add https://github.com/marketplace/stale to help keep stale issues under control
- Are the issue templates working? I don't see anything come up when creating a new template. Assuming they're broken:
  - Add in a template chooser https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
  - Create issue forms (or wait until beta is complete?) https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
- Set up a project wiki with an FAQ page; Split the README into wiki pages
- Set up GitHub Discussions so that we can focus the "Issues" section on concrete issues
- ???

**Comment by BookOfGreg** [comment]
- [x]  #491  - We need to discuss the content of this file, generally it's expected that there's an email to handle this privately, however given the length of time it took me to get back in the game, what kind of guaranteed can we make?

**Comment by BookOfGreg** [comment]
- [x] #492 - This one should be fairly straight forward. Stale is pretty sensible to me, shame to loose people's good content but there is a limit of what's useful and what will reasonably be gotten to. Discuss in the PR thresholds and message.

**Comment by BookOfGreg** [comment]
- [x] I've made a discussion section. I've never used one before but happy for others to do so. Hopefully this will help us make and keep this a vibrant place.

You can find it here: https://github.com/rswag/rswag/discussions

**Comment by jtannas** [comment]
Thoughts on opening up a wiki?
I'm seeing some common threads in the tickets that would fit well into an FAQ section.
- How can split my `swagger_helper` definitions across multiple files?
- Why is this test passing when there are additional properties?
- Why is this test passing when there are missing properties?
- https://github.com/rswag/rswag/issues/256

They could go into the README but it's getting pretty unwieldy with how long it is

**Comment by jtannas** [comment]
Related: can I please get a `documentation` label for keeping track of things to add to an FAQ?
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label

**Comment by BookOfGreg** [comment]
Slowly working through these suggestions, hope you don't mind my pace, you seem to be tracking a little faster than I am :laughing: . Do you have any thoughts on a good async communication tool? Team discussions in the org might do it but not used that before either.
Edit: Think at one point @sergioisidoro mentioned about slack or discord, hope I'm not mis-remembering, have a preference?

**Comment by BookOfGreg** [comment]
I think you should have permission to open a Wiki up yourself. The Org settings don't restrict it as far as I can tell but please correct me if I'm wrong there.

I do wonder if the content is better as a GitHub page, I've seen a number of other repos have good GH Pages content for their documentation so I would think that might be the better kind of content, trouble is that needs write access and fairly high-quality content. Wiki or GH Pages?

**Comment by BookOfGreg** [comment]
Finally got around to making a very basic logo. Anyone who is a designer PLEASE SEND HELP. In the meantime I hope this is OK. 
![rswag logo](https://user-images.githubusercontent.com/637868/153675174-93144b1e-f4c7-4f5a-83b9-a850a3769244.png)

Edit: as you might be able to tell, I am not a professional graphic designer and should never be allowed near the front-end.

**Comment by jtannas** [comment]
> I think you should have permission to open a Wiki up yourself. The Org settings don't restrict it as far as I can tell but please correct me if I'm wrong there.

I'd need access to https://github.com/rswag/rswag/settings to enable that feature and it's 404'ing me so it needs more access than I have.
 
> I do wonder if the content is better as a GitHub page, I've seen a number of other repos have good GH Pages content for their documentation so I would think that might be the better kind of content, trouble is that needs write access and fairly high-quality content. Wiki or GH Pages?

GitHub pages are nicer bit Wiki is much less work. My priority right now is to get caught up on the backlog, so I lean towards Wiki to start. Pages can come later when there's more free time & energy.

**Comment by jtannas** [comment]
> Finally got around to making a very basic logo. Anyone who is a designer PLEASE SEND HELP. In the meantime I hope this is OK.

Very slick looking - definitely a lot better than anything I could manage so let's go with it.
For a future revision, I think something that melds in the swagger logo would be nice. eg.
![image](https://user-images.githubusercontent.com/22785056/153696888-89b39574-b144-4b25-abb2-5f6b64c64ff3.png)
Sorry about all the JsPaint artifacting 😅

**Comment by jtannas** [comment]
> Do you have any thoughts on a good async communication tool? Team discussions in the org might do it but not used that before either.

Let's try moving this to Discussions and see how it works out - could help out people who want to contribute by having everything out in the open.
