### ISSUE TITLE
Feature: Raise custom error for required params

### ISSUE THREAD

**Issue by BookOfGreg** [rswag/rswag#497]
I like it! I've definiely chased that wild goose a couple times and this would've saved a ton of time :swan: 
This is also applicable to query parameters with `required: true` if you feel like extending the PR a bit. If not we can just merge as-is.

_Originally posted by @jtannas in https://github.com/rswag/rswag/issues/455#issuecomment-1037579628_

**Comment by romanblanco** [comment]
@BookOfGreg, could we keep this one open to keep track of it for future?
