### ISSUE TITLE
[BUG] Rswag failed to parse json body in GET method

### ISSUE THREAD

**Issue by nolan23** [rswag/rswag#509]
## Describe the bug
If we use GET method in rswag and we also add parameter body, the parameter that we send is not properly parsed in controller

## Steps to Test or Reproduce
given this code:
```ruby
get('product_unit_conversions product_unit') do
      parameter name: :param, in: :body, schema: {
        type: :object,
        properties: {
          product_id:{
            type: :integer
          }
        }
      }
      response(200, 'successful') do
        let(:param){{product_id: product.id}}
        after do |example|
          example.metadata[:response][:content] = {
            'application/json' => {
              example: JSON.parse(response.body, symbolize_names: true)
            }
          }
        end
        before do |example|
          submit_request(example.metadata)
        end

        it 'returns a valid 200 response' do |example|
          assert_response_matches_metadata(example.metadata)
        end
      end
    end
```

but in controller, the product_id is not properly parsed. here is the param log
```json
{"{\"product_id\":1}":null,"format":"json","controller":"api/product_units","action":"product_unit_conversions","product_unit":{}}
```

as you can see the product_id parsed into `"{\"product_id\":1}":null`

## Expected behavior
If the body properly parsed then it should be parsed like this:
```json
{"product_id":1,"format":"json","controller":"api/product_units","action":"product_unit_conversions","product_unit":{}}
```

## Screenshots
-

## Additional context
- 

## Rswag Version
`v2.5.1`

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by JSimon14** [comment]
I'm seeing this same bug. Hopefully it gets sorted out soon.

**Comment by kstevens715** [comment]
I would also like to be able to send request bodies with a `GET` request. Unfortunately, I don't know if this is going to be supported. A similar issue (#446) was previously closed because [OpenAPI 3.0 does not support bodies with GET requests](https://swagger.io/docs/specification/describing-request-body/):

> GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3).

**Comment by PavloBezpalov** [comment]
This is my patch.

```ruby
module Rswag
  module Specs
    class RequestFactory
      private

      def add_payload(request, parameters, example)
        content_type = request[:headers]['CONTENT_TYPE']
        return if content_type.nil?

        request[:payload] =
          if ['application/x-www-form-urlencoded', 'multipart/form-data'].include?(content_type)
            build_form_payload(parameters, example)
          elsif request[:verb] == :get
            build_hash_payload(parameters, example)
          else
            build_json_payload(parameters, example)
          end
      end

      def build_hash_payload(parameters, example)
        body_param = parameters.select { |p| p[:in] == :body }.first

        return nil unless body_param

        raise(MissingParameterError, body_param[:name]) unless example.respond_to?(body_param[:name])

        example.send(body_param[:name])
      end
    end
  end
end
```

**Comment by jtannas** [comment]
Looking at the link Kyle provided, it does seem like something outside of OAS3 so I don't think we'll be officially adding support for this. An entry into the wiki describing the situation and including your patch seems like it'd be a good compromise though.
