### ISSUE TITLE
 Disable sending root params

### ISSUE THREAD

**Issue by igorgesso** [rswag/rswag#510]
## Is your feature request related to a problem? Please describe.

Is there a way to disable swag from sending root params.
Ex: I have a Billet model and a BillerController controller.
If I try to send
```
{ abc: 1234 , xyz: "test"}
```

Rswag automatically sends root params 
```
{ abc: 1234, xyz: "test", billet: {abc: 1234, xyz: "test" } }
```

## Describe the solution you'd like

I would like to disable this behavior like this
config.send_root_params = false

## What support could we give you, so you could implement this yourself?

My mastery level is low but if you give me a light on how to implement this, I would like to do so in order to learn more.

## Describe alternatives you've considered

I looked in all the documentation, I looked on the internet for examples, I looked in the issues for something like that and I only saw that it seems to be a pattern of rswag behavior

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [x] OAS3
- [ ] OAS3.1

**Comment by dce** [comment]
It is possible that it's Rails doing this, not rswag: https://edgeapi.rubyonrails.org/classes/ActionController/ParamsWrapper.html
