### ISSUE TITLE
[REQUEST] CVE GHSA-qrmm-w75w-3wpx has been discovered in rswag gem.

### ISSUE THREAD

**Issue by venkikg** [rswag/rswag#514]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
CVE GHSA-qrmm-w75w-3wpx is showing up in rswag gem, but there are no possible solutions online. I updated the gem version to the most recent, 2.5, but the CVE remains in the report. So, could you please assist me in resolving this issue as soon as possible?

## Describe the solution you'd like
A possible workaround for GHSA-qrmm-w75w-3wpx in the rswag gem.

## What support could we give you, so you could implement this yourself?
Please tell us how could we help you implement this feature, so you could 
become a contributor. **Our time is limited, so it's unlikely that we will
be able to implement this ourselves, but we will try to help you**

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by jtannas** [comment]
@BookOfGreg @sergioisidoro

**Comment by sergioisidoro** [comment]
This would be fixed by merging https://github.com/rswag/rswag/pull/476, since 4.1.3 is already a patched version. 
From the compatibility notes 4.x should still support the OAS 2.0 although we're also about to drop it.

I can try to make sure that #476 doesn't break anything merge and make a release.

**Comment by jtannas** [comment]
Thank you :bow: 
I've got more free time now than the last 2 months, so just let me know if there's anything I can lend a hand with.

**Comment by venkikg** [comment]
> Thank you 🙇 I've got more free time now than the last 2 months, so just let me know if there's anything I can lend a hand with.

Could you please tell me when the issue fix will be available? Because this is an issue with one of our client deployments.

**Comment by sergioisidoro** [comment]
@venkikg The issue should be resolved in master, but we haven't released the fixe to rubygems yet. If this is a critical issue for your client consider installing the gem directly from github for the time being (https://bundler.io/guides/git.html). Also note from the CVE that the impact of the vulnerability is quite restricted although it is categorised as "Moderate". Remember to evaluate the threat according to your context.

@jtannas if you have time, you could poke around the version in master to check that there's no problems on your setup :) I've been using the version in master in one project and so far no issues, but a second pair of eyes is always welcome. If there's no issues we could make a release of the gem. 🚀
