### ISSUE TITLE
[REQUEST] enable global or spec setting of accept header

### ISSUE THREAD

**Issue by jsugarman** [rswag/rswag#519]
## Is your feature request related to a problem? Please describe.
We version via the accept header, for example `accept: application/json;version=4`. I cannot find a way to amend the swagger_helper.rb or individuals specs to allow for supplying a version in the accept header. 

A manual hack of the generated `swagger.yaml` works:
```yml
paths:
  "/endpoint":
    post:
      ...
      responses:
        '200':
          description: successful
          content:
            "application/json;version=4": {} <---- this sets the accept header on the request
```

## Describe the solution you'd like
Ideally this would be definable/settable with a spec (which we can version ourselves), such as

```ruby
  path "/endpoint" do
    post("create something") do
      tags "something"
      consumes "application/json" <---- changes content-type only
      produces "application/json" 
      accepts "application/json;version=3" <---- possible new feature
```

Alternatively, or in addition, a way to override for all endpoints for a given version of swagger_docs via the `swagger_helper.rb`:

```ruby
    "v3/swagger.yaml" => {
      openapi: "3.0.1",
      info: {
        title: "API V3",
        version: "v3",
      },
      paths: {
        "/something": {
          post: {
            summary: "create something",
            responses: {
              '200': {
                description: "successful",
                content: {
                  "application/json;version=3": {}, <-------
                }
              },
            },
          },
        },
      },
    },
    "v4/swagger.yaml" => {
      openapi: "3.0.1",
      info: {
        title: "API V4",
        },
        version: "v4",
      },
      paths: {
        "/something": {
          post: {
            summary: "create something",
            responses: {
              '200': {
                description: "successful",
                content: {
                  "application/json;version=4": {}, <-------
                }
              },
            },
          },
        },
```

## What support could we give you, so you could implement this yourself?
Would this be something that is doable as I am aware that [OpenAPi 3.0](https://swagger.io/specification/) states
> If [in](https://swagger.io/specification/#parameter-in) is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored. 

## Describe alternatives you've considered
As above, plus using the `consumes` helper to set the Accept header as well as the Content-type header.

## Additional context
Trying to implement openAPI 3.0 for an existing API that uses the `Accept` for versioning, and am generating separate versioned swagger.yaml files using swaggerize.

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [X] OAS3
- [ ] OAS3.1

**Comment by lyricsboy** [comment]
Hi @jsugarman We have the same requirement, where we have per-endpoint versioning using the Accept header / media type as you describe. In our case, I am starting out by having both versions of the endpoint in the same swagger file, and here's how I wrote my test:

```ruby
require 'spec_helper'
require 'swagger_helper'

describe "Pings API" do
  
  path "/api/ping" do

    post "Returns a Ping" do
      produces "application/json;version=1"

      response "201", "Ping created" do
        schema type: :object,
          properties: {
            ping: { type: :object,
              properties: {
                status: { type: :string }
              },
              required: [ "status" ] 
            }
          },
          required: [ 'ping' ]
        
        run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['ping']['status']).to eq('ok')
        end
      end
    end

    post "Returns a Ping" do
      produces "application/json;version=2"

      response "201", "Ping created" do
        schema type: :object,
          properties: {
            ping: { type: :object,
              properties: {
                your_status_sir: { type: :string }
              },
              required: [ "your_status_sir" ] 
            }
          },
          required: [ 'ping' ]
        
        run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['ping']['your_status_sir']).to eq('ok')
        end
      end
    end
  end
end
```

This resulted in the following output:

```yaml
---
openapi: 3.0.1
info:
  title: some-service API
paths:
  "/api/ping":
    post:
      summary: Returns a Ping
      responses:
        '201':
          description: Ping created
          content:
            application/json;version=1:
              schema:
                type: object
                properties:
                  ping:
                    type: object
                    properties:
                      status:
                        type: string
                    required:
                    - status
                required:
                - ping
            application/json;version=2:
              schema:
                type: object
                properties:
                  ping:
                    type: object
                    properties:
                      your_status_sir:
                        type: string
                    required:
                    - your_status_sir
                required:
                - ping
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: some-service
```

Essentially, using the `produces` method to provide the appropriate versioned media type, in separate-but-otherwise-equal specs, will create a Swagger file that supports different responses for the same endpoint and each media type.

There are some limitations, as the `summary` and `description` will get determined by the spec run order. So you can't have different values for those in the tests and expect them to be distinct in the output. But this seems like it works well enough so far.

Using rswag version 2.6.0

**Comment by lyricsboy** [comment]
I'm unsure if this will work as I need it to if the parameters or request body are different between the two versions of the endpoint. Since the parameters and body are specified at the "Operation" level, I don't see a way to distinguish them from one another, and they might get merged or overwritten by the rswag implementation given the above test structure.
