### ISSUE TITLE
Rswag specs failing for rspec

### ISSUE THREAD

**Issue by haxxanali512** [rswag/rswag#522]
I am having a very strange issue while documenting the APIs with rswag. I have 15 rswag API documents that has been tested and they are working fine. But when I run the Rspec for login spec to see If it works or not. It throws an error saying invalid url(error is attached).
And for other APIs the error is invalid method X-API-TOKEN. Although I have handled this on backend for Authorization and X-API-TOKEN. If you guys have faced the similar issue please reach out to this so that I can continue with my deployment process. Can you guys help me on this @jamie @ledermann @thiagopradi @pjdavis @olleolleolle 
 [
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/68467749/169531466-ad908b7a-5f19-4e67-886b-ca509af2a84c.png">
](url)

**Comment by olleolleolle** [comment]
Perhaps you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), to aid finding the issue?

**Comment by haxxanali512** [comment]
@olleolleolle Yeah sure. Here is the code for a single rspec test case for login that i am trying to run: 



    post 'Login user' do
      tags 'Users Authentication'
      consumes 'application/json'

      parameter name: :user, in: :query, schema: {
        type: :object,
        properties: {
          user: {
            type: :object,
            properties:{
              email: { type: :string },
              password: { type: :string }
            }
          }
        },
        required: [ 'email', 'password' ]
      }

      response '201', 'Login User Successfully' do
        let(:user) { { email: 'admin@gmail.com', password: 'Password_123456' } }
        run_test!
      end
    end

**Comment by sudeeptarlekar** [comment]
I think you should be sending JSON data in request body and not in query. Also sending a password in URL query is big NO.

**Comment by jtannas** [comment]
Agreed with Sudeep here... The problem is likely something to do with encoding the email and password into the query parameters. Doing so is massive security vulnerability though because the URL doesn't get encrypted when making web requests. It's effectively broadcasting the user's password to everywhere that the request gets routed through.
Closing this issue since I don't see a anything that should be fixed on RSwag's side of things.
