### ISSUE TITLE
[REQUEST] Realease a new version to be able to add multiple examples

### ISSUE THREAD

**Issue by RobertAudi** [rswag/rswag#529]
## Is your feature request related to a problem? Please describe.

Right now it's not possible to add more than one example for a response with a given HTTP status code.

## Describe the solution you'd like

A fix was merge in https://github.com/rswag/rswag/pull/501 but is not released in any public version of the gem.

## What support could we give you, so you could implement this yourself?

\- 

## Describe alternatives you've considered

I tried the fix suggested in this issue: https://github.com/rswag/rswag/issues/438#issuecomment-1025725758

I also tried to adapt the modified from the master branch in before/after callbacks in the specs.

## Additional context

\-

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [x] OAS3
- [x] OAS3.1

**Comment by mscdit** [comment]
One question ... I am using rswag 2.5.1 and I am observing that only the "legacy" call to example**s** 

        examples 'application/json' => {
            id: 1,
            title: 'Hello legay world!',
            content: 'Hello legacy world and hello universe. Thank you all very much!!!',
            thumbnail: 'legacy-thumbnail.png'
         }

is working. A call to 

        example 'application/json', :example_1, {
          id: 1,
          title: 'Hello world!',
          content: 'Hello world and hello universe. Thank you all very much!!!',
          thumbnail: 'thumbnail.png'
        }, "Summary of the example", "A longer description of a fine blog post about a wonderfull universe!"

ends up with no example content in the swagger.json. Furthermore rspec yields one pending "Not yet implemented" message.

Thanks for every hint!

**Comment by jtannas** [comment]
Just released v2.6.0 :tada:
