### ISSUE TITLE
[REQUEST] Add frun_test! and xrun_test! equivalents to fit and xit for RSpec

### ISSUE THREAD

**Issue by ghost** [rswag/rswag#532]
## Is your feature request related to a problem? Please describe.
There are no equivalents to `fit` or `xit` when using the `run_test!` example group helpers.

## Describe the solution you'd like
Add `frun_test!` and `xrun_test!` 

## What support could we give you, so you could implement this yourself?
Tell me ASAP if you think this is a bad idea and won't approve a PR. Otherwise review my PR when I get it up in a timely manner.

## Describe alternatives you've considered
I can re-implement `run_test` manually or just include my own `frun_test!` and `xrun_test!` in my own project, but they'll probably be useful for others too.

**Comment by jtannas** [comment]
Seems like a good idea to me and I now have maintainer powers to merge PRs. I'd welcome a PR that implemented these.
