### ISSUE TITLE
[REQUEST] Too slow specs

### ISSUE THREAD

**Issue by MeterSoft** [rswag/rswag#537]
Any idea why swag specs is too slow

./spec/requests/api/web/v1/device_spec.rb[1:3:1:3:1:1:1]                      | passed  | 2.24 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:3:1:3:2:1]                        | passed  | 2.21 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:3:1:4:1:1:1]                      | passed  | 1.96 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:4:1:1:1]                          | passed  | 4.41 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:4:1:2:1:1:1]                      | passed  | 3.14 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:4:1:3:1:1:1]                      | passed  | 2.3 seconds           |
./spec/requests/api/web/v1/device_spec.rb[1:4:1:3:2:1]                        | passed  | 2.27 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:4:1:4:1:1:1]                      | passed  | 2.98 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:5:1:1:1]                          | passed  | 2.19 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:5:1:2:1:1:1]                      | passed  | 2.18 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:5:1:3:1:1:1]                      | passed  | 2.19 seconds          |
./spec/requests/api/web/v1/device_spec.rb[1:5:1:3:2:1]                        | passed  | 2.18 seconds

**Comment by jtannas** [comment]
Hi @MeterSoft - are this specs in this gem or within one of your own projects?
Without being able to see the spec code it's tough to say anything.

**Comment by jtannas** [comment]
Closing this issue due to no response.
