### ISSUE TITLE
[BUG] RSwag Schema pattern somehow did not match the regex

### ISSUE THREAD

**Issue by pawlarius** [rswag/rswag#546]
## Describe the bug
RSwag somehow said regex is wrong when it's not.

## Steps to Test or Reproduce

Here's the error message generated by RSwag.
Somehow "29/08/2022" did not match the regex '^d{2}/d{2}/d{4}$'.

```
swag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/promos/0/start_date' value "29/08/2022" did not match the regex '^d{2}/d{2}/d{4}$' in schema 5a4f4d0d-a729-5b26-bf1e-4e09fadacdd1#
```

<img width="800" alt="Screen Shot 2022-09-05 at 17 15 42" src="https://user-images.githubusercontent.com/27823957/188426135-41f6132a-d628-41a3-9639-6b5adbaf437f.png">

Here's my schema definition:

```
{
  "model_date": {
    "type": "string",
    "pattern": "^\d{2}\/\d{2}\/\d{4}$",
    "description": "Pretty date in dd/mm/yyyy format",
    "example": "28/02/2022"
  }
}
```

I tried running the same regex with Ruby regex online and it should match:
<img width="1078" alt="Screen Shot 2022-09-05 at 17 14 33" src="https://user-images.githubusercontent.com/27823957/188426441-990408f6-c379-466a-9ba3-02c9013e7247.png">

## Expected behavior
RSwag should not complain for the correct regex.

## Rswag Version
2.5.1

## Relates to which version of OAS (Open API Specification)
- [ ] OAS2
- [ ] OAS3
- [X] OAS3.1

**Comment by IlkhamGaysin** [comment]
As it's told in JSON Schema that is used under the hood
> The [pattern](https://json-schema.org/understanding-json-schema/reference/string.html#pattern) and [Pattern Properties](https://json-schema.org/understanding-json-schema/reference/object.html#patternproperties) keywords use regular expressions to express constraints. The regular expression syntax used is from JavaScript ([ECMA 262](https://www.ecma-international.org/publications/standards/Ecma-262.htm), specifically). However, that complete syntax is not widely supported, therefore it is recommended that you stick to the subset of that syntax described below.

[Ref](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html)


It also does not work
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/17009998/189157194-959205c5-afd4-446c-ac43-0b60540a1e4d.png">
```bash
     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/specificationUrl' value "http://armstrong.info/mckenzie.witting" did not match the regex '^(https?://)([da-z.-]+).([a-z.]{2,6})([/w .-]*)*/?$' in schema bfcde6e5-f52a-5956-b079-b41b31d20013#
```
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/17009998/189157396-3ff8eefc-af78-47ab-a517-86f63c048a7f.png">
