### ISSUE TITLE
Only the "legacy" call to example generation is working

### ISSUE THREAD

**Issue by jtannas** [rswag/rswag#548]
One question ... I am using rswag 2.5.1 and I am observing that only the "legacy" call to example**s** 

        examples 'application/json' => {
            id: 1,
            title: 'Hello legay world!',
            content: 'Hello legacy world and hello universe. Thank you all very much!!!',
            thumbnail: 'legacy-thumbnail.png'
         }

is working. A call to 

        example 'application/json', :example_1, {
          id: 1,
          title: 'Hello world!',
          content: 'Hello world and hello universe. Thank you all very much!!!',
          thumbnail: 'thumbnail.png'
        }, "Summary of the example", "A longer description of a fine blog post about a wonderfull universe!"

ends up with no example content in the swagger.json. Furthermore rspec yields one pending "Not yet implemented" message.

Thanks for every hint!

_Originally posted by @mscdit in https://github.com/rswag/rswag/issues/529#issuecomment-1180243079_

**Comment by jtannas** [comment]
@mscdit I'm just catching up on everything going on in this repo and release v2.6.0
Is this still applicable there?

**Comment by romanblanco** [comment]
@mscdit See https://github.com/rswag/rswag/issues/545#issuecomment-1256783108.

@jtannas Can be closed together with #545.
