### ISSUE TITLE
Missing Response Schemas

### ISSUE THREAD

**Issue by jtannas** [rswag/rswag#559]
### Discussed in https://github.com/rswag/rswag/discussions/558

<div type='discussions-op-text'>

<sup>Originally posted by **owen-webb** September 27, 2022</sup>
I would like to generate schemas for responses documented in Swagger. The ability to define a response schema, as demonstrated in the code below, suggests to me that this would be possible; however, I do not see a "schema" link in the response section of the UI or any reference to defined schemas in the generated JSON files.

Does RSwag support this functionality?

Is there anything missing from the code below that might be needed to generate response schemas?

```ruby
1  require "swagger_helper"
2  
3  describe "SMS API" do
4    path "/sms/enable" do
5      post "Enable SMS" do
...   
31        response 500, "Failed to enable SMS communications."
32           schema type: :object, properties: {error_code: {type: :string}, error_message: {type: :string}}
33           example "application/json", :error, {error_code: :U0, error_message: "Invalid state transition."}
34       end
35     end
36   end
37 end
38
```
(Note the reference to "schema" on line 32.)

![Swagger Response](https://user-images.githubusercontent.com/28901695/192650311-238f8851-add3-4e39-8cf4-37e074a4ac7b.png)
(Note the missing "schema" link. The "example" link is generated as expected.)</div>

**Comment by jtannas** [comment]
@owen-webb that looks like a bug...
What versions are you using for
- RSwag?
- RSpec?
- Rails?
- Ruby?

Having more information will help me find & fix the issue.

**Comment by owen-webb** [comment]
> @owen-webb that looks like a bug... What versions are you using for
> 
> * RSwag?
> * RSpec?
> * Rails?
> * Ruby?
> 
> Having more information will help me find & fix the issue.

RSwag is version 2.6.0
RSpec (rspec-rails) is version 4.1.2
Rails is version 6.1.6.1
Ruby is version 2.7.6

**Comment by romanblanco** [comment]
@owen-webb It should be possible to generate schema using rswag, but I can reproduce the same issue using Swagger Editor.

We're using the `schema` method here:
https://github.com/RedHatInsights/compliance-backend/blob/f7783ec66c2a64a78b043630f730acf8ca1eb17a/spec/integration/profiles_spec.rb#L56

Generating this OpenAPI spec: https://raw.githubusercontent.com/RedHatInsights/compliance-backend/fab750a1268e1589b256892dc8086eb4db954413/swagger/v1/openapi.json

Resulting in 
![image](https://user-images.githubusercontent.com/1187051/193354238-0e29df1d-b8a3-43b3-9d5e-337934465b92.png)

However, I'm noticing that if I import the `openapi.json` into [SwaggerEditor](https://editor.swagger.io/), the schema is not visible.

Maybe there was a change in the Swagger viewer :thinking:

**Comment by cdimitroulas** [comment]
I believe I am also experiencing this issue. 

Rails: 7.0.1
rspec-rails: 5.1.2
Rswag: 2.6
Ruby: 3.0.4

I don't see the response/content/schema in the outputted swagger.yaml file with code like this:
```
RSpec.describe 'Something' do
  path '/my/path' do
    get 'returns the list of things' do
      response '200', 'Success' do
        schema type: :object,
               properties: {
                 items: {
                   type: :array,
                   items: { type: :array, items: my_schema }
                 },
                 page: { type: :integer },
                 pageCount: { type: :integer },
                 pageSize: { type: :integer },
                 requiresPagination: { type: :boolean }
               }

        let!(:my_thing) { create(:my_thing) }

        run_test!
      end
    end
  end
end

``` 

_Edit: I tested with rswag 2.5 and the issue was still there for me. I wasn't able to try an earlier version than that as it's not compatible with the rest of my app's gems if I go to 2.4 or earlier_

**Comment by rbarge76** [comment]
I just had the same issue, it turns out you need to make sure you have the ```produces 'application/json'``` before it will output the schema

**Comment by owen-webb** [comment]
> I just had the same issue, it turns out you need to make sure you have the `produces 'application/json'` before it will output the schema

Adding this line to the response block fixed the issue for me. Thank you, @rbarge76!

**Comment by romanblanco** [comment]
@rbarge76 You're right, making sure `examples` and `schema` are under the same mime type helped! :+1:

**Comment by romanblanco** [comment]
@jtannas, this can be closed now :slightly_smiling_face:
