### ISSUE TITLE
Rswag Testing Question

### ISSUE THREAD

**Issue by gabrielmytime** [rswag/rswag#565]
Hello, 

I've just started working with RSWAG and I can't really seem to find out how the testing actually works. For example, I have this code for an index and I want to see if the test is ran - I put a print in my index method to see if it appears in console but no result.

```
 path '/api/v1/boards' do
    get 'Retrieve the boards' do
      tags 'Boards'
      consumes 'application/json'
      response '200', 'boards retrieved' do
        let(:board) { { name: 'foo' } }
        run_test!
      end
    end
```

how do I check if the tests are running? because if I comment the let and run test, it somehow still passes.

If you need any further explanation or information to understand what my question is, please do ask. 

Thank you!

**Comment by oblakeerickson** [comment]
From the [README section about `run_test!`](https://github.com/rswag/rswag#paths-operations-and-responses) you can check for a specific status code or a that a specific value is returned with something like:

```
response '200', 'boards retrieved' do
  run_test! do |response|
    data = JSON.parse(response.body)
    expect(data['title']).to eq('foo')
  end
end
```

**Comment by gabrielmytime** [comment]
@oblakeerickson 
`get 'Retrieve the boards' do
      tags 'Boards'
      consumes 'application/json'
      response '200', 'boards retrieved' do
        let(:board) { { name: 'foo' } }
        run_test! do |response|
          data = JSON.parse(response.body)
          pp data
          expect(true).to eq(true)
        end
      end
    end`

Should this work? It is not printing the data and I'm not seeing any tests being executed so I'm trying to figure it out how exactly rswag tests.

**Comment by jtannas** [comment]
Seems resolved; closing
