### ISSUE TITLE
Relax Rails dependency, allow Rails 5.1

### ISSUE THREAD

**Issue by grk** [rswag/rswag#58]
I've tested the fork at https://github.com/we-studio/rswag/commit/fb00ae5d130895918e0fddacab8c7382e19b0db3 and it works without any problems in our app. Would be great to get a released version that works with Rails 5.1.

**Comment by djcp** [comment]
@grk It might move this along quicker if you submitted that as a PR. We need this too!

**Comment by domaindrivendev** [comment]
Yep - submit and test a PR and I'll endeavor to get it released ASAP

**Comment by grk** [comment]
Opened #59.

**Comment by domaindrivendev** [comment]
Fixed by #59
