### ISSUE TITLE
[REQUEST] Using "include" as an optional query parameter is not "optional" 

### ISSUE THREAD

**Issue by SL855** [rswag/rswag#586]
While using rswag to generate openapi documentations, my controller uses a query optional parameter named ":include". With attribute "required: false", I expected not to initialize the parameter when unnecessary. 
```
parameter name: :include, in: :query, required: false, description: "All available top-level includes", schema: { type: :array, items: { type: :string, enum: [:name, :id] } }
response "200", "item retrieved" do
  run_test!
end
```
This makes the response to be `nil` because in file `rswag/rswag-specs/lib/rswag/specs/request_factory.rb`, 
```
          parameters.select { |p| p[:in] == :query }.each_with_index do |p, i|
            path_template.concat(i.zero? ? '?' : '&')
            path_template.concat(build_query_string_part(p, example.send(p[:name]), swagger_doc))
          end
```
`example.send(p[:name])` aborts with error where `p[:name]` is `:include` while no such parameter is passed.
In the same file, method `expand_parameters`
   ```
     (operation_params + path_item_params + security_params)
          .map { |p| p['$ref'] ? resolve_parameter(p['$ref'], swagger_doc) : p }
          .uniq { |p| p[:name] }
          .reject { |p| p[:required] == false && !example.respond_to?(p[:name]) }
      end
```
`example.respond_to?(:include)` always returns `true` such that `:include` is always contained in parameters.

I hope you can make parameters named like `:include` to be optional.

**Comment by Arkolos** [comment]
Hello ! I also have this issue (if I understood well). I would like to do optional parameters but I am not sure it is possible.

If I do `parameter name: :account_id, in: :query, type: :string, default: nil,  nullable: true`, I would like my parameter `account_id` to not be given, or to be nil in my controller . However it is set to `""` , which break my code.

**Comment by pechorin** [comment]
+1. This is kind of expected problem, where should be some way for both: 1) define parameter and 2) provide way not to send null string "" value.

**Comment by Deathis** [comment]
> Hello ! I also have this issue (if I understood well). I would like to do optional parameters but I am not sure it is possible.
> 
> If I do `parameter name: :account_id, in: :query, type: :string, default: nil, nullable: true`, I would like my parameter `account_id` to not be given, or to be nil in my controller . However it is set to `""` , which break my code.

Try this:
`parameter name: :account_id, in: :query, type: :string, default: nil,  nullable: true, required: false`
It works if you don't use `let(:account_id)`. Without `required: false` it needs let to be defined.

When I set required to false and I don't use `let(:include)` then it is trying to send `<RSpec::Matchers::BuiltIn::Include:0x000000011a0daf28>` as value. It works if i rename parameter.

**Comment by Arkolos** [comment]
It works for me, thank you!
