### ISSUE TITLE
[BUG] Rswag return error if the schema has attribute with int4multirange 

### ISSUE THREAD

**Issue by amr-hamdy** [rswag/rswag#595]
## Describe the bug
When you run rails rswag it returns an error if the schema has an attribute with type of int4multirange 

## Steps to Test or Reproduce

1. Database is POSTGRES
2. Generate a new model called EvenRole
3. Generate new migration file to add a new attribute by running this command
`execute 'ALTER TABLE event_roles ADD working_hours_ranges int4multirange'`
4. run `rails db:migrate`
5. run `rails rswag`

## Expected behavior
The documentation should generated successfully and all the test cases should passed without any problem

## Screenshots
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/68852051/217655138-f24fa23f-8037-4fb1-b9ce-99b5e1abce99.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/68852051/217655379-f0702203-5b5b-4888-8ded-e1020d451ac4.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/68852051/217655399-f9c014ec-8b3a-4f4f-94bc-f6f25dc9cdeb.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/68852051/217655453-c5424ec3-882e-42b8-94ae-4a054775c77e.png">
In the Schema file 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/68852051/217656429-8bc63a42-dc47-4b3d-aad2-2825180b2c99.png">

## Dependency versions
The version of are you using for:
* rswag-api (2.6.0)
* rswag-specs (2.6.0)
* rails (7.0.4)
* ruby )3.1)

**Comment by MohabKahla** [comment]
how did you solve it? I have the same issue :hand:
