### ISSUE TITLE
[BUG] Server URL placeholder replacement using custom variables broken in rswag-specs version 2.7.0 and 2.8.0

### ISSUE THREAD

**Issue by beatbull** [rswag/rswag#597]
## Describe the bug
rswag-specs 2.7.0 introduced a bug when building the base_path from server . The bug is still present in 2.8.0 .  The custom variables provided for the server URL with placeholders are not replaced properly any more.

## Steps to Test or Reproduce
Take a look at commit https://github.com/rswag/rswag/commit/2264b033e8ff7c88d04a800c9197f7dc8971ac47 , especially the implementation of the method `base_path_from_servers`.

It basically changed 
`url = server[:url].gsub(/\{(.*?)\}/) { variables[$1.to_sym] }`
to
`base_path = server[:url].gsub(/\{(.*?)\}/) { |name| variables[name.to_sym] }`

When providing:
```
swagger_doc = {servers: [{url: "{protocol}://{defaultHost}", variables: {protocol: {default: 'https' }, defaultHost: {default: 'localhost'} } } ] }
```
the old code using `$1` produces `"https://localhost"`
, while the new code using the block with the `name` variable produces `"://"`.

:confused: 

## Screenshots
Code and links explain the issue and can be easily checked and reproduced in `irb`.

## Additional context
I guess the case where the first server URL in the openAPI spec is a URL with placeholders & variables simply has no test coverage currently and thus any code refactoring carried out since 2.5.1 has been not tested for this case.

## Dependency versions
The version of are you using for:
* Rswag: 2.8.0 - except for rswag-specs, which is stuck at 2.5.1, error above comes for 2.7.0 and 2.8.0
* RSpec: 3.12.1
* Rails: 7+
* Ruby: 2.7.5, 3.2.1 (issue same for both)

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [x] OAS3
- [ ] OAS3.1

**Comment by roxanemace** [comment]
Same issue on my side!

**Comment by gridar** [comment]
I had the same issue.
There is a PR opened for this here : https://github.com/rswag/rswag/pull/591

**Comment by romanblanco** [comment]
Fixed by https://github.com/rswag/rswag/pull/591
