### ISSUE TITLE
Struggling to find a solution to multipart/form-data upload

### ISSUE THREAD

**Issue by braindeaf** [rswag/rswag#598]
I hope you can help because I feel like I'm going round in circles but hopefully there is an easy answer.

I am trying to write the spec for a file upload say something like...

```
post "Create List of Photo" do
  consumes "multipart/form-data"
  produces "application/json"
  parameter name: :caption, in: formData
  parameter name: :photos, in: :formData

  let(:photos) { [image] }
  let(:caption) { 'My Photos' }

  response "201", :created, use_as_request_example: true do
    schema "$ref" => "#/components/schemas/photos"
    run_test!
  end
end
```

photos has to be form data since we are uploading a file. The caption doesn't have to be formData, it could be json but for an easy life. All form-data. Now I can see from the swagger.json that parameters for this request are empty, there is no requestBody and since I haven't / can't set a schema there is no helpful example.

The documentation for OpenAPI 3.0
https://swagger.io/docs/specification/describing-request-body/file-upload/

...suggests that we can document an upload by setting requestBody

```
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          caption:
            type: string
          photos:
            type: array
            items:
              type: file
```

This is never set. SwaggerFormater#stop seems to be where this is set. However, the schema_param here is attached to a specific parameter, and set for the entire request. I am not sure in what situation this makes sense unless it's designed to only be used when you only have one parameter in form-data.

```
def stop(_notification = nil)
-----8<-----
          if is_hash && value[:parameters]
            schema_param = value[:parameters]&.find { |p| (p[:in] == :body || p[:in] == :formData) && p[:schema] }
            mime_list = value[:consumes] || doc[:consumes]
            if value && schema_param && mime_list
              value[:requestBody] = { content: {} } unless value.dig(:requestBody, :content)
              value[:requestBody][:required] = true if schema_param[:required]
              value[:requestBody][:description] = schema_param[:description] if schema_param[:description]
              examples = value.dig(:request_examples)
              mime_list.each do |mime|
                value[:requestBody][:content][mime] = { schema: schema_param[:schema] }
                if examples
                  value[:requestBody][:content][mime][:examples] ||= {}
                  examples.map do |example|
                    value[:requestBody][:content][mime][:examples][example[:name]] = {
                      summary: example[:summary] || value[:summary],
                      value: example[:value]
                    }
                  end
                end
              end
            end
-----8<-----
end
```

It feels like I could solve this by setting the schema on a single parameter and leave the others with no schema. But it feel very wrong indeed. 

Lastly if I want to set a practical example how is the best way to do it, since we may or may not have a schema available. I've seen *request_body_example* but where I could potentially output the body request as a string based on the following PR.

https://github.com/rswag/rswag/pull/555

I will add I couldn't get the config.after(:each) hook to trigger which was unexpected so this didn't work for me either.

Sorry if this is a long one but to sum up. I would like a request with a file upload to produce requestBody, and an example and know that I am going about this the right way. Can anyone make any suggestions?

Many thanks

**Comment by braindeaf** [comment]
I will add if this just isn't possible I am happy to work on a PR to make this improvement.

**Comment by romanblanco** [comment]
@braindeaf, thank you for the detailed description!

Did you check, if https://github.com/rswag/rswag/pull/451 or the [suggested workaround](https://github.com/rswag/rswag/pull/451#issuecomment-1453846096) is addressing your problems?
