### ISSUE TITLE
Servers setup can not parse variables correctly

### ISSUE THREAD

**Issue by jokklan** [rswag/rswag#601]
## Describe the bug
The `variables` in for `servers` does not seem to be correctly parsed. I get the following error because of this:

```
URI::InvalidURIError:
  bad URI(is not URI?): ":3000"
```

## Steps to Test or Reproduce
In `spec/swagger_helper.rb` setup the following:

```ruby
config.swagger_docs = {
  'v1/swagger.yaml' => {
  openapi: '3.0.1',
  info: {
    title: 'API V1',
    version: 'v1'
  },
  servers: [{
    url: '{domain}:3000',
    description: 'Local development server',
    variables: {
      domain: {
        default: 'http://localhost'
      }
  }]
}
```

## Expected behavior
Running specs should work as normal, and use the specified server (here http://localhost:3000).

## Additional context
This change seems to be the culprit: https://github.com/rswag/rswag/commit/2264b033e8ff7c88d04a800c9197f7dc8971ac47#diff-bbd8f08065700370f3c638e9dc2ba07c5af94f30dd770d7d77f2486421433b6b

I think going back to `server[:url].gsub(/\{(.*?)\}/) { variables[$1.to_sym]  }` from `server[:url].gsub(/\{(.*?)\}/) { |name| variables[name.to_sym] }` should fix the issue.

## Dependency versions
The version of are you using for:
* Rswag: 2.8.0
* RSpec: 3.11.0
* Rails: 7.0.3.1
* Ruby: 3.1.3

## Relates to which version of OAS (OpenAPI Specification)
- [x] OAS3
- [x] OAS3.1

**Comment by gridar** [comment]
I had the same issue 👍 
FYI there is a PR opened for this https://github.com/rswag/rswag/pull/591

**Comment by romanblanco** [comment]
Fixed by https://github.com/rswag/rswag/pull/591
