### ISSUE TITLE
[BUG] '+' sign in url does not get encoded properly

### ISSUE THREAD

**Issue by NebojsaStrbac997** [rswag/rswag#606]
## Describe the bug
I have a param in query called 'created_after'. It is a string with datetime format and when being sent, it isn't encoded properly. The plus sign turns into a 'space' in the URL. 

## Steps to Test or Reproduce
created_after is defined like this:

` parameter name: :created_after, in: :query, required: false, type: :string, format: :datetime `

My test looks like this: 
```
 response 200, "Get all examples that are created after 'created_after' value" do
  let(:old_example) { create(:example, created_at: Datetime.current - 5.days) }
  let(:created_after) { (old_example.created_at + 5.minutes).to_formatted_s.sub(" ", "T").gsub(" ", "") }
  
  run_test! do
    excluded_example_id = old_example.id
    expect(json_response_data_ids).to_not include(excluded_example_id)
   end
 end
```
When swaggerizing the tests, they fail. In my rails logs I notice that this happens:

```
Started GET "/api/v1/example/index?created_after=2023-03-05T15:33:01+0100"

Processing by Api::V1::example::exampleController#index as HTML Parameters: {"created_after"=>"2023-03-05T15:33:01 0100"
```
In Parameters: the plus sign is changed to a space, instead of being encoded back into a plus sign.

Here is the code for created_after in my controller:
```
      def created_after_param
        created_after = params.fetch(:created_after, nil)
        created_after.present? ? parse_created_after_param(created_after) : nil
      end

      def parse_created_after_param(created_after)
        Time.strptime(created_after, "%Y-%m-%dT%H:%M:%S%z")
      rescue ArgumentError
        nil
      end
```

## Expected behavior
In parameters, created_after should have a + at the end, and thus the test will pass.

## Dependency versions
* Rswag: 2.8.0
* RSpec: 3.11.0
* Rails: 7.0.3
* Ruby: 3.1.2

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [x] OAS3.1

**Comment by NebojsaStrbac997** [comment]
@romanblanco I have found a temporary workaround. Basically I've added CGI.escape to the string inside created after like this:

`let(:created_after) { CGI.escape((old_notice.created_at + 2.minutes).to_s.sub(" ", "T").gsub(" ", "")) }`

Not sure if this is the cleanest solution, but it works at the moment. I found the solution on this thread on [stackoverflow](https://stackoverflow.com/questions/6464885/rails-plus-sign-in-get-request-replaced-by-space).

**Comment by romanblanco** [comment]
Thanks for reporting back, @NebojsaStrbac997!

**Comment by NebojsaStrbac997** [comment]
This same spec works with rspec_api_documentation. I'm switching to rswag because the rspec_api_documentation gem is no longer being maintained or seems like it at least.

**Comment by NebojsaStrbac997** [comment]
@romanblanco After checking out rswags files, is there a reason why this is the only case that is not being escaped? 

https://github.com/rswag/rswag/blob/77759f05f9aa0527f4fee4cd5433cf3aa0eaff9e/rswag-specs/lib/rswag/specs/request_factory.rb#L176

In all other cases, the param being sent is escaped. In my case, my param is probably ending up here.

**Comment by romanblanco** [comment]
@NebojsaStrbac997 It's not obvious to me why that one is not being escaped.

Looking thorugh https://github.com/rswag/rswag/pull/311 and https://github.com/rswag/rswag/pull/507 could provide a clue.

I've tried to escape the `name` and `value`, and the change does not break any tests:

```diff
diff --git a/rswag-specs/lib/rswag/specs/request_factory.rb b/rswag-specs/lib/rswag/specs/request_factory.rb
index f13fddcb..13f2c4c4 100644
--- a/rswag-specs/lib/rswag/specs/request_factory.rb
+++ b/rswag-specs/lib/rswag/specs/request_factory.rb
@@ -135,7 +135,7 @@ module Rswag
               return "#{CGI.escape(name.to_s)}=" + value.to_a.flatten.map{|v| CGI.escape(v.to_s) }.join(separator)
             end
           else
-            return "#{name}=#{value}"
+            return "#{CGI.escape(name.to_s)}=#{CGI.escape(value.to_s)}"
           end
         end
```

**Comment by NebojsaStrbac997** [comment]
@romanblanco After forking and trying this, my param doesn't hit these lines. I'll try to find out about my specific case what is happening when I can :+1:

**Comment by NebojsaStrbac997** [comment]
@romanblanco I have a potential fix for this, I'll make some tests for it and see if my change breaks anything :smile:

**Comment by romanblanco** [comment]
https://github.com/rswag/rswag/pull/621

**Comment by HiroNonoyama** [comment]
I'm using OpenAPI v3, and I have defined a parameter as follows:

```rb
parameter name: started_at, in: :query, type: :string, format: 'date-time'
```
In a scenario where I have multiple test cases within a single response block, I'm encountering an issue. When I ran `rails rswag`, after the completion of the first test case, the `upgrade_request_type!(metadata)` method is altering the definition from `type: :string` to `schema: { type: :string }`. As a result, the encoding is not performed correctly for the second and subsequent test cases.

---
```rb
get('search') do
  parameter name: :started_at, in: :query, type: :string

  response(200, 'successful') do
    after do |example|
      content = example.metadata[:response][:content] || {}
      example_spec = {
        'application/json' => {
          examples: {
            example.metadata[:example_group][:description] => {
              value: JSON.parse(response.body, symbolize_names: true)
            }
          }
        }
      }
      example.metadata[:response][:content] = content.deep_merge(example_spec)
    end

    let(:started_at) { Time.current.iso8601 }

    context 'context 1' do
      run_test! # ok
    end

    context 'context 2' do
      run_test! # error because of not url encoding "+09:00:00"
    end

    context 'context 3' do
      run_test! # error because of not encoding "+09:00:00"
    end
  end
end
```

**Comment by NebojsaStrbac997** [comment]
> I'm using OpenAPI v3, and I have defined a parameter as follows:
> 
> ```ruby
> parameter name: started_at, in: :query, type: :string, format: 'date-time'
> ```
> 
> In a scenario where I have multiple test cases within a single response block, I'm encountering an issue. When I ran `rails rswag`, after the completion of the first test case, the `upgrade_request_type!(metadata)` method is altering the definition from `type: :string` to `schema: { type: :string }`. As a result, the encoding is not performed correctly for the second and subsequent test cases.
> 
> ```ruby
> get('search') do
>   parameter name: :started_at, in: :query, type: :string
> 
>   response(200, 'successful') do
>     after do |example|
>       content = example.metadata[:response][:content] || {}
>       example_spec = {
>         'application/json' => {
>           examples: {
>             example.metadata[:example_group][:description] => {
>               value: JSON.parse(response.body, symbolize_names: true)
>             }
>           }
>         }
>       }
>       example.metadata[:response][:content] = content.deep_merge(example_spec)
>     end
> 
>     let(:started_at) { Time.current.iso8601 }
> 
>     context 'context 1' do
>       run_test! # ok
>     end
> 
>     context 'context 2' do
>       run_test! # error because of not url encoding "+09:00:00"
>     end
> 
>     context 'context 3' do
>       run_test! # error because of not encoding "+09:00:00"
>     end
>   end
> end
> ```
@HiroNonoyama Have you tried changing format: 'date-time' to format: 'datetime'

**Comment by HiroNonoyama** [comment]
@NebojsaStrbac997 

> @HiroNonoyama Have you tried changing format: 'date-time' to format: 'datetime'

Same thing happened

**Comment by NebojsaStrbac997** [comment]
@HiroNonoyama I remember having the same issue with using multiple context blocks. Check out [this thread](https://github.com/rswag/rswag/issues/79), it might help you out. I think you need to define let in every context block in order to use multiple context blocks.

Also you can move the after block above the get blocks as to not repeat it for every response block.

**Comment by HiroNonoyama** [comment]
@NebojsaStrbac997 
Thank you
I have checked the issue, but it has not been resolved. I read the source code and found that `upgrade_request_type!(metadata)` is called with each execution of run_test!, and I believe that this is causing the `type: :string` parameter within metadata to be wrapped in scheme.

For the parameter `scheme: { type: :string }`, URL encoding seems to be skipped, and the parameter appears to be executed in the request as is."
