### ISSUE TITLE
Dropping of OAS2

### ISSUE THREAD

**Issue by romanblanco** [rswag/rswag#609]
### Discussed in https://github.com/rswag/rswag/discussions/503

<div type='discussions-op-text'>

<sup>Originally posted by **sergioisidoro** February 22, 2022</sup>
Hi everyone, 

Right now supporting OAS2 adds quite a big overhead, and I'm wondering if it really makes sense to continue supporting it. OAS 3.0.0 was released on 26 July 2017, and if we to continue to keep this gem in good shape, it's time to focus our resources into supporting OAS >= 3

Some examples of the overhead in keeping backwards compatibility include recent pull requests, like:
* Response examples - https://github.com/rswag/rswag/pull/501
* Query - https://github.com/rswag/rswag/pull/499 

What do you think? Please react with 👎 if still need OAS2 support.</div>

**Comment by pboling** [comment]
The lift to support OAS 3.1 may also be significant, as OAS dropped SemVer with 3.1 and introduced breaking changes to bring OAS fully inline with JSONSchema... all the more reason to drop 2.0.

https://apisyouwonthate.com/blog/openapi-v3-1-and-json-schema/
