### ISSUE TITLE
[BUG] With `swagger_dry_run` set to false, Rswag reports DEPRECATION WARNING despite using Rspec 3

### ISSUE THREAD

**Issue by CKolkey** [rswag/rswag#611]
## Describe the bug
Despite using ruby `3.2.1` and rspec `3.12`, every time we run the rswag rake task, a deprecation warning is printed.
https://github.com/rswag/rswag/blob/154af48db7f5b702b69091e4f1b25fb15c2e076c/rswag-specs/lib/tasks/rswag-specs_tasks.rake#L21

## Steps to Test or Reproduce
On ruby `3.2.1` and rspec `3.12`, run `SWAGGER_DRY_RUN=0 rails rswag`

## Expected behavior
I do not expect a deprecation warning for a version of rspec that I am not using.

## Screenshots
![Screenshot 2023-03-27 at 12 13 52](https://user-images.githubusercontent.com/7228095/227913090-af77d063-1355-4a2d-9a5d-52e95cfa4f1e.png)
```
> SWAGGER_DRY_RUN=0 rails rswag
using KG_SITE=pro-dk
DEPRECATION WARNING: Rswag::Specs: WARNING: Support for RSpec 2.X will be dropped in v3.0 (called from <main> at bin/rails:4)
/Users/u0158204/.asdf/installs/ruby/3.2.1/bin/ruby -I/Users/u0158204/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib:/Users/u0158204/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-support-3.12.0/lib /Users/u0158204/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined
```

## Dependency versions
The version of are you using for:
* Rswag: `2.8.0`
* RSpec: `3.12.1`
* Rails: `7.0.4.2`
* Ruby: `3.2.1`

**Comment by romanblanco** [comment]
@CKolkey, thank you for submitting the issue :+1: 

I plan to remove the support for older version of Rspec soon, so the deprecation message will be removed too.

**Comment by romanblanco** [comment]
Closing the issuee, as the code removing the report has been removed in `v3` branch and will be released in v3.
