### ISSUE TITLE
[REQUEST] new release 2.9

### ISSUE THREAD

**Issue by Piioo** [rswag/rswag#612]
Hello,

When is the next release planned?
In master is it possible to specify `spec_path`, but not in the 2.8 release from November.

**Comment by romanblanco** [comment]
Hi @Piioo, it's one of the next things on my list. I plan to release 2.9 this month.

**Comment by romanblanco** [comment]
FYI, starting with a draft: https://github.com/rswag/rswag/releases/tag/untagged-28ccb4041c8c97dc50eb

**Comment by romanblanco** [comment]
https://github.com/rswag/rswag/releases/tag/2.9.0
