### ISSUE TITLE
[REQUEST] Is there a way to change the favicon, title and logo image?

### ISSUE THREAD

**Issue by yshmarov** [rswag/rswag#616]
👋 Hello! I've been trying to add `rswag` to my app, everything works great but I just can't figure out how to customize the layout....

**Is there a way to change the `favicon`, `title` and `logo image`?**

<img width="347" alt="Screenshot 2023-04-01 at 20 09 56" src="https://user-images.githubusercontent.com/13472945/229307514-affebcb5-9d15-4471-acca-71f4ad99790e.png">

**Comment by yshmarov** [comment]
sorry, I was being inattentive. Found it in the readme: https://github.com/rswag/rswag#customizing-the-swagger-ui

perfect!

**Comment by yshmarov** [comment]
Okay, I have tried customizing the layout. Updating the <title> and thumbnails was easy, but to change the `"swagger sponsored by"` logo with my logo I found a solution [here](https://stackoverflow.com/a/61143351/5695646). 

I added this code, while I had an image named `favicon.png` in the `public` folder
```js
<script>
  (function () {
  window.addEventListener("load", function () {
      setTimeout(function () {

          var logo = document.getElementsByClassName('link');

          logo[0].children[0].alt = "Yaros API";
          logo[0].children[0].src = "/favicon.png";
      });
  }); })();
</script>
```


image 1 - updated title and thumbnail
<img width="275" alt="Screenshot 2023-04-01 at 20 43 24" src="https://user-images.githubusercontent.com/13472945/229308784-c4de470c-24c3-499e-bb4b-5bce648cf009.png">
image 2 - updated logo
<img width="418" alt="Screenshot 2023-04-02 at 00 15 01" src="https://user-images.githubusercontent.com/13472945/229316378-a2bfe898-d2c6-4deb-82c0-e976a4bdd419.png">

**Comment by romanblanco** [comment]
@yshmarov, feel free to document [your find](https://stackoverflow.com/a/61143351/5695646) in https://github.com/rswag/rswag#customizing-the-swagger-ui
