### ISSUE TITLE
[BUG] rswag:ui:copy_assets not working

### ISSUE THREAD

**Issue by yshmarov** [rswag/rswag#617]
## Describe the bug

I tried following the instruction for [Serve UI Assets Directly from your Web Server](https://github.com/rswag/rswag#serve-ui-assets-directly-from-your-web-server) and ran variations of `bundle exec rake rswag:ui:copy_assets[public/api-docs]`, but it does not seem to be working for me:

<img width="855" alt="Screenshot 2023-04-01 at 23 27 15" src="https://user-images.githubusercontent.com/13472945/229349658-50083409-92cc-4188-b1a8-b608af90b2a5.png">

## Dependency versions
The version of are you using for:
* Rswag: 2.8.0
* RSpec: irrelevant
* Rails: 7.0.4.3
* Ruby: 3.2.1

**Comment by romanblanco** [comment]
@yshmarov, thank you for submitting the issue :+1: 

I've tried executing a version of `bundle exec rake rswag:ui:copy_assets[public/api-docs]` in [our codebase](https://github.com/RedHatInsights/compliance-backend/tree/4ab5f84596c590761b097475028d8f0c206f27be) and it seems to work for me:

```sh
$ podman-compose exec rails bundle exec rake rswag:ui:copy_assets[openapi_example]
['podman', '--version', '']
using podman version: 4.4.3
podman exec --interactive --tty --env POSTGRESQL_TEST_DATABASE=compliance_test --env DISABLE_DATABASE_ENVIRONMENT_CHECK=1 --env HOSTNAME=rails --env ACG_CONFIG=/opt/app-root/src/devel.json --env SWAGGER_DRY_RUN=0 compliance-backend_rails_1 bundle exec rake rswag:ui:copy_assets[openapi_example]
exit code: 0

$ ls openapi_example/
absolute-path.js  favicon-16x16.png  favicon-32x32.png  index.js  swagger-ui-bundle.js  swagger-ui.css  swagger-ui-es-bundle-core.js  swagger-ui-es-bundle.js  swagger-ui.js  swagger-ui-standalone-preset.js
```

Could you try running the command with `--trace` to trace the error? 

```sh
bundle exec rake rswag:ui:copy_assets[public/api-docs] --trace
```

**Comment by yshmarov** [comment]
here's what I get:
<img width="1067" alt="Screenshot 2023-04-02 at 16 15 32" src="https://user-images.githubusercontent.com/13472945/229358489-7cd2f867-a947-4952-9bd3-1ad13f1b86d6.png">

**Comment by romanblanco** [comment]
@yshmarov, looks like `zsh` is complaining about the `[public/api-docs]`. Have you tried executing the command using `bash` or another shell?

**Comment by Nkadze** [comment]
Hi Guys, on my end command executes successfully, but nothing is copied in `public/api-docs` folder
output of rake task: 
```
** Invoke rswag:ui:copy_assets (first_time)
** Execute rswag:ui:copy_assets
```
I'm using latest master of rswag gem, 
rails 7.0.6 (with importmaps) 
ruby 3.0.4

Am I missing something?

Thanks in advance

**Comment by yshmarov** [comment]
In the end everything worked for me. I made a small video tutorial about it. Hope it helps you too: https://superails.com/posts/rails-7-131-api-documentation-with-openapi-swagger-rswag-generate-manifest-with-chatgpt

**Comment by Nkadze** [comment]
Thanks for responses, what I've found out 
`bundle exec rake rswag:ui:copy_assets[public/api-docs] --trace` this will only work on if rails is on webpacker setup, not when assets are served through importmaps
