### ISSUE TITLE
Swagger UI 3.x

### ISSUE THREAD

**Issue by moserke** [rswag/rswag#62]
Are their plans to upgrade to Swagger UI 3.x?

**Comment by douglasrlee** [comment]
👍

**Comment by douglasrlee** [comment]
@domaindrivendev do you care if we update the UI version?

**Comment by domaindrivendev** [comment]
@moserke @douglasrlee - as awesome as swagger-ui 3.x is, there's still known issues and feature gaps in comparison to 2.x.

Therefore, updating rswag to use it may result in an overall regression of functionality. Ideally, with any upgrade of the swagger-ui, I'd like to maintain feature parity and then some. So, I'm not convinced it's the right time to make this change right now.

However, the swagger-ui is essentially just set of static files (HTML, CSS, JS etc.) that you can easily expose with any web server (apache, nginx, even S3). So, it would be fairly trivial to host this yourself and just leverage rswag for the Swagger generation and corresponding Swagger JSON endpoint.

**Comment by grekko** [comment]
@domaindrivendev First of all: Thanks for your work.

>  as awesome as swagger-ui 3.x is, there's still known issues and feature gaps in comparison to 2.x

Can you elaborate on that point a little bit?

There seem to be at least also known [issues](https://github.com/swagger-api/swagger-ui/issues/2433) with displaying the response examples in 2.x which got resolved in 3.x and I dont see anyone working on a downstream fix for 2.x.

**Comment by yelvert** [comment]
Can this update happen now?

**Comment by sudoaza** [comment]
I'm also having issues with 2.x which seem to be resolved in 3.x, specifically when using objects as parameters the requests miss the parameter name and just posts the object. (this is inlining, references work though).

If the loss of functionality is too much maybe we can have a branch.

EDIT

There's a fork which supports 3.x, didn't fix my issue though.

**Comment by domaindrivendev** [comment]
Swagger UI 3.x was added by #121 (available in version 2.0.0 and above). Please give it a go and let me know if it works
