### ISSUE TITLE
[REQUEST] Develop for Ruby version 3.0.x

### ISSUE THREAD

**Issue by Zarthus** [rswag/rswag#624]
## Is your feature request related to a problem? Please describe.

Currently, rswag develops against ruby 2.7.6, which is EOL.

https://endoflife.date/ruby

https://github.com/rswag/rswag/blob/master/.ruby-version

https://github.com/rswag/rswag/blob/master/Dockerfile

## Describe the solution you'd like

Upgrading both to at minimum ruby 3.0.x should do :) 

## What support could we give you, so you could implement this yourself?

https://github.com/rswag/rswag/pull/625

## Describe alternatives you've considered

I haven't considered any alternatives.

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by romanblanco** [comment]
Closing the issue, as the PR has been merged and the changes will be released in v3.0
