### ISSUE TITLE
[BUG] Error constructing base_path_from_servers. Variables in server url are not replaced correctly. 

### ISSUE THREAD

**Issue by johannesengl** [rswag/rswag#626]
## Describe the bug

Error replacing placeholder parameters in server url in `swagger_docs`. 

Error message: 

```
Failure/Error: raise InvalidURIError, "bad URI(is not URI?): #{uri.inspect}"
          
          URI::InvalidURIError:
            bad URI(is not URI?): "://"
          # /Users/xxx/.rvm/gems/ruby-3.2.2/gems/rswag-specs-2.8.0/lib/rswag/specs/request_factory.rb:110:in `base_path_from_servers'
```

The issue is that the pattern provided to gsub matches the surrounding {}:
https://github.com/rswag/rswag/blob/5d77db93cecc2c2cabd93207049da67ae31756be/rswag-specs/lib/rswag/specs/request_factory.rb#L109

```
server[:url].gsub(/\{(.*?)\}/).to_a
=> ["{protocol}", "{defaultHost}"] // This is unexpected. It should match ["protocol", "defaultHost"] instead.
```

## Steps to Test or Reproduce

Configure swagger_docs in the following way: 

```
  config.swagger_docs = {
    'v1/swagger.json' => {
      openapi: '3.0.1',
      info: {
        title: 'API V1',
        version: 'v1'
      },
      paths: {},
      servers: [
        {
          url: '{protocol}://{defaultHost}',
          # TODO: This is a hack to get make replacing the variables in the url work.
          # Open PR to fix this upstream. 
          variables: {
            "protocol": {
              default: :https
            },
            "defaultHost": {
                default: 'www.example.com'
            }
          }
        }
      ]
    }
  }
```

## Expected behavior
No error and base url should be constructed correctly replacing the placeholders like `defaultHost` and `protocol` with the provided data under variables. 

## Dependency versions
The version of are you using for:
* Rswag: 2.8.0
* RSpec: 3.12.0
* Rails: 7.0.4
* Ruby: 3.2.2

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [x] OAS3.1

**Comment by romanblanco** [comment]
@johannesengl Thanks for submitting the issue! 

This was fixed in https://github.com/rswag/rswag/issues/601.
Updating gem to 2.9.0 will solve your issue.
