### ISSUE TITLE
[REQUEST] <Is rswag supporting expect { sth }.to change {  }.from().to() >

### ISSUE THREAD

**Issue by NgocHungWeploy** [rswag/rswag#635]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

## What support could we give you, so you could implement this yourself?
Please tell us how could we help you implement this feature, so you could
become a contributor. **Our time is limited, so it's unlikely that we will
be able to implement this ourselves, but we will try to help you**

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by romanblanco** [comment]
@NgocHungWeploy, please describe well the issue you are facing.
