### ISSUE TITLE
[REQUEST] How to split yaml to multiple files

### ISSUE THREAD

**Issue by arrowcircle** [rswag/rswag#641]
## Is your feature request related to a problem? Please describe.
How to properly support refs to external local files in manually generated yaml

I am using only rswag API and UI to serve manually generated yaml file, but I struggle to reference other files like:

```yaml
paths:
  $ref: "./paths/index.yaml"
```
But I get error:

```
No operations defined in spec!
```

## Describe the solution you'd like

I would like to have ability to split my spec to multiple files.

## What support could we give you, so you could implement this yourself?

I would like to know if this is possible currently and where to dig into (UI or API or where)? I am ready to open pull request as long as I understand where to dig.

## Describe alternatives you've considered
-

## Additional context
-

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [x] OAS3
- [ ] OAS3.1

**Comment by gaboluque** [comment]
Hey @arrowcircle , did you find a solution for this?

**Comment by arrowcircle** [comment]
Hey @gaboluque, it's actually according to the convention. I didn't manage to find a solution to put multiple paths into one file, but it's much better, than nothing.

`swagger.yaml`
```yaml
paths:
  /assets/{AssetId}/comments:
    $ref: ./paths/assets/comments.yaml
```
`comments.yaml`
```yaml
---
get:
  description: ...
    '200':
...
```

**Comment by ausangshukla** [comment]
Need better example of how to do this, the swagger.yaml is too large
