### ISSUE TITLE
[BUG] Auto generated examples not working

### ISSUE THREAD

**Issue by drvn-eb** [rswag/rswag#642]
## Describe the bug
Following the [Enable auto generation examples from responses](https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses) section from the README,  examples are not added to my swagger.yaml file after running `rake rswag:specs:swaggerize`

## Steps to Test or Reproduce
This does not generate examples in the yaml file:
```ruby
after do |example|
  content = example.metadata[:response][:content] || {}
  example_name = example.metadata[:example_name] || "test_example"
  example_spec = {
    "application/json" => {
      examples: {
        example_name.to_sym => {
          value: JSON.parse(response.body, symbolize_names: true)
        }
      }
    }
  }
  example.metadata[:response][:content] = content.deep_merge(example_spec)
end
    
response "401", "unauthorized" do
    schema type: :object,
      properties: {
        error: {type: :string}
      },
      required: ["error"]
    let(:Authorization) { "Bearer invalid credential" }
    run_test!(swagger_strict_schema_validation: true, example_name: :unauthorized)
  end
end
```

The examples are generated when I set them manually
```ruby
response "401", "unauthorized" do
  example "application/json", :unauthorized, {
    error: "You need to sign in or sign up before continuing."
  }
  schema type: :object,
    properties: {
      error: {type: :string}
    },
    required: ["error"]
  let(:Authorization) { "Bearer invalid credential" }
  run_test!(swagger_strict_schema_validation: true, example_name: :unauthorized)
end
```

## Expected behavior
Clarify the README documentation for auto generating examples and/or fix the issue.

## Dependency versions
The version of are you using for:
* Rswag: 2.9.0
* RSpec: 3.11
* Rails: 6.1.7.3
* Ruby: 3.0.5

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [x] OAS3
- [ ] OAS3.1

**Comment by drvn-eb** [comment]
`SWAGGER_DRY_RUN=0 rake rswag:specs:swaggerize` 🤦

**Comment by mzanini** [comment]
> SWAGGER_DRY_RUN=0 rake rswag:specs:swaggerize

lifesaver!
