### ISSUE TITLE
[REQUEST] Autogenerate response examples for the same response code

### ISSUE THREAD

**Issue by Quintasan** [rswag/rswag#651]
## Is your feature request related to a problem? Please describe.

My understanding of https://github.com/rswag/rswag/pull/501 is that I can call `example` multiple times in a `response` block and all of them will show up in the generated docs file. This will not, however, work with the example autogeneration.

I can apply https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses, but it will still disregard any other specs for the same error code.

## Describe the solution you'd like

Ideally, one could do something like this:

```ruby
response(422, "invalid parameters") do
  context "when user_id is missing" do
    let(:attendance) { { start_date: "2023-06-22"} }
    run_test!
  end

  context "when start_date is missing" do
    let(:attendance) { { user_id: 1} }
    run_test!
  end
end
```

And have the responses show as `<context name> in the `Examples` dropdown under a particular HTTP response code

## What support could we give you, so you could implement this yourself?
I have never written anything related to RSpec before, so ideally someone would point me which file this feature would go to

## Describe alternatives you've considered
I did consider grouping examples by return code, but I think this would be too complicated.

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [X] OAS3
- [ ] OAS3.1

**Comment by xkraty** [comment]
Hello,

I edited the documentation script to generate both request and response examples automatically by using your context description, I did add the following code in the `swagger_helper.rb` file:

```ruby
config.after do |example|
    next unless example.metadata[:rswag]

    summary = example.metadata[:example_group][:description]
    # save the response body as example
    content = example.metadata[:response][:content] || {}

    value = JSON.parse(response.body, symbolize_names: true) if response.body.present?

    example_spec = {
      'application/json' => {
        examples: {
          "#{summary}": {
            value:
          }
        }
      }
    }
    example.metadata[:response][:content] = content.deep_merge(example_spec) unless value.nil?
    next unless example.metadata[:operation][:parameters]

    # save the request payload as example
    example.metadata[:operation][:parameters].each.with_index do |param, i|
      value = send(param[:name])
      name = summary

      if param[:in] == :body
        # parameters in body require to be added to request_examples
        example.metadata[:operation][:request_examples] ||= []
        example.metadata[:operation][:request_examples] << { value:, summary:, name: }
      else
        # parameters in query, path, headers, etc.... require to be added to examples
        example.metadata[:operation][:parameters][i][:examples] ||= {}
        example.metadata[:operation][:parameters][i][:examples][name] = { value: }
      end
    end
  end
```

EDIT: In order to run spec and generate requests you also need to add to your configuration :
EDIT: non body params require to be added to examples definition

```ruby
  RSpec.configure do |config|
    config.swagger_dry_run = false
  end
```
Thanks @arinhouck for pointing it out

**Comment by arinhouck** [comment]
@xkraty Did you configure something else as well? The after block doesn't seem to run when using `rake rswag`. With some investigation it looks like it is related to --dry-run doesn't actually run specs. That is the only way I could get it to run is overriding.

EDIT: I think I realize now, you can configure `config.swagger_dry_run = false`.

**Comment by xkraty** [comment]
> @xkraty Did you configure something else as well? The after block doesn't seem to run when using `rake rswag`. With some investigation it looks like it is related to --dry-run doesn't actually run specs. That is the only way I could get it to run is overriding.
> 
> EDIT: I think I realize now, you can configure `config.swagger_dry_run = false`.

Yeah you right, sorry i forgot about that, I've edited my previous answer as well.

**Comment by xkraty** [comment]
> Hello,
> 
> I edited the documentation script to generate both request and response examples automatically by using your context description, I did add the following code in the `swagger_helper.rb` file:
> 
> ```ruby
> config.after do |example|
>     next unless example.metadata[:rswag]
> 
>     summary = example.metadata[:example_group][:description]
>     # save the response body as example
>     content = example.metadata[:response][:content] || {}
> 
>     value = JSON.parse(response.body, symbolize_names: true) if response.body.present?
> 
>     example_spec = {
>       'application/json' => {
>         examples: {
>           "#{summary}": {
>             value:
>           }
>         }
>       }
>     }
>     example.metadata[:response][:content] = content.deep_merge(example_spec) unless value.nil?
>     next unless example.metadata[:operation][:parameters]
> 
>     # save the request payload as example
>     example.metadata[:operation][:parameters].each.with_index do |param, i|
>       value = send(param[:name])
>       name = summary
> 
>       if param[:in] == :body
>         # parameters in body require to be added to request_examples
>         example.metadata[:operation][:request_examples] ||= []
>         example.metadata[:operation][:request_examples] << { value:, summary:, name: }
>       else
>         # parameters in query, path, headers, etc.... require to be added to examples
>         example.metadata[:operation][:parameters][i][:examples] ||= {}
>         example.metadata[:operation][:parameters][i][:examples][name] = { value: }
>       end
>     end
>   end
> ```
> 
> EDIT: In order to run spec and generate requests you also need to add to your configuration : EDIT: non body params require to be added to examples definition
> 
> ```ruby
>   RSpec.configure do |config|
>     config.swagger_dry_run = false
>   end
> ```
> 
> Thanks @arinhouck for pointing it out


Updated code to automatically add non-body params to examples

<img width="1426" alt="Screenshot 2023-09-24 at 09 57 47" src="https://github.com/rswag/rswag/assets/1638403/2abd2857-19d8-4678-b783-4c03b4e58751">

**Comment by Shinta** [comment]
I implemented this successfully but the --dry-run part was a problem, I ended up creating my rake task with the command: `RAILS_ENV=test bundle exec rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined` in order to make this work, great solution, many thanks @xkraty
