### ISSUE TITLE
[BUG] TypeError when viewing docs

### ISSUE THREAD

**Issue by jdudley1123** [rswag/rswag#665]
## Describe the bug
API docs UI will not load because of a TypeError. Part of Rswag's code is:

```
unless filename.start_with? @config.resolve_swagger_root(env)
  return @app.call(env)
end
```

This was changed in https://github.com/rswag/rswag/pull/654/commits/fc353ef558271765390a519bcc12641359fab5e7 as part of https://github.com/rswag/rswag/pull/654 in release 2.10.0. `@config.resolve_swagger_root(env)` returns a Pathname that used to be cast as a string, but isn't anymore. `start_with?` expects a String argument, but now gets a Pathname instead, causing the TypeError. This should be fixable by adding `.to_s` or similar to cast it back into a string.

## Steps to Test or Reproduce
Rswag is mounted on the `/api-docs` route.

Visit `/api-docs` and see:
```
TypeError at /index.html
no implicit conversion of Pathname into String

rswag-api (2.10.1) lib/rswag/api/middleware.rb:19
      def call(env)
        path = env['PATH_INFO']
        # Sanitize the filename for directory traversal by expanding, and ensuring
        # its starts with the root directory.
        filename = File.expand_path(File.join(@config.resolve_swagger_root(env), path))
        unless filename.start_with? @config.resolve_swagger_root(env)
          return @app.call(env)
        end
        if env['REQUEST_METHOD'] == 'GET' && File.file?(filename)
          swagger = parse_file(filename)
```

## Expected behavior
There should not be an error

## Additional information
As an aside, there's also a type in the comment in the code `# its starts with` should be `# it starts with`

## Dependency versions
The version of are you using for:
* Rswag: 2.10.1 (API) and 2.10.1 (UI)
* RSpec: 3.12.2
* Rails: 6.1.7.4
* Ruby: 3.0.0

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [x] OAS3
- [ ] OAS3.1

**Comment by mkllnk** [comment]
I just ran into the same problem. I can confirm that adding `.to_s` works:

```diff
-        unless filename.start_with? @config.resolve_swagger_root(env)
+        unless filename.start_with? @config.resolve_swagger_root(env).to_s
```

**Comment by nazeefahmadmeer** [comment]
Ran into the same problem, thanks for getting the fix up and merged already. Any chances of this getting released soon?

Edit: If anyone else is getting the same, alternatively when assigning `swagger_root` config instead of a path, convert that to a string to avoid the error e.g

```
Rswag::Api.configure do |c|
    c.swagger_root = Rails.root.join('swagger').to_s
end
```

**Comment by romanblanco** [comment]
Closing, as this was released in https://github.com/rswag/rswag/releases/tag/2.11.0
