### ISSUE TITLE
[REQUEST] Improve strict schema validation

### ISSUE THREAD

**Issue by romanblanco** [rswag/rswag#666]
## Is your feature request related to a problem? Please describe.
https://github.com/rswag/rswag/pull/604#issuecomment-1641941197

## Describe the solution you'd like
Use `allPropertiesRequired` and `noAdditionalProperties` options for json-schema gem implemented in https://github.com/voxpupuli/json-schema/pull/494.

## Relates to which version of OAS (OpenAPI Specification)
- OAS3
- OAS3.1

**Comment by romanblanco** [comment]
https://github.com/rswag/rswag/pull/659 addresses same issue as https://github.com/rswag/rswag/pull/675

**Comment by a-lavis** [comment]
@romanblanco is this issue resolved?  As I understand it, we now have access to `allPropertiesRequired` and `noAdditionalProperties` from `rswag-specs`, but we aren't actually using them, right?

I have a draft branch up here with what I think the changes would have to look like for this issue to be resolved: 
https://github.com/rswag/rswag/compare/master...a-lavis:rswag:allow_any_json_schema_params

**Comment by romanblanco** [comment]
@a-lavis you're right. It's just unblocked, not closed. Thanks!

**Comment by IlkhamGaysin** [comment]
@romanblanco 
@a-lavis 
hi guys, I've added two more options to keep the restrictions up to date, please take a look. 
Thanks
https://github.com/rswag/rswag/pull/721
