### ISSUE TITLE
[REQUEST] upgrade `json-schema` support to 4.0

### ISSUE THREAD

**Issue by bvogel** [rswag/rswag#669]
## Is your feature request related to a problem? Please describe.
Currently `json-schema` is restricted in the gemspec to be `>= 2.2, < 4.0`. 

## Describe the solution you'd like
change limit on `json-schema` be either `>= 2.2, < 5.0` or. `>= 2.2`

## What support could we give you, so you could implement this yourself?
breaking for 4.0 is:
- Removed `data` ivar from JSON::Validator so that multiple validate call become faster

I can't seem to find the usage of said ivar. Where would I need to look?

## Describe alternatives you've considered
stick with the older version?

## Additional context
we use schema validations for our API so keeping up to date with the latest version would be desirable as additionally there seems no support for older versions

**Comment by romanblanco** [comment]
The upgrade was merged and will be released in the next version.

**Comment by bvogel** [comment]
Thank you so much!
