### ISSUE TITLE
[BUG] Example group metadata does not support symbol shorthand

### ISSUE THREAD

**Issue by franzliedke** [rswag/rswag#674]
## Describe the bug
The custom example groups in RSwag (for example `response`) do not support [symbol-style example metadata](https://rspec.info/features/3-12/rspec-core/metadata/user-defined/).

## Steps to Test or Reproduce
Example spec:

```ruby
response "201", "article created", :skip_bullet do
  # ...
end
```

This is perfectly valid in RSpec, but leads to the following error inside RSwag:

```
NoMethodError:
  undefined method `[]=' for :skip_bullet:Symbol
```

## Expected behavior

The spec should be equivalent to the following, which works just fine:

```ruby
response "201", "article created", skip_bullet: true do
  # ...
end
```

## Additional context
This became a problem with the new `MetadataStyle` cop in rubocop-rspec, which has support for two enforced styles, `hash` or `symbol`.

Rubocop understands that `response` defines an example group with the following config:
```yaml
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - response
```

## Dependency versions
The version of are you using for:
* Rswag: 2.9.0
* RSpec: 3.12
* Rails: 7.0.8
* Ruby: 3.2.2

## Relates to which version of OAS (OpenAPI Specification)
Not related to OAS

**Comment by perfetti** [comment]
This seems a user issue, symbol-style example metadata which is `:foo => :bar`, as that is shorthand for a hash.  `{ foo: }` could also be acceptable as a hash assuming you've defined a value for `foo` earlier in the code.

You'll notice in the link you posted the syntax is `:foo => :bar`

Using `:foo` means you're passing purely a symbol and not a hash. Hence the error.
