### ISSUE TITLE
[BUG] Old swagger-ui-dist "4.1.3" in gem node modules instead of "5.9.4"

### ISSUE THREAD

**Issue by reneweteling** [rswag/rswag#699]
## Describe the bug
when installing the rswag-ui-2.11.0 the node_modules of version 4.1.3 are there instead of "swagger-ui-dist": "5.9.4" that is promised here https://github.com/rswag/rswag/blob/master/rswag-ui/package.json

![image](https://github.com/rswag/rswag/assets/3830933/ed6a9024-d425-4063-a512-9d3d08744428)

My guess is that something in the gem deployment pipeline isn't fetching all the new node modules.

**Comment by romanblanco** [comment]
@reneweteling, the changes are in `master`, but were not released yet in the gem version.

I plan to release the changes soon. In the meantime, you can point the gem to `master` branch to workaround the problem temporarily.

**Comment by romanblanco** [comment]
@reneweteling, FYI: https://github.com/rswag/rswag/releases/tag/2.12.0

**Comment by reneweteling** [comment]
> @reneweteling, FYI: https://github.com/rswag/rswag/releases/tag/2.12.0

Nice first thing I'll do Monday :)

**Comment by reneweteling** [comment]
Awesome it works!!

One question though what is the propper way to config the UI, I've done it like this, but no clueue if this is the correct way, it feels a bit dirty

```ruby
Rswag::Ui.configure do |c|
  c.swagger_endpoint '/api-docs/v1/swagger.json', 'v1'
  c.config_object.merge!({
                           deepLinking: true,
                           filter: true,
                           syntaxHighlight: {
                             activate: true,
                             theme: 'monokai'
                           },
                           tryItOutEnabled: true,
                           persistAuthorization: true
                         })
end
```
