### ISSUE TITLE
[BUG] Depreciation warning adding noise to test runs

### ISSUE THREAD

**Issue by tgxworld** [rswag/rswag#703]
## Describe the bug

Usefulness of new deprecation warnings added. 

## Steps to Test or Reproduce

In https://github.com/rswag/rswag/pull/688, deprecation warnings were added to various methods which the gem itself depends on and it causes the warnings to be logged in test runs adding noise to the output. 

## Expected behavior

Since there is no replacement for the existing methods which will be renamed, I don't think there is a need to print out the deprecation message since there is nothing the end user can do. 

## Dependency versions
The version of are you using for:
* Rswag: 2.12.0
* RSpec: 3.12.0
* Rails: 7
* Ruby: 3.2

**Comment by hs-arodrigues** [comment]
+1 to this

**Comment by alexcastrodev** [comment]
+1

**Comment by davidwessman** [comment]
Could you cut a new release with this change? 🙏🏻

**Comment by romanblanco** [comment]
@davidwessman The fix was alreaday released in [2.13.0](https://github.com/rswag/rswag/releases/tag/2.13.0)

**Comment by davidwessman** [comment]
> @davidwessman The fix was alreaday released in [2.13.0](https://github.com/rswag/rswag/releases/tag/2.13.0)

Ah, I misread and now realize only one of the rswag-packages had updated to 2.13...
