### ISSUE TITLE
Pattern change

### ISSUE THREAD

**Issue by douglasrlee** [rswag/rswag#73]
I know that you can change the pattern when running the specs but it does not look like you can change the pattern when you want run the swaggerize rake task.

IE: I want to store the swagger specs in `/spec/swagger/`

**Comment by domaindrivendev** [comment]
`rswag:specs:swaggerize` is just a wrapper around an rspec command.

For the flexibility you need, just call the rspec command directly.

```
rspec spec/swagger --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
```
