### ISSUE TITLE
Authorization Headers

### ISSUE THREAD

**Issue by jonstorer** [rswag/rswag#74]
I'm running into an issue between rswag integration tests & adding swagger `securityDefinitions`. I can either have rswag integration tests work OR Swagger UI docs work.

My controllers all required an authorization header. I've manually added those as params in each integration test:

```ruby
parameter({
  :in => :header,
  :type => :string,
  :name => :Authorization,
  :required => true,
  :description => 'Client token'
})
...
let(:Authorization) { 'Bearer ' + generate_token }

run_test!
```
specs pass!

When I move to the `security` helper:

```ruby
security [ { :client => [] } ]
...
let(:Authorization) { 'Bearer ' + generate_token }
```
The Authorization header is not added added for the integration spec and the spec fails.

I've attached an example:

This passes
```ruby
RSpec.describe 'Session' do
  path '/sessions' do
    post 'create' do
      tags 'Session'

      consumes 'application/json'
      produces 'application/json'

      # here
      parameter({
        :in => :header,
        :type => :string,
        :name => :Authorization,
        :required => true,
        :description => 'Client token'
      })

      response '201', 'created' do
        # this header is included
        let(:Authorization) { 'Bearer ' + generate_token }

        schema({ '$ref' => '#/definitions/responses/session' })

        run_test!
      end
    end
  end
end
```

this fails
```ruby
config.swagger_docs = {
  'v1/swagger.json' => {
    :swagger => '2.0',
    :info => {
      :title => 'My Api',
      :version => 'v1',
      :description => 'our docs'
    },
    :schemes => [ 'http' ],
    :host => 'localhost:3000',
    :basePath => '/v1/',
    :definitions => [],
    :securityDefinitions => {
      # here
      :client => {
        :in => :header,
        :name => :Authorization,
        :type => 'oauth2',
        :require => true,
        :description => 'Client Token',
        :tokenUrl => 'http://localhost:5000/auth/token',
        :flow => 'application',
        :scopes => { }
      }
    }
  }
}

RSpec.describe 'Session' do
  path '/sessions' do
    post 'create' do
      tags 'Session'

      # here
      security [ { :client => [] } ]

      consumes 'application/json'
      produces 'application/json'

      response '201', 'created' do
        # this header won't be included
        let(:Authorization) { 'Bearer ' + generate_token }

        schema({ '$ref' => '#/definitions/responses/session' })

        run_test!
      end
    end
  end
end
```

Swagger UI works great with the `security` helper & defined `securityDefinitions`. But specs won't pass. When I configure rswag for specs to pass, swagger UI doesn't auto fill the Authorization header. When I configure rswag for swagger-ui to work, rswag specs don't include the Authorization header & specs fail. 

In this clip, specs are passing, I'm using the `security` helper, I've manually defined the Authorization header, & I've defined `securityDefinitions`. (I'm pretty sure I'm not supposed to do all of those). But it's the only way I can get specs to pass & get swagger docs to work --- kinda.

Since I've manually defined the Authorization header, I have to add a value to it. Even though swagger UI will do that globally.

![swagger2](https://user-images.githubusercontent.com/104508/27811389-db6c8650-6033-11e7-8aea-69b9d8418969.gif)

**Comment by hc2p** [comment]
We have the following working:

in swagger_helper.rb
```
      securityDefinitions: {
        Bearer: {
          description: "...",
          type: :apiKey,
          name: 'Authorization',
          in: :header
        }
      },
```

in the request specs:
```
  path "/resource_123" do
    post "create a resource 123" do
      consumes "application/json"
      security [Bearer: {}]

      response "201", "Resource 123 created" do
        let(:"Authorization") { "Bearer #{token_for(user)}" }
        ....
      end
    end
   end
```
No extra Authorization header needed in here.

Then in the swagger-ui we can use "login", where you need to fill in a value of `Bearer <token-value>`.

**Comment by jonstorer** [comment]
@hc2p that method works, though it lose all the oauth2 flow goodness swagger provides. And now I’m looking at building a “token fetcher” of sorts. ¯\_(ツ)_/¯ It just be nice if it worked like it was supposed to. 

I'm not closing this issue because the problem isn't solved, I'm just using a workaround.

**Comment by domaindrivendev** [comment]
@jonstorer - please take a look at #71. It's already been merged but hasn't been released to rubygems yet. In a nutshell, it adds support for _securityDefinitions_ so long as you're using one of the standard schemes defined by Swagger - _apiKey_, _basic_ and _oauth2_. For _basic_ and _oauth2_ it automatically sends an _Authorization_ header with integration tests, expecting the value to be set via "let(:Authorization) {}". This will allow you to define oauth2 schemes correctly and therefore avail of the integrated flows that ship with the swagger-ui.

Stay tuned for a release. In the meantime, it would be awesome if you could reference the latest code and try it our prior to releasing.

**Comment by jonstorer** [comment]
@domaindrivendev I'll check that out. Is the readme updated on master?

**Comment by domaindrivendev** [comment]
Full support for _securityDefinitions_ available as of rswag 1.4.0. See [readme](https://github.com/domaindrivendev/rswag#specifyingtesting-api-security) for details.

**Comment by zlesnr** [comment]
I'm trying to get the authorization working for testing our api and get 401 back from all endpoints.

I've currently got the config, commented earlier as working:

```
  config.swagger_docs = {
    'v1/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'API V1',
        version: 'v1'
      },
      paths: {},
      securityDefinitions: {
        Token: {
          description: "...",
          type: :apiKey,
          name: 'Authorization',
          in: :header
        }
      },
    }
  }
```

In my test, I have the following.

```ruby
    get 'Retrieves a device' do
      security [Token: {}]
      tags 'Device'
      produces 'application/json', 'application/xml'
      parameter name: :fqdn, :in => :path, :type => :string

      response '200', 'device found' do
        schema type: :object,
          properties: {
            fqdn: { type: :string },
          },
          required: [ 'fqdn' ]

        let(:fqdn) { Device.create! FactoryGirl.build(:device).attributes }
        api_key = ApiKey.create! FactoryGirl.build(:api_key).attributes
        let(:Authorization) { "Token token=\"#{api_key.access_token}\"" }
        run_test!
      end

      response '404', 'device not found' do
        let(:fqdn) { 'invalid' }
        api_key = ApiKey.create! FactoryGirl.build(:api_key).attributes
        let(:Authorization) { "Token token=\"#{api_key.access_token}\"" }
        run_test!
      end
    end
```

Any pointers on how I might get the authorization token to pass?  Its also possible that the token is being passed, but I'm declaring an invalid token by generating one, but I'm unsure how to debug.  Any pointers on how to debug this issue would be appreciated.

**Comment by domaindrivendev** [comment]
@zlesnr - at an initial glance, I think your security requirement specification (at the operation level) is slightly incorrect. It should be "security [ Token: [] ]" instead of "security [ Token: {} ]". This may well be your problem.

Regarding debugging - what are you using in your Rails app to implement the API key authentication, regardless of rswag. Seems like this is where you would want to add some debugging code. I would start by looking at request.headers to inspect the AUTHORIZATION header and see what value is in fact being passed.

**Comment by domaindrivendev** [comment]
Interested to hear how you get on as this is an freshly released feature - keep me posted :)

**Comment by zlesnr** [comment]
The API work looks to be done in devise, but if I add a `binding.pry` immediately lbefore the authentication call to `authenticate_or_request_with_http_token`, I see that headers contains the following.

```
[3] pry(#<Api::V1::SearchController>)> headers
=> {"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff"}
```
No `Authorization` header makes it into the request.  I do see in our other rspec tests for the API (which do not call through http, but rather just call the methods directly) that we have the following to get the header correct.

```
headers = { :Authorization => "Token token=\"#{api_key.access_token}\"" }
request.headers.merge! headers
```

That was necessary for us, but I think (at least in part) its required to work around a bug.  https://github.com/rspec/rspec-rails/issues/1655

Now that I can see the headers don't contain the `Authorization` header, is there something else that I need to do on the rswag side to ensure the header gets set?  I looked over the docs again, but didn't see what I missed.

**Comment by zlesnr** [comment]
Perhaps I'm confused about how the securityDefinition is supposed to be used.  I'm new to swagger also, so that is likely contributing to my failure here.

Is the definition of the securityDefinition in `swagger_helper` combined with `security` called in the test expected to result in an extension of the headers during the test?

Using more Pry to determine what is available and when, calling `security` only seems to return an array, but I don't see any other impact to the environment here.

`security [{Token: []}]` returns `[{:Token=>[]}]`.  Is that valid?  How do I know it did the correct thing?  Did it discover the securityDefinition accurately and inject the referenced header?  These are my initial questions I'm running in to.

This is all in an effort to use rswag to test the API initially, but once passing, to build docs as well.  Please let me know if I'm missing something here.

**Comment by domaindrivendev** [comment]
@zlesnr - you're correct, the securityDefinition in `swagger_helper` combined with `security` called in the test is expected to result in an extension of the headers during the test?

For some reason, it seems the intersection of these isn't being picked up correctly during the test preparation. To confirm this is where the issue lies, you can uncomment all of the lines where you assign the `:Authorization` value (i.e the let blocks) and rerun the test. If you see "undefined method 'Authorization' for ..." then the security requirement is being picked up correctly during the test and this is just rswag trying to retrieve the required :Authorization value for the given example. If you don't see this ... then the security requirement (for the operation) is not being picked up and this is likely due to some subtle issue with the combination of `securityDefinition` and `security`

Unfortunately, I'm unable to repro this locally. I assume you're definitely using the latest version - 1.3.0?

**Comment by domaindrivendev** [comment]
Here's the code where the intersection happens:

```ruby
def applicable_security_schemes
  # First figure out the security requirement applicable to the operation
  requirements = @api_metadata[:operation][:security] || @global_metadata[:security]
  scheme_names = requirements ? requirements.map { |r| r.keys.first } : []

  # Then obtain the scheme definitions for those requirements
  (@global_metadata[:securityDefinitions] || {}).slice(*scheme_names).values
end
```

**Comment by zlesnr** [comment]
@domaindrivendev Looks like I've been using 1.4.0.  I'll comment some bits and test as you suggest.

**Comment by zlesnr** [comment]
If I comment out the let block, I see the undefined method error for 'Authorization'.  So it appears that the variable from the securityDefinition is at least being read.

**Comment by zlesnr** [comment]
Thank you for the leading questions @domaindrivendev.  I believe the issue I'm running into is entirely with our code.  I'm narrowing in on where.  I appreciate the assistance.

**Comment by developius** [comment]
I know this is an old thread, but I've tried all the different methods here and can't seem to make this work. I've got JWT setup with Devise in my app but _always_ receive a 401 response. It's very hard to debug what the exact message is because I don't seem to be able to access the response inside the specs (any suggestions on how to do that?). This setup is working in the swagger UI, so I guess it's generating the correct JSON for that.

```rb
config.swagger_docs = {
  'v1/swagger.json' => {
    swagger: '2.0',
    info: {
      title: 'API V1',
      version: 'v1'
    },
    paths: {},
    securityDefinitions: {
      Bearer: {
        type: :apiKey,
        description: 'Bearer token',
        name: 'Authorization',
        in: :header
      }
    }
  }
}
```

```rb
path '/v1/users/{id}' do
    get 'Retrieves a user' do
      tags 'Users'
      produces 'application/json'
      parameter name: :id, in: :path, type: :integer
      security [Bearer: []]

      let(:user) { FactoryBot.create(:user) }
      let(:id) { user.id }
      let(:Authorization) { auth_header(user) }
      # for some reason, the API is rejecting this. How to inspect request?

      response '200', 'user found' do
        schema type: :object,
               properties: {
                 email: { type: :string }
               },
               required: %w[email]

        run_test!
      end

      response '404', 'user not found' do
        let(:id) { 'invalid' }
        run_test!
      end

      response '406', 'unsupported accept header' do
        let(:Accept) { 'application/foo' }
        run_test!
      end
    end
  end
```

I also have a standard request spec which is **passing**:

```rb
RSpec.describe 'Users API', type: :request do
  let!(:users) { create_list(:user, 10, :confirmed) }
  let(:user_id) { users.first.id }
  let(:headers) { auth_headers(users.first) }

  describe 'GET /users' do
    context 'as an authenticated user' do
      before { get users_path, headers: headers }

      it 'returns status code 200' do
        expect(response).to have_http_status(200)
      end

      it 'returns a successful response' do
        expect(json['success']).to eq(true)
      end

      it 'returns users' do
        expect(json['result']).not_to be_empty
        expect(json['result'].size).to eq(10)
      end
    end
  end
end
```

`auth_header` returns a string like this (tested): 
```
Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4YTQ0NzdjYi1jZDRmLTRlMzQtOGJjOC1mYjg0NDk4OTBhMjAiLCJzdWIiOiI0Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTQxNTMzMzA3LCJleHAiOjE1NDE2MTk3MDd9.fwDXqZgAKiCBsKovb8YN-PTGwfR0VMhJ7EoWurybNXg
```
`auth_header` (note the plural) returns:
```
{"Authorization"=>"Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4YTQ0NzdjYi1jZDRmLTRlMzQtOGJjOC1mYjg0NDk4OTBhMjAiLCJzdWIiOiI0Iiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTQxNTMzMzA3LCJleHAiOjE1NDE2MTk3MDd9.fwDXqZgAKiCBsKovb8YN-PTGwfR0VMhJ7EoWurybNXg"}
```

I've also tried adding a `before_action` to the application controller before any auth happens and it looks like the header is never set, which aligns with the error coming back 401 - can't see response body as noted above.

```rb
class ApplicationController < ActionController::API
  before_action :debug

  def debug
    byebug
  end
end
```

```rb
(byebug) request.env['Authorization']
nil
```

**Comment by lstone** [comment]
Can confirm - I ALWAYS receive a 401 w/ Devise JWT setup too. Some info on how to debug would be greatly appreciated.

**Comment by x1wins** [comment]
I have same issue

**Comment by x1wins** [comment]
i change gem 'rswag' to gem 'rspec-rails-swagger'
and solved
https://github.com/drewish/rspec-rails-swagger

spec/requests/posts_spec.rb
```ruby
require 'swagger_helper'

RSpec.describe 'posts', type: :request do

  let(:user) { create(:user) }
  let(:category) { create(:category, user_id: user.id) }
  let(:posts) { create_list(:post, 30) }
  let(:headers) { authenticated_header(user.id) }
  let(:token) { authenticated_token(user.id) }
  let(:token_invalid) { 'invalid_token' }

  describe "GET #index" do
    it "returns a success response" do
      get api_v1_posts_path, params: {category_id: category.id}, headers: headers
      expect(response).to be_successful
    end
  end

  # Path Item Object
  path '/api/v1/posts' do
    parameter 'Authorization', {in: :header, type: :string}
    parameter 'body', {in: :body, required: true, schema: {
        type: :object,
        properties: {
            category_id: { type: :integer }
        }
      }
    }
    let (:body) {
      { category_id: category.id}
    }

    operation "GET", summary: "fetch list" do
      let(:'Authorization') { "Bearer #{token}" }
      response 200, description: "successful"
    end

    operation "GET", summary: "fetch list" do
      let(:'Authorization') { "Bearer #{token_invalid}" }
      response 401, description: "unathorize"
    end
  end

end
```

**Comment by jaydorsey** [comment]
@developius In your working request spec example, you've created your user with a `:confirmed` trait, but in the integration test you didn't pass that trait in. Could that be the cause of the failure in the integration test?

> for some reason, the API is rejecting this. How to inspect request?

I've had success with debugging integration specs by using the alternative syntax instead of `run_test!`

    before do |example|
     # inspect what you're sending before you send it here
      submit_request(example.metadata)
    end

    it do
      # inspect the response here, but also any of the other stuff like request.url
    end

**Comment by Paxa** [comment]
Seems like rswag support only few headers that can be customized https://github.com/domaindrivendev/rswag/blob/ef91e087d3332c5105a1b1601093517fc434e5bb/rswag-specs/lib/rswag/specs/request_factory.rb#L102

We can add missing feature:
```rb
class Rswag::Specs::RequestFactory
  alias_method :orig_add_headers, :add_headers

  def add_headers(request, metadata, swagger_doc, parameters, example)
    orig_add_headers(request, metadata, swagger_doc, parameters, example)

    if example.respond_to?(:extra_headers)
      request[:headers].merge!(example.send(:extra_headers))
    end
  end
end
```

Then use it in your tests:
```rb
let(:extra_headers) {
  api_client = create_new_api_key(...)
  {
    'API-Key'    => api_client.client_id,
    'API-Secret' => api_client.api_secret
  }
}
```

---

btw imo rswag dsl is too much magic, so hard to get it right without looking into code. Any plans to make more simple interface? May be something like this

```rb
describe "Cats API" do
  include Rswag::TestHelpers
  rswag_type :Cat, properties: {
                      id: { type: :integer, },
                      name: { type: :string },
                      photo_url: { type: :string },
                      status: { type: :string }
                    }

  before do
    set_header("User-Agent", "Miau!")
  end

  context "/api/cats" do # or context("List cats", path: "/api/cats", tags: [:cats, :pets])
    it "list all cats" do  # "list all cats" will be in summary field
      create_10_cats
      rswag(:get,
        description: "List all the cats current user can see",
        operation: "blabla",
        tags: [:cat],
        response: {code: 200, body: [:Cat], headers: {"User-Agent": "Miau!"}}
      )
    end

    it "creates cat" do
      cat_params = FactoryGirl.attributes_for(cat)
      rswag(:post, request: {parameters: :Cat, body: cat_params}, response: {code: 201, body: :cat})
    end
  end
end
```

**Comment by elijahmurray** [comment]
@jonstorer How were you creating your `generate_token` method? I've tried so many different ways to generate my bearer token and none of them pass through successfully and auth.

```
@user = FactoryBot.create(:user)
let(:Authorization) { "Bearer #{@user.create_new_auth_token['access-token']}" }
```

**Comment by Petercopter** [comment]
I was able to get JWT working quickly using the solution @hc2p posted. I would recommend dropping a `binding.pry` or something in the code where you are having problems, and inspect
`headers` and `params` to see what you're getting.

**Comment by kwitczak** [comment]
Solution of @hc2p started working for me, once I changed `openapi: '3.0.1'`, to `swagger: '2.0'` inside `config.swagger_docs`. 

To make it work for `openapi: '3.0.1', use new notation in `config.swagger_docs`:
```ruby
      components: {
        securitySchemes: {
          Bearer: {
            description: 'JWT key necessary to use API calls',
            type: :apiKey,
            name: 'authorization',
            in: :header
          }
        }
      }
```

**Comment by mkhoa1412** [comment]
@developius , @lstone, @x1wins I had same issue with Bearer. Passed on swag-ui but all rspec failed. 
Did you fix it and how ?

**Comment by helmiItsavirus** [comment]
@mkhoa1412 I never using this gem but I had experience about JWT problem in sometimes, I think you need to check your JWT to https://jwt.io/
check the scope of the user. 

Note:
If the Bearer token successfully sent but still get 401.

**Comment by momnanaseer** [comment]
I was using wrong name for auth token in swagger helper I was using Bearer for security and in spec file I was using BearerAuth, that's why it gives me nil every time.
My swagger helper code:
```
securityDefinitions: {
        **Bearer**: {
          description: 'Bearer Token',
          type: :apiKey,
          name: 'Authorization', :in => :header
          # name: 'Authorization', in: :header
        }
      }
```

My specs file code:

`security [**Bearer**: []]`
