### ISSUE TITLE
[REQUEST] Add support for deep_linking

### ISSUE THREAD

**Issue by DiannaTz** [rswag/rswag#750]
## Is your feature request related to a problem? Please describe.
Swagger UI supports a 'deepLinking=true' configuration parameter. However, this option is not configurable within this gem, and the default value set by Swagger is 'false'. I would greatly appreciate having the ability to utilize this configuration.

## Describe the solution you'd like
A nice-to-have solution would be to simply add the following code to config/initializers/rswag_ui.rb
```
Rswag::Ui.configure do |c|
  c.deep_linking = true
end
```

## What support could we give you, so you could implement this yourself?
Just let me know if this request is ok with you and I will try to do it by myself.

## Describe alternatives you've considered
Don't have at the moment any other alternatives. I did not get the change to look over the entire code and find other potential solutions.

## Additional context
N/A

## Relates to which version of OAS (OpenAPI Specification)
- [x] OAS2
- [x] OAS3
- [x] OAS3.1

**Comment by elthariel** [comment]
That doesn't seem like a huge change ? Can't you send a PR ? :)

**Comment by zhuravel** [comment]
@DiannaTz This is what I’m currently using in my project.

```ruby
Rswag::Ui.configure do |c|
  c.config_object[:deepLinking] = true
end

**Comment by DiannaTz** [comment]
Thank you @zhuravel .I don't know how i missed this. It indeed works. Closing this request now
