### ISSUE TITLE
[BUG] Unable to auto-generate request parameters example and response example

### ISSUE THREAD

**Issue by pdkproitf** [rswag/rswag#754]
## Describe the bug
I'm able to see the request example and response example captured via the hook (after {}). However, they are not added to the API docs

## Expected behavior
Should able to see the request example and response example in API docs

## Screenshots
![Screenshot 2024-06-12 at 11 56 55](https://github.com/rswag/rswag/assets/12691828/dd2a2ef0-9252-4d8f-9c31-7f4e877172c5)
![Screenshot_2024-06-12_at_11_59_01](https://github.com/rswag/rswag/assets/12691828/51f9d80f-3656-4672-9ed3-fe97b1fcbc86)

## Dependency versions
The version of are you using for:
* Rswag: 2.13.0
* RSpec: 3.0
* Rails: 6.0.3
* Ruby: 2.6

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by pdkproitf** [comment]
Please help to have a look, Many thanks!

**Comment by pratikgadhave** [comment]
@pdkproitf please add “produces ‘application/json’ after post block. Same is mentioned in documentation. Hope this helps.

**Comment by pdkproitf** [comment]
Thank for your response @pratikgadhave 
I found the root cause: the rswag_dry_run configuration was not respected.. https://github.com/rswag/rswag/issues/359

**Comment by pdkproitf** [comment]
btw, Is it possible to capture auto-generate request QUERY parameters example?
Thanks!
