### ISSUE TITLE
[REQUEST] Add support for Rails 7.2 in rswag ui

### ISSUE THREAD

**Issue by rmatovu987** [rswag/rswag#764]
## Is your feature request related to a problem? Please describe.
We are starting a new project this week, and the plan is to use rails 7.2. We heavily use the rswag gem, however, there is an issue regarding rswag-ui. It doesn't support rails 7.2.

We are also in the process of upgrading existing projects to the latest versions, but this is a blocker.

## Describe the solution you'd like
Add support for rails 7.2 in rswag-ui.

**Comment by JulienDefrance** [comment]
Thank you @rmatovu987 and @zhuravel / This fix is urgently needed given today's release of Rails 7.2.0: https://edgeguides.rubyonrails.org/7_2_release_notes.html
