### ISSUE TITLE
Improve check for JSON content type

### ISSUE THREAD

**Issue by romanblanco** [rswag/rswag#768]
Current check is too simplistic to consider all valid json types. For example, the JSON:API content type is [application/vnd.api+json](http://www.iana.org/assignments/media-types/application/vnd.api+json)

_Originally posted by @hasghari in https://github.com/rswag/rswag/pull/639#discussion_r1715933244_

**Comment by hasghari** [comment]
I just created #769 to fix this issue.

**Comment by kwent** [comment]
@hasghari Thanks! Was just running into this issue
