### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by klobuczek** [rswag/rswag#77]
rswag depends on rswag-specs
rswag-specs requires ''rspec/core' without defining the dependency in gemspec
rswag seems to inject itself into default Rakefile
when run in non test enviroment where rspec-core is  not present this causes an error
```
Step 10/11 : RUN RAILS_ENV=docker bundle exec rake assets:precompile
 ---> Running in 7e0706635cc5
rake aborted!
LoadError: cannot load such file -- rspec/core
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/rswag-specs-1.4.0/lib/rswag/specs.rb:1:in `<top (required)>'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/rswag-1.4.0/lib/rswag.rb:1:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/var/www/org-api/current/config/application.rb:13:in `<top (required)>'
/var/www/org-api/current/Rakefile:4:in `require_relative'
/var/www/org-api/current/Rakefile:4:in `<top (required)>'
/var/www/org-api/current/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by domaindrivendev** [comment]
Yep - this is an interesting one. If I include _rspec_ in any of the gemspecs it will be added to the application's runtime dependencies and this would be undesirable as it would never be used after initial dev/testing.

In fact _rswag-specs_ itself shouldn't even be added to the application's runtime dependencies. On the one-hand, I like the idea of a single gem (i.e. _rswag_) that pulls in the complete toolchain. But the downside is that there's no way (at least with my understanding of the Gemfile/gemspec interaction) to say which components should be dev/test vs runtime. You can work around this by avoiding the top-level package and pulling in each component in your Gemfile under the appropriate group:

```ruby
# Gemfile
gem 'rswag-api'
gem 'rswag-ui'

groups :test do
  gem 'rspec-rails'
  gem 'rswag-specs'
end
```

But this is just a workaround and I would like to address the bug you've reported. Interested to get other's thoughts?

**Comment by domaindrivendev** [comment]
Perhaps keep it as an assumed dependency (i.e. out of the gemspec) and then put some conditional logic to check Rails.env and only require the relevant code if it's "development" OR "test"?

**Comment by klobuczek** [comment]
I think you might have not separated sufficiently the subgems. If rswag-specs has any functionality that should ever be run in any other environment than test then this part should be moved to a different subgem. That subgem should not have dependency on any rspec. What depends on rspec must ever only run in test environment. The idea of having 1 super gem encompassing everything is flawed. Nearly all prominent gems have a main gem and in documentation they reference some rspec helper gem to be optionally included in the Gemfile.

**Comment by domaindrivendev** [comment]
You've missed my point. I'm saying that rswag-specs DOESN'T CONTAIN any functionality that should ever be run outside of the test environment.

As someone who's been using different Swagger workflows for several years, I'm happy with the separation of concerns with the current gems. They go as follows ...

1. rswag-specs - for testing and generating a Swagger compatible spec __during DEV/TEST__.
2. rswag-api - for exposing the Swagger.json as a JSON endpoint __at runtime__.
3. rswag-ui - for exposing the swagger-ui __at runtime__

These provide value independently and as a composite (hence the top-level gem that combines them). For your information, many prominent gems do in fact use this pattern of combining subgems including [Rails](https://github.com/rails/rails/blob/master/rails.gemspec) and [Rspec](https://github.com/rspec/rspec/blob/master/rspec.gemspec).

**Comment by klobuczek** [comment]
My apologies, you are right, rails does include testing framework inside their subgems. Not in the gemspec you referenced as all those gems are production gems and there is no mix between test and other environments. But this gemspec references mini-test https://github.com/rails/rails/blob/master/activesupport/activesupport.gemspec.
rspec gem does include other subgems, but all those gems are for test environment, so no mix.
In any case putting 'rswag-specs' in the test group solves my problem.
Thanks for the good work.

**Comment by supairish** [comment]
I just ran into this same issue when trying to deploy an app with newly added swagger docs.  Declaring each gem individually fixed it for me.  This should probably be added to the README for clarification and to help others new to rswag, like myself

**Comment by loicginoux** [comment]
I also had this issue and used the work around proposed here. The only problem now is that you have to pass the test env to swaggerize your doc. the rake task does not exist on other envs :/

```
RAILS_ENV=test rake rswag:specs:swaggerize
```

**Comment by domaindrivendev** [comment]
Closing as details for including gems in appropriate bundle groups have been added to readme - https://github.com/domaindrivendev/rswag#getting-started.
