### ISSUE TITLE
[REQUEST] support rails 8.0

### ISSUE THREAD

**Issue by balakirevs** [rswag/rswag#798]
rswag-api, rswag-specs, rswag-ui

Could not find compatible versions

Because rswag-api >= 2.14.0 depends on railties >= 5.2, < 8.0
  and rails >= 8.0.0 depends on railties = 8.0.0,
  rswag-api >= 2.14.0 is incompatible with rails >= 8.0.0.
So, because Gemfile depends on rails ~> 8.0.0
  and Gemfile depends on rswag-api ~> 2.15.0,
  version solving has failed.

**Comment by romanblanco** [comment]
https://github.com/rswag/rswag/compare/2.15.0...2.16.0

https://rubygems.org/gems/rswag/versions/2.16.0
