### ISSUE TITLE
`require': cannot load such file -- swagger_helper

### ISSUE THREAD

**Issue by angelolao** [rswag/rswag#8]
Hi,

I'm trying to use this but I get this error when doing `rake swaggerize`

```
/Users/my-name/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- swagger_helper (LoadError)
```

Everything out of the box doing `rails g swagger_rails:install`

just added a file `spec/api/controllers/posts_controller_spec.rb`

```
require 'swagger_helper'

describe "posts api" do

  path "/posts/{id}" do

  ...

```

Rails 4.2.7
ruby 2.3.0

Is there any definitive guide for this gem? 
Thank you in advanced. 😄

**Comment by domaindrivendev** [comment]
In terms of documentation, the readme is all I've had the time to put together at this point :(

Can you confirm that swagger_helper.rb was in fact installed. It should be sitting alongside "spec_helper" and "rails_helper" at the root of your "spec" folder?

**Comment by gerrypower** [comment]
I had a similar problem ... the issue seems to be the gemspec only specifies rspec-rails as a **development** dependency. It seems it's actually a dependency for swagger_rails. A workaround that worked for me, was to specify rspec-rails in my Gemfile, then:
1.  bundle install
2. rails generate spec:install (as per the rspec docs)
3. rails g swagger_rails:install
4. create a sample spec as per swagger_rails doc
5. rake swaggerize

That generated the swagger files and they appear when I ran the server.

**Comment by internationalbridgeinc** [comment]
I'm having the same problem. I can't find swagger_helper.rb anywhere in the gem. It looks like the install picks it up from the templates directory and copies it to spec. But I can't see a templates directory.

**Comment by drewish** [comment]
@harrywhitehouse the file is in the gem at: https://github.com/domaindrivendev/swagger_rails/blob/master/lib/generators/swagger_rails/install/templates/swagger_helper.rb which should be getting picked up by the gemspecs's file list: https://github.com/domaindrivendev/swagger_rails/blob/master/swagger_rails.gemspec#L17

**Comment by benoittgt** [comment]
I had to add the file manually in `/spec` now it's work.

**Comment by francisnkhata** [comment]
> I had a similar problem ... the issue seems to be the gemspec only specifies rspec-rails as a **development** dependency. It seems it's actually a dependency for swagger_rails. A workaround that worked for me, was to specify rspec-rails in my Gemfile, then:
> 
> 1. bundle install
> 2. rails generate spec:install (as per the rspec docs)
> 3. rails g swagger_rails:install
> 4. create a sample spec as per swagger_rails doc
> 5. rake swaggerize
> 
> That generated the swagger files and they appear when I ran the server.

How did you do this ..? Please show me a snapshot of the gem file. Getting the same error now 3 days

**Comment by francisnkhata** [comment]
This is my gemfile

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 2.5.3', '< 3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.4.3'
# Use sqlite3 as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 4.3.8'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Json Web Token (JWT) for token based authentication
gem 'jwt'

# Use the browser gem to get browser information
gem 'browser'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'passenger'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

gem 'composite_primary_keys'
gem 'rest-client'

gem 'test-unit'

gem 'rswag-api'
gem 'rswag-ui'

gem 'emr_ohsp_interface', '~> 1.2.2'
gem 'his_emr_api_lab', '~> 1.1.30'
gem 'his_emr_api_radiology', '~> 0.0.8'

gem 'parallel', '~> 1.20.1'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :test do
  gem 'factory_bot_rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rswag-specs'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'whenever', '~> 1.0'

# gems for reading excel and csv files
gem 'roo', '~> 2.8'
```
