### ISSUE TITLE
Question: what is the purpose of schema?

### ISSUE THREAD

**Issue by zlesnr** [rswag/rswag#80]
I'm seeing the schema in swagger, as well as used in the rswag gem, but I don't understand its purpose.  Is it to test the results of a call?  When is it required?  Is it ever advisable to leave it off?

**Comment by domaindrivendev** [comment]
You can use `schema` to indicate the expected structure (JSON Schema) of the response payload for a given status code. If it's included and you use `run_test!` or `assert_response_matches_metadata!` as described in the readme, then rswag will automatically validate the structure of the actual response payload against that schema. If you're testing an operation that does return a payload, you should use `schema` to describe it.
