### ISSUE TITLE
Description for tags and summary missing from UI

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#83]
Hi everyone,

In my API docs, I'd like to have a short intro/description of each tag and each method for the users to quickly understand what the sections and methods are responsible for. Swagger supports both features **description of tags** (https://swagger.io/specification/#tag-object-71), **summary for an endpoint** (https://swagger.io/specification/#operation-object-36). In the case of tags, Rswag nicely generates something along these lines to swagger.json:

`"tags" : {
    "Users" : {
      "description" : "These actions relate to user objects"
    },
    "Articles" : {
      "description" : "These actions relate to articles"
    }
  }`
But this never shows up in the UI.

However, Swaggerizer seems not to recognize the keyword 'summary'. The following code:

`post 'Creates a blog' do
      tags 'Blogs'
      consumes 'application/json', 'application/xml'
      description 'This section displays nicely in the UI'
      summary 'Swaggerizer does not like this keyword though'
      parameter name: :blog, in: :body, schema: {`

results in the following error:

`block (4 levels) in <top (required)>': undefined method `summary' for #<Class:0x0000000d32c078> (NoMethodError)`

Could you advise me whether I'm doing something wrong or whether Rswag and it's version of UI do not have such features.

Thanks in advance!

**Comment by domaindrivendev** [comment]
The swagger "summary" field is actually taken from the string that's passed to "post" in your example above. I can understand your confusion though and will likely add support to provide this along with the other fields.

Also worth noting - you can use "description" for displaying more detailed notes

**Comment by seriousbee** [comment]
It worked perfectly! Thank you for explaining! 

How about the description of the tags? I am looking to do something like "Everything about the pets" in this screenshot:

![screenshot from 2017-07-25 10 47 45](https://user-images.githubusercontent.com/9888476/28566411-f85ef94c-7126-11e7-9790-49f2b043df0b.png)

**Comment by talolierwork** [comment]
+1

**Comment by domaindrivendev** [comment]
You can add descriptions for tags (by name) in `swagger_helper.rb`

```ruby
RSpec.configure do |config|

  ...

  config.swagger_docs = {
    'v1/swagger.json' => {
      swagger: '2.0',
      info: {
        title: 'API V1',
        version: 'v1'
      },
      paths: {},
      tags: [
        {
          name: 'pet',
          description: 'Everything about your Pets'
        }
      ]
    }
  }
end
```
