### ISSUE TITLE
Assigning *_spec.rb files to versions of API

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#84]
Hi everyone,

The API I am documenting is made of 3 versions, each of them varying in the methods they provide and schema of objects they output. I would like to document this with Rswag but I am stuck :/

I followed the instructions in ReadMe regarding adding multiple versions of API (updating rswag_ui.rb file and swagger_helper.rb). At this point, swaggerizer parses everything without issues and in the UI I can switch between versions. 

I want to create different *_spec.rb files for each endpoint in each API version. The problem is that  **ReadMe does not specify how does swaggerizer know which version should a given _spec.rb file be associated with.** I tried putting *_spec.rb  files in different folders - /api/v1, /api/v2 etc however it still does not work.

Could you please advise me how can this be done??

Thank you in advance

**Comment by domaindrivendev** [comment]
Not sure if you saw the following in the readme - but it was my "attempt" at explaining it :)

__NOTE__: By default, the paths, operations and responses defined in your spec files will be associated with the first Swagger document in _swagger_helper.rb_. If you're using multiple documents, you'll need to tag the individual specs with their target document name:

```ruby
# spec/integration/v2/blogs_spec.rb
describe 'Blogs API', swagger_doc: 'v2/swagger.json' do

  path '/blogs' do
  ...

  path '/blogs/{id}' do
  ...
end
```

**Comment by seriousbee** [comment]
I must have missed this part of the doc :/

Thank you! :)
