### ISSUE TITLE
List of all object models in UI

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#85]
Hi there!

Is it possible to add a section at the bottom of the UI website with all object models used in the API? 
I would be looking for something like this:

![screenshot from 2017-07-25 10 48 26](https://user-images.githubusercontent.com/9888476/28567760-6d904302-712b-11e7-81a0-04cbd65454c4.png)

Currently, one can only see the models where they are actually being used,
![screenshot from 2017-07-25 11 04 10](https://user-images.githubusercontent.com/9888476/28567808-8dc92a80-712b-11e7-878f-70a7e309ad3f.png)

 but there is no single place with all the models. Or did I miss something?

Thanks

**Comment by daniel-sullivan** [comment]
This is available in Swagger UI 3.x which you can get from PR #66 (that's if you want to do the fork and merge yourself)

**Comment by domaindrivendev** [comment]
Available as of v2.0.0
