### ISSUE TITLE
Creating tables

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#86]
Having spent quite a lot of time figuring out how to make tables display in the UI, I'd like to share my solution to hopefully spare some time for someone in the future.

The normal markdown table syntax looks as follows:
```
| Column1 | Collumn2 |
| ------- | -------- |
| cell1   | cell2    | 
```

However, in RSwag this displays in quite an interesting fashion:
![screenshot from 2017-07-28 10 49 38](https://user-images.githubusercontent.com/9888476/28714398-32e51c02-738b-11e7-824e-3ff9244e0b55.png)

In order to get the "real" table output:
![screenshot from 2017-07-28 11 52 57](https://user-images.githubusercontent.com/9888476/28714433-55805c5e-738b-11e7-9be8-37a2c6e2a1f2.png)

One has to use this syntax:
```
&#13;
| Column1 | Collumn2 |&#13;
| ------- | -------- |&#13;
| cell1   | cell2    |&#13;
&#13;
```
Making sure there are no white spaces in front of any lines of the code above. 

I hope I was able to help someone!

**Comment by domaindrivendev** [comment]
Nice - would you be interested in submitting a PR to update the readme?

**Comment by boehle** [comment]
@seriousbee quick question regarding this issue. Could you provide a simple example of a full string including the property you assigned it to (e.g. description "…………").
I'm currently trying to figure this out as well and it just won't work for me, even with your code example.

**Comment by vokshirg** [comment]
Does anybody found the way how to implement it? Thanks!

**Comment by vokshirg** [comment]
oh, there is just a wrong example 

works for me: 
```ruby
      description <<~MD
        | Tables        | Are           | Cool  |
        | ------------- |:-------------:| -----:|
        | col 3 is      | right-aligned | $1600 |
        | col 2 is      | centered      |   $12 |
        | zebra stripes | are neat      |    $1 |
      MD
```

![image](https://user-images.githubusercontent.com/10025264/150153403-2f4f8cae-2389-4608-a4c4-82a57dc8df7b.png)
