### ISSUE TITLE
How to include body prams for put api method?

### ISSUE THREAD

**Issue by zlesnr** [rswag/rswag#91]
I've got a test that has the following:

```ruby
 require 'swagger_helper'

describe 'Port API' do

  path '/port/admin_state' do
    put 'Sets the admin state for a port' do
      security [ Token: [] ]
      produces 'application/json'
      consumes 'application/json'

      let(:api_key) { FactoryGirl.create(:api_key) }
      let(:Authorization) { "Token token=\"#{api_key.access_token}\"" }

      parameter name: :device_id,
        in: :body,
        type: 'string',
        required: true,
        description: 'Numeric device identifier'
      
      before do |example|
        @device = FactoryGirl.create(:device)
        @port = FactoryGirl.create(:port, device: @device)
        submit_request(example.metadata)
      end

      response '200', 'A port was toggled successfully' do
        let(:device_id) { @device.id }

        schema type: :object,
          properties: {
            status: { type: :string },
            error: { type: :string }
          }

        it do
          data = JSON.parse(response.body)
          p data
          expect(data.class).to be(Hash)
          expect(response.status).to eq(200)
        end
      end
    end

  end
end

```

For my get operations, all of the parameters have been in the query string.  For this particular method, I'm looking to use body parameters in the request.  I see when executing code against the endpoint, that the `params` object does indeed get populated with the params I've sent in the body.  However, when testing with rswag, I don't see those parameters submitted in the request.  Furthermore, I don't see anything related to my body parameters in the `example.metadata` object.  How do I get the body params to get submitted as json to the endpoint?

**Comment by domaindrivendev** [comment]
You're definition of a body parameter is incorrect. Have you looked at the "post" example at the beginning of the readme?

**Comment by domaindrivendev** [comment]
As per the [swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject), body parameter descriptions need to include the `schema` field to describe the structure of the expected JSON object.

Then in your tests, you assign the parameter value by passing a corresponding object to a `let` block

**Comment by zlesnr** [comment]
I see, thank you for the response.  I was expecting that each of the `properties` in the object was in fact a `parameter`.  Defining a single `parameter` as an `object`, even though the name doesn't appear to be used in the body, I was able to assign the keys of the hash to the properties.
