### ISSUE TITLE
Method 'description' from 'example_group.rb' has no parameters

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#93]
For each endpoint, I provide a few sentences describing what is it for. 

The following code correctly generates the swagger.json file and includes description of the endpoint.
```
get 'pets' do
      produces 'application/json'
      description 'Some description'
```

However, my IDE, RubyMine, complains all the time that the description method has 0 parameters while I have provided 1. 
 
Why does the method description from example_group.rb have no parameters?

**Comment by daniel-sullivan** [comment]
I'm also using Rubymine and have replicated the issue. Happily it's related to an issue in the parameters code in relation to overrides which I've already risen a ticket for some time ago (https://youtrack.jetbrains.com/issue/RUBY-18948)

If you look at the Rswag::Spec:ExampleGroupHelpers, description has this:

```
 # NOTE: 'description' requires special treatment because ExampleGroup already
      # defines a method with that name. Provide an override that supports the existing
      # functionality while also setting the appropriate metadata if applicable
      def description(value=nil)
        return super() if value.nil?
        metadata[:operation][:description] = value
      end
```

This is pretty much just a Rubymine bug
