### ISSUE TITLE
travis change prevents using github gem reference in Gemfile

### ISSUE THREAD

**Issue by dan-ding** [rswag/rswag#94]
The changes in: https://github.com/domaindrivendev/rswag/commit/3404fa72aab208e626ff1e932f67523532c2b5fe
(or maybe it was the other one)

prevent using in the Gemfile something like:
gem 'rswag', '~> 1.2.3', git: 'https://github.com/domaindrivendev/rswag.git', branch: 'master'

As the version will always return 0.0.0 to bundler.
Of course, a fix is to remove the version requirement, however it still reports the version to be 0.0.0

**Comment by BookOfGreg** [comment]
I've never worked on a gem that uses the travis tags to fill in the version number but I must say as a maintainer it's VERY convenient for me.
I understand it's a problem but thank you for identifying you can remove the version constraint in the file as a solution.

Going to close this for now as it's quite a stale issue.
