### ISSUE TITLE
Nested GET parameters?

### ISSUE THREAD

**Issue by fbrix** [rswag/rswag#99]
Is there some definition how to use nested GET parameters within tests? 
This does not work:
```ruby
parameter name: :checkboxes,
  in: :path,
  description: 'The values of marked checkboxes',
  type: :array,
  items: {
    type: :string
  }
```

the final I am trying to call URL looks like this:  `/?checkboxes[]=Value 1&checkboxes[]=Value 2`

Thank you in advance!

**Comment by domaindrivendev** [comment]
Try the following ...

```ruby
parameter name: :'checkboxes[]', in: :query, type: :array, collectionFormat: :multi
```

**Comment by benoittgt** [comment]
I had an error on Swagger UI with the definition of the array using `collectionFormat: :multi`.

<img width="1438" alt="Screenshot 2021-03-01 at 11 51 26" src="https://user-images.githubusercontent.com/8417720/109510260-15904880-7aa2-11eb-8557-e934eaef7716.png">

But with the schema defined like this it works. 

```ruby
      parameter name: :'apps[]',
                in: :query,
                required: false,
                type: :array,
                collectionFormat: :multi,
                schema: { type: 'array', items: { type: 'string' } }
```

Swagger UI is not able to render it properly.

<img width="548" alt="Screenshot 2021-03-01 at 12 43 24" src="https://user-images.githubusercontent.com/8417720/109511844-c4815400-7aa3-11eb-97dc-8222f43bbc07.png">


BTW it is still not OpenApi 3 compatible. https://github.com/rswag/rswag/issues/256#issuecomment-780240614

**Comment by paulomcnally** [comment]
Any solution for object/hash?

**Comment by jtannas** [comment]
Added to the FAQ here: https://github.com/rswag/rswag/wiki/FAQ#how-can-i-submit-arrays-through-query-parameters
